// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateMatchStats implements pgx.CopyFromSource.
type iteratorForCreateMatchStats struct {
	rows                 []CreateMatchStatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMatchStats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMatchStats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MatchID,
		r.rows[0].TeamID,
		r.rows[0].StatTypeID,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForCreateMatchStats) Err() error {
	return nil
}

func (q *Queries) CreateMatchStats(ctx context.Context, arg []CreateMatchStatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"match_stats"}, []string{"match_id", "team_id", "stat_type_id", "value"}, &iteratorForCreateMatchStats{rows: arg})
}

// iteratorForCreatePerformanceStats implements pgx.CopyFromSource.
type iteratorForCreatePerformanceStats struct {
	rows                 []CreatePerformanceStatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePerformanceStats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePerformanceStats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PerformanceID,
		r.rows[0].StatTypeID,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForCreatePerformanceStats) Err() error {
	return nil
}

func (q *Queries) CreatePerformanceStats(ctx context.Context, arg []CreatePerformanceStatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"performance_stats"}, []string{"performance_id", "stat_type_id", "value"}, &iteratorForCreatePerformanceStats{rows: arg})
}
