// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (
    name,
    iso2,
    iso3
) VALUES (
    $1, $2, $3
)
RETURNING id, name, iso2, iso3, created_at, updated_at
`

type CreateCountryParams struct {
	Name string `db:"name" json:"name"`
	Iso2 string `db:"iso2" json:"iso2"`
	Iso3 string `db:"iso3" json:"iso3"`
}

type CreateCountryRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (CreateCountryRow, error) {
	row := q.db.QueryRow(ctx, createCountry, arg.Name, arg.Iso2, arg.Iso3)
	var i CreateCountryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries
WHERE id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCountry, id)
	return err
}

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT id, name, iso2, iso3, created_at, updated_at
FROM countries
WHERE iso2 = UPPER($1) OR iso3 = UPPER($1) LIMIT 1
`

type GetCountryByCodeRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetCountryByCode(ctx context.Context, upper interface{}) (GetCountryByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCountryByCode, upper)
	var i GetCountryByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, iso2, iso3, created_at, updated_at
FROM countries
WHERE id = $1 LIMIT 1
`

type GetCountryByIDRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetCountryByID(ctx context.Context, id pgtype.UUID) (GetCountryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i GetCountryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, iso2, iso3, created_at, updated_at
FROM countries
ORDER BY name
`

type ListCountriesRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListCountries(ctx context.Context) ([]ListCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCountriesRow
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Iso2,
			&i.Iso3,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCountries = `-- name: SearchCountries :many
SELECT id, name, iso2, iso3, created_at, updated_at
FROM countries
WHERE name ILIKE $1 OR iso2 ILIKE $1 OR iso3 ILIKE $1
ORDER BY name
`

type SearchCountriesRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchCountries(ctx context.Context, name string) ([]SearchCountriesRow, error) {
	rows, err := q.db.Query(ctx, searchCountries, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCountriesRow
	for rows.Next() {
		var i SearchCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Iso2,
			&i.Iso3,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET 
    name = COALESCE($2, name),
    iso2 = COALESCE($3, iso2),
    iso3 = COALESCE($4, iso3),
    updated_at = now()
WHERE id = $1
RETURNING id, name, iso2, iso3, created_at, updated_at
`

type UpdateCountryParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Iso2 string      `db:"iso2" json:"iso2"`
	Iso3 string      `db:"iso3" json:"iso3"`
}

type UpdateCountryRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (UpdateCountryRow, error) {
	row := q.db.QueryRow(ctx, updateCountry,
		arg.ID,
		arg.Name,
		arg.Iso2,
		arg.Iso3,
	)
	var i UpdateCountryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
