// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchReview = `-- name: CreateMatchReview :one
INSERT INTO match_reviews (
    match_id,
    user_id,
    title,
    content
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, match_id, user_id, title, content, created_at, updated_at
`

type CreateMatchReviewParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Title   pgtype.Text `db:"title" json:"title"`
	Content string      `db:"content" json:"content"`
}

func (q *Queries) CreateMatchReview(ctx context.Context, arg CreateMatchReviewParams) (MatchReview, error) {
	row := q.db.QueryRow(ctx, createMatchReview,
		arg.MatchID,
		arg.UserID,
		arg.Title,
		arg.Content,
	)
	var i MatchReview
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatchReview = `-- name: DeleteMatchReview :exec
DELETE FROM match_reviews
WHERE id = $1
`

func (q *Queries) DeleteMatchReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatchReview, id)
	return err
}

const getMatchReviewAverageRating = `-- name: GetMatchReviewAverageRating :one
SELECT COALESCE(AVG(r.rating), 0.0)::numeric(2,1) AS average_rating
FROM match_reviews mr
JOIN match_ratings r ON mr.match_id = r.match_id AND mr.user_id = r.user_id
WHERE mr.match_id = $1
`

func (q *Queries) GetMatchReviewAverageRating(ctx context.Context, matchID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getMatchReviewAverageRating, matchID)
	var average_rating pgtype.Numeric
	err := row.Scan(&average_rating)
	return average_rating, err
}

const getMatchReviewByID = `-- name: GetMatchReviewByID :one
SELECT 
    mr.id, mr.match_id, mr.user_id, mr.title, mr.content, mr.created_at, mr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    m.title AS match_title, m.slug AS match_slug,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count
FROM match_reviews mr
JOIN users u ON mr.user_id = u.id
JOIN matches m ON mr.match_id = m.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM match_review_likes
    GROUP BY review_id
) likes ON mr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM match_review_comments
    GROUP BY review_id
) comments ON mr.id = comments.review_id
WHERE mr.id = $1 LIMIT 1
`

type GetMatchReviewByIDRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MatchID           pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	MatchTitle        string             `db:"match_title" json:"match_title"`
	MatchSlug         string             `db:"match_slug" json:"match_slug"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) GetMatchReviewByID(ctx context.Context, id pgtype.UUID) (GetMatchReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchReviewByID, id)
	var i GetMatchReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
		&i.MatchTitle,
		&i.MatchSlug,
		&i.LikesCount,
		&i.CommentCount,
	)
	return i, err
}

const getMatchReviewCount = `-- name: GetMatchReviewCount :one
SELECT COUNT(*)::bigint AS review_count
FROM match_reviews
WHERE match_id = $1
`

func (q *Queries) GetMatchReviewCount(ctx context.Context, matchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMatchReviewCount, matchID)
	var review_count int64
	err := row.Scan(&review_count)
	return review_count, err
}

const getMatchReviews = `-- name: GetMatchReviews :many
SELECT 
    mr.id, mr.match_id, mr.user_id, mr.title, mr.content, mr.created_at, mr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count,
    CASE WHEN $4::uuid IS NOT NULL THEN 
        EXISTS(SELECT 1 FROM match_review_likes WHERE review_id = mr.id AND user_id = $4)
    ELSE false END AS liked_by_me
FROM match_reviews mr
JOIN users u ON mr.user_id = u.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM match_review_likes
    GROUP BY review_id
) likes ON mr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM match_review_comments
    GROUP BY review_id
) comments ON mr.id = comments.review_id
WHERE mr.match_id = $1
ORDER BY mr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMatchReviewsParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
	Column4 pgtype.UUID `db:"column_4" json:"column_4"`
}

type GetMatchReviewsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MatchID           pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
	LikedByMe         bool               `db:"liked_by_me" json:"liked_by_me"`
}

func (q *Queries) GetMatchReviews(ctx context.Context, arg GetMatchReviewsParams) ([]GetMatchReviewsRow, error) {
	rows, err := q.db.Query(ctx, getMatchReviews,
		arg.MatchID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchReviewsRow
	for rows.Next() {
		var i GetMatchReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.LikesCount,
			&i.CommentCount,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularMatchReviews = `-- name: GetPopularMatchReviews :many
SELECT 
    mr.id, mr.match_id, mr.user_id, mr.title, mr.content, mr.created_at, mr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    m.title AS match_title, m.slug AS match_slug,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count
FROM match_reviews mr
JOIN users u ON mr.user_id = u.id
JOIN matches m ON mr.match_id = m.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM match_review_likes
    GROUP BY review_id
) likes ON mr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM match_review_comments
    GROUP BY review_id
) comments ON mr.id = comments.review_id
ORDER BY likes_count DESC, mr.created_at DESC
LIMIT $1 OFFSET $2
`

type GetPopularMatchReviewsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetPopularMatchReviewsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MatchID           pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	MatchTitle        string             `db:"match_title" json:"match_title"`
	MatchSlug         string             `db:"match_slug" json:"match_slug"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) GetPopularMatchReviews(ctx context.Context, arg GetPopularMatchReviewsParams) ([]GetPopularMatchReviewsRow, error) {
	rows, err := q.db.Query(ctx, getPopularMatchReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularMatchReviewsRow
	for rows.Next() {
		var i GetPopularMatchReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.LikesCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMatchReviews = `-- name: GetRecentMatchReviews :many
SELECT 
    mr.id, mr.match_id, mr.user_id, mr.title, mr.content, mr.created_at, mr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    m.title AS match_title, m.slug AS match_slug,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count
FROM match_reviews mr
JOIN users u ON mr.user_id = u.id
JOIN matches m ON mr.match_id = m.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM match_review_likes
    GROUP BY review_id
) likes ON mr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM match_review_comments
    GROUP BY review_id
) comments ON mr.id = comments.review_id
ORDER BY mr.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentMatchReviewsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentMatchReviewsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MatchID           pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	MatchTitle        string             `db:"match_title" json:"match_title"`
	MatchSlug         string             `db:"match_slug" json:"match_slug"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) GetRecentMatchReviews(ctx context.Context, arg GetRecentMatchReviewsParams) ([]GetRecentMatchReviewsRow, error) {
	rows, err := q.db.Query(ctx, getRecentMatchReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMatchReviewsRow
	for rows.Next() {
		var i GetRecentMatchReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.LikesCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMatchReviews = `-- name: GetUserMatchReviews :many
SELECT 
    mr.id, mr.match_id, mr.user_id, mr.title, mr.content, mr.created_at, mr.updated_at,
    m.title AS match_title, m.slug AS match_slug,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count
FROM match_reviews mr
JOIN matches m ON mr.match_id = m.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM match_review_likes
    GROUP BY review_id
) likes ON mr.id = likes.review_id
WHERE mr.user_id = $1
ORDER BY mr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserMatchReviewsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserMatchReviewsRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	MatchID    pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Title      pgtype.Text        `db:"title" json:"title"`
	Content    string             `db:"content" json:"content"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MatchTitle string             `db:"match_title" json:"match_title"`
	MatchSlug  string             `db:"match_slug" json:"match_slug"`
	LikesCount int64              `db:"likes_count" json:"likes_count"`
}

func (q *Queries) GetUserMatchReviews(ctx context.Context, arg GetUserMatchReviewsParams) ([]GetUserMatchReviewsRow, error) {
	rows, err := q.db.Query(ctx, getUserMatchReviews, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMatchReviewsRow
	for rows.Next() {
		var i GetUserMatchReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.LikesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserReviewedMatch = `-- name: HasUserReviewedMatch :one
SELECT EXISTS (
    SELECT 1 FROM match_reviews
    WHERE match_id = $1 AND user_id = $2
)::boolean AS has_reviewed
`

type HasUserReviewedMatchParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserReviewedMatch(ctx context.Context, arg HasUserReviewedMatchParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserReviewedMatch, arg.MatchID, arg.UserID)
	var has_reviewed bool
	err := row.Scan(&has_reviewed)
	return has_reviewed, err
}

const updateMatchReview = `-- name: UpdateMatchReview :one
UPDATE match_reviews
SET 
    title = COALESCE($2, title),
    content = COALESCE($3, content),
    updated_at = now()
WHERE id = $1
RETURNING id, match_id, user_id, title, content, created_at, updated_at
`

type UpdateMatchReviewParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Title   pgtype.Text `db:"title" json:"title"`
	Content string      `db:"content" json:"content"`
}

func (q *Queries) UpdateMatchReview(ctx context.Context, arg UpdateMatchReviewParams) (MatchReview, error) {
	row := q.db.QueryRow(ctx, updateMatchReview, arg.ID, arg.Title, arg.Content)
	var i MatchReview
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
