// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchStat = `-- name: CreateMatchStat :one
INSERT INTO match_stats (
    match_id,
    team_id,
    stat_type_id,
    value
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, match_id, team_id, stat_type_id, value, created_at
`

type CreateMatchStatParams struct {
	MatchID    pgtype.UUID    `db:"match_id" json:"match_id"`
	TeamID     pgtype.UUID    `db:"team_id" json:"team_id"`
	StatTypeID pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value      pgtype.Numeric `db:"value" json:"value"`
}

func (q *Queries) CreateMatchStat(ctx context.Context, arg CreateMatchStatParams) (MatchStat, error) {
	row := q.db.QueryRow(ctx, createMatchStat,
		arg.MatchID,
		arg.TeamID,
		arg.StatTypeID,
		arg.Value,
	)
	var i MatchStat
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.StatTypeID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

type CreateMatchStatsParams struct {
	MatchID    pgtype.UUID    `db:"match_id" json:"match_id"`
	TeamID     pgtype.UUID    `db:"team_id" json:"team_id"`
	StatTypeID pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value      pgtype.Numeric `db:"value" json:"value"`
}

const deleteMatchStat = `-- name: DeleteMatchStat :exec
DELETE FROM match_stats
WHERE match_id = $1 AND team_id = $2 AND stat_type_id = $3
`

type DeleteMatchStatParams struct {
	MatchID    pgtype.UUID `db:"match_id" json:"match_id"`
	TeamID     pgtype.UUID `db:"team_id" json:"team_id"`
	StatTypeID pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
}

func (q *Queries) DeleteMatchStat(ctx context.Context, arg DeleteMatchStatParams) error {
	_, err := q.db.Exec(ctx, deleteMatchStat, arg.MatchID, arg.TeamID, arg.StatTypeID)
	return err
}

const deleteMatchStats = `-- name: DeleteMatchStats :exec
DELETE FROM match_stats
WHERE match_id = $1
`

func (q *Queries) DeleteMatchStats(ctx context.Context, matchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatchStats, matchID)
	return err
}

const getMatchStats = `-- name: GetMatchStats :many
SELECT 
    ms.id, ms.match_id, ms.team_id, ms.stat_type_id, ms.value,
    st.name AS stat_name, st.short_name AS stat_short_name, st.unit AS stat_unit, st.category AS stat_category
FROM match_stats ms
JOIN stat_types st ON ms.stat_type_id = st.id
WHERE ms.match_id = $1
`

type GetMatchStatsRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	TeamID        pgtype.UUID    `db:"team_id" json:"team_id"`
	StatTypeID    pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric `db:"value" json:"value"`
	StatName      string         `db:"stat_name" json:"stat_name"`
	StatShortName string         `db:"stat_short_name" json:"stat_short_name"`
	StatUnit      pgtype.Text    `db:"stat_unit" json:"stat_unit"`
	StatCategory  string         `db:"stat_category" json:"stat_category"`
}

func (q *Queries) GetMatchStats(ctx context.Context, matchID pgtype.UUID) ([]GetMatchStatsRow, error) {
	rows, err := q.db.Query(ctx, getMatchStats, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchStatsRow
	for rows.Next() {
		var i GetMatchStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TeamID,
			&i.StatTypeID,
			&i.Value,
			&i.StatName,
			&i.StatShortName,
			&i.StatUnit,
			&i.StatCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMatchStats = `-- name: GetTeamMatchStats :many
SELECT 
    ms.id, ms.match_id, ms.team_id, ms.stat_type_id, ms.value,
    st.name AS stat_name, st.short_name AS stat_short_name, st.unit AS stat_unit, st.category AS stat_category
FROM match_stats ms
JOIN stat_types st ON ms.stat_type_id = st.id
WHERE ms.match_id = $1 AND ms.team_id = $2
`

type GetTeamMatchStatsParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	TeamID  pgtype.UUID `db:"team_id" json:"team_id"`
}

type GetTeamMatchStatsRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	TeamID        pgtype.UUID    `db:"team_id" json:"team_id"`
	StatTypeID    pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric `db:"value" json:"value"`
	StatName      string         `db:"stat_name" json:"stat_name"`
	StatShortName string         `db:"stat_short_name" json:"stat_short_name"`
	StatUnit      pgtype.Text    `db:"stat_unit" json:"stat_unit"`
	StatCategory  string         `db:"stat_category" json:"stat_category"`
}

func (q *Queries) GetTeamMatchStats(ctx context.Context, arg GetTeamMatchStatsParams) ([]GetTeamMatchStatsRow, error) {
	rows, err := q.db.Query(ctx, getTeamMatchStats, arg.MatchID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMatchStatsRow
	for rows.Next() {
		var i GetTeamMatchStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TeamID,
			&i.StatTypeID,
			&i.Value,
			&i.StatName,
			&i.StatShortName,
			&i.StatUnit,
			&i.StatCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMatchesByStat = `-- name: GetTopMatchesByStat :many
SELECT 
    ms.match_id, ms.team_id, ms.value,
    t.name AS team_name, t.logo_url AS team_logo_url,
    m.title AS match_title, m.slug AS match_slug, m.utc_datetime AS match_utc_datetime
FROM match_stats ms
JOIN teams t ON ms.team_id = t.id
JOIN matches m ON ms.match_id = m.id
WHERE ms.stat_type_id = $1
ORDER BY ms.value DESC
LIMIT $2 OFFSET $3
`

type GetTopMatchesByStatParams struct {
	StatTypeID pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetTopMatchesByStatRow struct {
	MatchID          pgtype.UUID        `db:"match_id" json:"match_id"`
	TeamID           pgtype.UUID        `db:"team_id" json:"team_id"`
	Value            pgtype.Numeric     `db:"value" json:"value"`
	TeamName         string             `db:"team_name" json:"team_name"`
	TeamLogoUrl      pgtype.Text        `db:"team_logo_url" json:"team_logo_url"`
	MatchTitle       string             `db:"match_title" json:"match_title"`
	MatchSlug        string             `db:"match_slug" json:"match_slug"`
	MatchUtcDatetime pgtype.Timestamptz `db:"match_utc_datetime" json:"match_utc_datetime"`
}

func (q *Queries) GetTopMatchesByStat(ctx context.Context, arg GetTopMatchesByStatParams) ([]GetTopMatchesByStatRow, error) {
	rows, err := q.db.Query(ctx, getTopMatchesByStat, arg.StatTypeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMatchesByStatRow
	for rows.Next() {
		var i GetTopMatchesByStatRow
		if err := rows.Scan(
			&i.MatchID,
			&i.TeamID,
			&i.Value,
			&i.TeamName,
			&i.TeamLogoUrl,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.MatchUtcDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchStat = `-- name: UpdateMatchStat :one
UPDATE match_stats
SET value = $4
WHERE match_id = $1 AND team_id = $2 AND stat_type_id = $3
RETURNING id, match_id, team_id, stat_type_id, value, created_at
`

type UpdateMatchStatParams struct {
	MatchID    pgtype.UUID    `db:"match_id" json:"match_id"`
	TeamID     pgtype.UUID    `db:"team_id" json:"team_id"`
	StatTypeID pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value      pgtype.Numeric `db:"value" json:"value"`
}

func (q *Queries) UpdateMatchStat(ctx context.Context, arg UpdateMatchStatParams) (MatchStat, error) {
	row := q.db.QueryRow(ctx, updateMatchStat,
		arg.MatchID,
		arg.TeamID,
		arg.StatTypeID,
		arg.Value,
	)
	var i MatchStat
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.StatTypeID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
