// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMatchRating = `-- name: DeleteMatchRating :exec
DELETE FROM match_ratings
WHERE match_id = $1 AND user_id = $2
`

type DeleteMatchRatingParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteMatchRating(ctx context.Context, arg DeleteMatchRatingParams) error {
	_, err := q.db.Exec(ctx, deleteMatchRating, arg.MatchID, arg.UserID)
	return err
}

const getMatchAverageRating = `-- name: GetMatchAverageRating :one
SELECT 
    COALESCE(AVG(rating), 0.0)::numeric(3,1) AS average_rating,
    COUNT(id)::bigint AS total_votes
FROM match_ratings
WHERE match_id = $1
`

type GetMatchAverageRatingRow struct {
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	TotalVotes    int64          `db:"total_votes" json:"total_votes"`
}

func (q *Queries) GetMatchAverageRating(ctx context.Context, matchID pgtype.UUID) (GetMatchAverageRatingRow, error) {
	row := q.db.QueryRow(ctx, getMatchAverageRating, matchID)
	var i GetMatchAverageRatingRow
	err := row.Scan(&i.AverageRating, &i.TotalVotes)
	return i, err
}

const getMatchRating = `-- name: GetMatchRating :one
SELECT id, match_id, user_id, rating, created_at, updated_at
FROM match_ratings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMatchRating(ctx context.Context, id pgtype.UUID) (MatchRating, error) {
	row := q.db.QueryRow(ctx, getMatchRating, id)
	var i MatchRating
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchRatings = `-- name: GetMatchRatings :many
SELECT 
    mr.id, mr.match_id, mr.user_id, mr.rating, mr.created_at, mr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
FROM match_ratings mr
JOIN users u ON mr.user_id = u.id
WHERE mr.match_id = $1
ORDER BY mr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMatchRatingsParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type GetMatchRatingsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MatchID           pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating            pgtype.Numeric     `db:"rating" json:"rating"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
}

func (q *Queries) GetMatchRatings(ctx context.Context, arg GetMatchRatingsParams) ([]GetMatchRatingsRow, error) {
	rows, err := q.db.Query(ctx, getMatchRatings, arg.MatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchRatingsRow
	for rows.Next() {
		var i GetMatchRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchRatingsCount = `-- name: GetMatchRatingsCount :one
SELECT COUNT(*)::bigint AS ratings_count
FROM match_ratings
WHERE match_id = $1
`

func (q *Queries) GetMatchRatingsCount(ctx context.Context, matchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMatchRatingsCount, matchID)
	var ratings_count int64
	err := row.Scan(&ratings_count)
	return ratings_count, err
}

const getRecentlyRatedMatches = `-- name: GetRecentlyRatedMatches :many
SELECT 
    m.id, m.home_team_id, m.away_team_id, m.title, m.slug, m.utc_datetime, m.home_score, m.away_score,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url,
    latest_rating.max_created_at AS rated_at
FROM (
    SELECT match_id, MAX(created_at) AS max_created_at
    FROM match_ratings
    GROUP BY match_id
) latest_rating
JOIN matches m ON latest_rating.match_id = m.id
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
ORDER BY rated_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentlyRatedMatchesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentlyRatedMatchesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	HomeTeamID      pgtype.UUID        `db:"home_team_id" json:"home_team_id"`
	AwayTeamID      pgtype.UUID        `db:"away_team_id" json:"away_team_id"`
	Title           string             `db:"title" json:"title"`
	Slug            string             `db:"slug" json:"slug"`
	UtcDatetime     pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	HomeScore       int32              `db:"home_score" json:"home_score"`
	AwayScore       int32              `db:"away_score" json:"away_score"`
	HomeTeamName    string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	AwayTeamName    string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
	RatedAt         interface{}        `db:"rated_at" json:"rated_at"`
}

func (q *Queries) GetRecentlyRatedMatches(ctx context.Context, arg GetRecentlyRatedMatchesParams) ([]GetRecentlyRatedMatchesRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyRatedMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyRatedMatchesRow
	for rows.Next() {
		var i GetRecentlyRatedMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Title,
			&i.Slug,
			&i.UtcDatetime,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
			&i.RatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRatedMatches = `-- name: GetTopRatedMatches :many
SELECT 
    m.id, m.home_team_id, m.away_team_id, m.title, m.slug, m.utc_datetime, m.home_score, m.away_score,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url,
    m.average_rating,
    m.total_votes
FROM matches m
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
ORDER BY m.average_rating DESC, m.utc_datetime DESC
LIMIT $1 OFFSET $2
`

type GetTopRatedMatchesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetTopRatedMatchesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	HomeTeamID      pgtype.UUID        `db:"home_team_id" json:"home_team_id"`
	AwayTeamID      pgtype.UUID        `db:"away_team_id" json:"away_team_id"`
	Title           string             `db:"title" json:"title"`
	Slug            string             `db:"slug" json:"slug"`
	UtcDatetime     pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	HomeScore       int32              `db:"home_score" json:"home_score"`
	AwayScore       int32              `db:"away_score" json:"away_score"`
	HomeTeamName    string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	AwayTeamName    string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
	AverageRating   pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	TotalVotes      pgtype.Int4        `db:"total_votes" json:"total_votes"`
}

func (q *Queries) GetTopRatedMatches(ctx context.Context, arg GetTopRatedMatchesParams) ([]GetTopRatedMatchesRow, error) {
	rows, err := q.db.Query(ctx, getTopRatedMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopRatedMatchesRow
	for rows.Next() {
		var i GetTopRatedMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Title,
			&i.Slug,
			&i.UtcDatetime,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
			&i.AverageRating,
			&i.TotalVotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMatchRating = `-- name: GetUserMatchRating :one
SELECT id, match_id, user_id, rating, created_at, updated_at
FROM match_ratings
WHERE match_id = $1 AND user_id = $2 LIMIT 1
`

type GetUserMatchRatingParams struct {
	MatchID pgtype.UUID `db:"match_id" json:"match_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserMatchRating(ctx context.Context, arg GetUserMatchRatingParams) (MatchRating, error) {
	row := q.db.QueryRow(ctx, getUserMatchRating, arg.MatchID, arg.UserID)
	var i MatchRating
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rateMatch = `-- name: RateMatch :one
INSERT INTO match_ratings (
    match_id,
    user_id,
    rating
) VALUES (
    $1, $2, $3
)
ON CONFLICT (match_id, user_id) 
DO UPDATE SET 
    rating = EXCLUDED.rating,
    updated_at = now()
RETURNING id, match_id, user_id, rating, created_at, updated_at
`

type RateMatchParams struct {
	MatchID pgtype.UUID    `db:"match_id" json:"match_id"`
	UserID  pgtype.UUID    `db:"user_id" json:"user_id"`
	Rating  pgtype.Numeric `db:"rating" json:"rating"`
}

func (q *Queries) RateMatch(ctx context.Context, arg RateMatchParams) (MatchRating, error) {
	row := q.db.QueryRow(ctx, rateMatch, arg.MatchID, arg.UserID, arg.Rating)
	var i MatchRating
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshMatchRating = `-- name: RefreshMatchRating :exec
UPDATE matches SET
    average_rating = COALESCE((SELECT AVG(rating) FROM match_ratings mr WHERE mr.match_id = $1), 0)::numeric(3,1),
    total_votes = (SELECT COUNT(*) FROM match_ratings mr WHERE mr.match_id = $1)::int
WHERE id = $1
`

// Recomputes and persists the stored average_rating/total_votes for a match.
// Call after any rating mutation. Matches have no provider seed.
func (q *Queries) RefreshMatchRating(ctx context.Context, matchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshMatchRating, matchID)
	return err
}

const updateMatchRating = `-- name: UpdateMatchRating :one
UPDATE match_ratings
SET 
    rating = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, match_id, user_id, rating, created_at, updated_at
`

type UpdateMatchRatingParams struct {
	ID     pgtype.UUID    `db:"id" json:"id"`
	Rating pgtype.Numeric `db:"rating" json:"rating"`
}

func (q *Queries) UpdateMatchRating(ctx context.Context, arg UpdateMatchRatingParams) (MatchRating, error) {
	row := q.db.QueryRow(ctx, updateMatchRating, arg.ID, arg.Rating)
	var i MatchRating
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
