// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ReviewStatus string

const (
	ReviewStatusPENDING  ReviewStatus = "PENDING"
	ReviewStatusAPPROVED ReviewStatus = "APPROVED"
	ReviewStatusFLAGGED  ReviewStatus = "FLAGGED"
	ReviewStatusREMOVED  ReviewStatus = "REMOVED"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type TeamType string

const (
	TeamTypeCLUB     TeamType = "CLUB"
	TeamTypeNATIONAL TeamType = "NATIONAL"
)

func (e *TeamType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamType(s)
	case string:
		*e = TeamType(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamType: %T", src)
	}
	return nil
}

type NullTeamType struct {
	TeamType TeamType `json:"team_type"`
	Valid    bool     `json:"valid"` // Valid is true if TeamType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamType) Scan(value interface{}) error {
	if value == nil {
		ns.TeamType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamType), nil
}

type TournamentType string

const (
	TournamentTypeLEAGUE TournamentType = "LEAGUE"
	TournamentTypeCUP    TournamentType = "CUP"
)

func (e *TournamentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TournamentType(s)
	case string:
		*e = TournamentType(s)
	default:
		return fmt.Errorf("unsupported scan type for TournamentType: %T", src)
	}
	return nil
}

type NullTournamentType struct {
	TournamentType TournamentType `json:"tournament_type"`
	Valid          bool           `json:"valid"` // Valid is true if TournamentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTournamentType) Scan(value interface{}) error {
	if value == nil {
		ns.TournamentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TournamentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTournamentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TournamentType), nil
}

type UserRole string

const (
	UserRoleUSER  UserRole = "USER"
	UserRoleADMIN UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Country struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Iso2      string             `db:"iso2" json:"iso2"`
	Iso3      string             `db:"iso3" json:"iso3"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FlagEmoji pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
}

type Match struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	HomeTeamID       pgtype.UUID        `db:"home_team_id" json:"home_team_id"`
	AwayTeamID       pgtype.UUID        `db:"away_team_id" json:"away_team_id"`
	Title            string             `db:"title" json:"title"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Round            pgtype.Text        `db:"round" json:"round"`
	UtcDatetime      pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	Venue            pgtype.Text        `db:"venue" json:"venue"`
	CoverImageUrl    pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	HomeScore        int32              `db:"home_score" json:"home_score"`
	AwayScore        int32              `db:"away_score" json:"away_score"`
	HomePenaltyScore pgtype.Int4        `db:"home_penalty_score" json:"home_penalty_score"`
	AwayPenaltyScore pgtype.Int4        `db:"away_penalty_score" json:"away_penalty_score"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Tagline          pgtype.Text        `db:"tagline" json:"tagline"`
	AverageRating    pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	TotalVotes       pgtype.Int4        `db:"total_votes" json:"total_votes"`
}

type MatchRating struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	MatchID   pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating    pgtype.Numeric     `db:"rating" json:"rating"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MatchReview struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	MatchID   pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Title     pgtype.Text        `db:"title" json:"title"`
	Content   string             `db:"content" json:"content"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MatchReviewComment struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ReviewID  pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Body      string             `db:"body" json:"body"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MatchReviewCommentLike struct {
	CommentID pgtype.UUID        `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MatchReviewLike struct {
	ReviewID  pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MatchStat struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	MatchID    pgtype.UUID        `db:"match_id" json:"match_id"`
	TeamID     pgtype.UUID        `db:"team_id" json:"team_id"`
	StatTypeID pgtype.UUID        `db:"stat_type_id" json:"stat_type_id"`
	Value      pgtype.Numeric     `db:"value" json:"value"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Performance struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	MatchID       pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID  pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	CoverImageUrl pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber  pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	IsStarter     bool               `db:"is_starter" json:"is_starter"`
	Captain       bool               `db:"captain" json:"captain"`
	MinutesPlayed int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug          pgtype.Text        `db:"slug" json:"slug"`
	Tagline       pgtype.Text        `db:"tagline" json:"tagline"`
	TotalVotes    pgtype.Int4        `db:"total_votes" json:"total_votes"`
	SeedRating    pgtype.Numeric     `db:"seed_rating" json:"seed_rating"`
}

type PerformanceRating struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	PerformanceID pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PerformanceReview struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	PerformanceID pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Title         pgtype.Text        `db:"title" json:"title"`
	Content       string             `db:"content" json:"content"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PerformanceReviewComment struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ReviewID  pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Body      string             `db:"body" json:"body"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PerformanceReviewCommentLike struct {
	CommentID pgtype.UUID        `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PerformanceReviewLike struct {
	ReviewID  pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PerformanceStat struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	PerformanceID pgtype.UUID        `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID        `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric     `db:"value" json:"value"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Player struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Slug         string             `db:"slug" json:"slug"`
	FullName     pgtype.Text        `db:"full_name" json:"full_name"`
	KnownAs      pgtype.Text        `db:"known_as" json:"known_as"`
	DateOfBirth  pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	PlaceOfBirth pgtype.Text        `db:"place_of_birth" json:"place_of_birth"`
	CountryID    pgtype.UUID        `db:"country_id" json:"country_id"`
	PhotoUrl     pgtype.Text        `db:"photo_url" json:"photo_url"`
	HeightCm     pgtype.Int4        `db:"height_cm" json:"height_cm"`
	WeightKg     pgtype.Int4        `db:"weight_kg" json:"weight_kg"`
	ShirtName    pgtype.Text        `db:"shirt_name" json:"shirt_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PlayerTeam struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PlayerID     pgtype.UUID `db:"player_id" json:"player_id"`
	TeamID       pgtype.UUID `db:"team_id" json:"team_id"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate    pgtype.Date `db:"start_date" json:"start_date"`
	EndDate      pgtype.Date `db:"end_date" json:"end_date"`
	IsActive     bool        `db:"is_active" json:"is_active"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type StatType struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	ShortName    string      `db:"short_name" json:"short_name"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	Category     string      `db:"category" json:"category"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
}

type Team struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	Name        string             `db:"name" json:"name"`
	ShortName   string             `db:"short_name" json:"short_name"`
	Slug        string             `db:"slug" json:"slug"`
	Type        TeamType           `db:"type" json:"type"`
	LogoUrl     pgtype.Text        `db:"logo_url" json:"logo_url"`
	FoundedYear pgtype.Int4        `db:"founded_year" json:"founded_year"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FlagEmoji   pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
}

type TrendingScore struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	EntityType   string             `db:"entity_type" json:"entity_type"`
	EntityID     pgtype.UUID        `db:"entity_id" json:"entity_id"`
	TimeWindow   string             `db:"time_window" json:"time_window"`
	Score        pgtype.Numeric     `db:"score" json:"score"`
	Rank         int32              `db:"rank" json:"rank"`
	CalculatedAt pgtype.Timestamptz `db:"calculated_at" json:"calculated_at"`
}

type User struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Email         string             `db:"email" json:"email"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"password_hash"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Role          UserRole           `db:"role" json:"role"`
}

type UserOtp struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	OtpCode   string             `db:"otp_code" json:"otp_code"`
	Purpose   string             `db:"purpose" json:"purpose"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
