// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performance_ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePerformanceRating = `-- name: DeletePerformanceRating :exec
DELETE FROM performance_ratings
WHERE performance_id = $1 AND user_id = $2
`

type DeletePerformanceRatingParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeletePerformanceRating(ctx context.Context, arg DeletePerformanceRatingParams) error {
	_, err := q.db.Exec(ctx, deletePerformanceRating, arg.PerformanceID, arg.UserID)
	return err
}

const getPerformanceAverageRating = `-- name: GetPerformanceAverageRating :one
SELECT
    ((p.seed_rating + COALESCE(SUM(pr.rating), 0)) / (1 + COUNT(pr.id)))::numeric(3,1) AS average_rating,
    (1 + COUNT(pr.id))::bigint AS total_votes
FROM performances p
LEFT JOIN performance_ratings pr ON pr.performance_id = p.id
WHERE p.id = $1
GROUP BY p.seed_rating
`

type GetPerformanceAverageRatingRow struct {
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	TotalVotes    int64          `db:"total_votes" json:"total_votes"`
}

// Folds the provider seed rating in as the first vote so the live detail-page
// value matches the stored average_rating column.
func (q *Queries) GetPerformanceAverageRating(ctx context.Context, id pgtype.UUID) (GetPerformanceAverageRatingRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceAverageRating, id)
	var i GetPerformanceAverageRatingRow
	err := row.Scan(&i.AverageRating, &i.TotalVotes)
	return i, err
}

const getPerformanceRating = `-- name: GetPerformanceRating :one
SELECT id, performance_id, user_id, rating, created_at, updated_at
FROM performance_ratings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPerformanceRating(ctx context.Context, id pgtype.UUID) (PerformanceRating, error) {
	row := q.db.QueryRow(ctx, getPerformanceRating, id)
	var i PerformanceRating
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerformanceRatings = `-- name: GetPerformanceRatings :many
SELECT 
    pr.id, pr.performance_id, pr.user_id, pr.rating, pr.created_at, pr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
FROM performance_ratings pr
JOIN users u ON pr.user_id = u.id
WHERE pr.performance_id = $1
ORDER BY pr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPerformanceRatingsParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	Limit         int32       `db:"limit" json:"limit"`
	Offset        int32       `db:"offset" json:"offset"`
}

type GetPerformanceRatingsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PerformanceID     pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating            pgtype.Numeric     `db:"rating" json:"rating"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
}

func (q *Queries) GetPerformanceRatings(ctx context.Context, arg GetPerformanceRatingsParams) ([]GetPerformanceRatingsRow, error) {
	rows, err := q.db.Query(ctx, getPerformanceRatings, arg.PerformanceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPerformanceRatingsRow
	for rows.Next() {
		var i GetPerformanceRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformanceID,
			&i.UserID,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerformanceRatingsCount = `-- name: GetPerformanceRatingsCount :one
SELECT COUNT(*)::bigint AS ratings_count
FROM performance_ratings
WHERE performance_id = $1
`

func (q *Queries) GetPerformanceRatingsCount(ctx context.Context, performanceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPerformanceRatingsCount, performanceID)
	var ratings_count int64
	err := row.Scan(&ratings_count)
	return ratings_count, err
}

const getRecentlyRatedPerformances = `-- name: GetRecentlyRatedPerformances :many
SELECT 
    p.id, p.match_id, p.player_id, p.title, p.cover_image_url, p.average_rating,
    pl.name AS player_name, m.title AS match_title,
    latest_rating.max_created_at AS rated_at
FROM (
    SELECT performance_id, MAX(created_at) AS max_created_at
    FROM performance_ratings
    GROUP BY performance_id
) latest_rating
JOIN performances p ON latest_rating.performance_id = p.id
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
ORDER BY rated_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentlyRatedPerformancesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentlyRatedPerformancesRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID    `db:"player_id" json:"player_id"`
	Title         string         `db:"title" json:"title"`
	CoverImageUrl pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	PlayerName    string         `db:"player_name" json:"player_name"`
	MatchTitle    string         `db:"match_title" json:"match_title"`
	RatedAt       interface{}    `db:"rated_at" json:"rated_at"`
}

func (q *Queries) GetRecentlyRatedPerformances(ctx context.Context, arg GetRecentlyRatedPerformancesParams) ([]GetRecentlyRatedPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyRatedPerformances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyRatedPerformancesRow
	for rows.Next() {
		var i GetRecentlyRatedPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.Title,
			&i.CoverImageUrl,
			&i.AverageRating,
			&i.PlayerName,
			&i.MatchTitle,
			&i.RatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPerformanceRating = `-- name: GetUserPerformanceRating :one
SELECT id, performance_id, user_id, rating, created_at, updated_at
FROM performance_ratings
WHERE performance_id = $1 AND user_id = $2 LIMIT 1
`

type GetUserPerformanceRatingParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserPerformanceRating(ctx context.Context, arg GetUserPerformanceRatingParams) (PerformanceRating, error) {
	row := q.db.QueryRow(ctx, getUserPerformanceRating, arg.PerformanceID, arg.UserID)
	var i PerformanceRating
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ratePerformance = `-- name: RatePerformance :one
INSERT INTO performance_ratings (
    performance_id,
    user_id,
    rating
) VALUES (
    $1, $2, $3
)
ON CONFLICT (performance_id, user_id) 
DO UPDATE SET 
    rating = EXCLUDED.rating,
    updated_at = now()
RETURNING id, performance_id, user_id, rating, created_at, updated_at
`

type RatePerformanceParams struct {
	PerformanceID pgtype.UUID    `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID    `db:"user_id" json:"user_id"`
	Rating        pgtype.Numeric `db:"rating" json:"rating"`
}

func (q *Queries) RatePerformance(ctx context.Context, arg RatePerformanceParams) (PerformanceRating, error) {
	row := q.db.QueryRow(ctx, ratePerformance, arg.PerformanceID, arg.UserID, arg.Rating)
	var i PerformanceRating
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshPerformanceRating = `-- name: RefreshPerformanceRating :exec
UPDATE performances SET
    average_rating = sub.avg,
    total_votes = sub.cnt
FROM (
    SELECT ((p.seed_rating + COALESCE(SUM(pr.rating), 0)) / (1 + COUNT(pr.id)))::numeric(3,1) AS avg,
           (1 + COUNT(pr.id))::int AS cnt
    FROM performances p
    LEFT JOIN performance_ratings pr ON pr.performance_id = p.id
    WHERE p.id = $1
    GROUP BY p.seed_rating
) sub
WHERE performances.id = $1
`

// Recomputes and persists the stored average_rating/total_votes for a
// performance (seed vote + community votes). Call after any rating mutation.
func (q *Queries) RefreshPerformanceRating(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshPerformanceRating, id)
	return err
}

const updatePerformanceRating = `-- name: UpdatePerformanceRating :one
UPDATE performance_ratings
SET 
    rating = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, performance_id, user_id, rating, created_at, updated_at
`

type UpdatePerformanceRatingParams struct {
	ID     pgtype.UUID    `db:"id" json:"id"`
	Rating pgtype.Numeric `db:"rating" json:"rating"`
}

func (q *Queries) UpdatePerformanceRating(ctx context.Context, arg UpdatePerformanceRatingParams) (PerformanceRating, error) {
	row := q.db.QueryRow(ctx, updatePerformanceRating, arg.ID, arg.Rating)
	var i PerformanceRating
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
