// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performance_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerformanceStat = `-- name: CreatePerformanceStat :one
INSERT INTO performance_stats (
    performance_id,
    stat_type_id,
    value
) VALUES (
    $1, $2, $3
)
RETURNING id, performance_id, stat_type_id, value, created_at
`

type CreatePerformanceStatParams struct {
	PerformanceID pgtype.UUID    `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric `db:"value" json:"value"`
}

func (q *Queries) CreatePerformanceStat(ctx context.Context, arg CreatePerformanceStatParams) (PerformanceStat, error) {
	row := q.db.QueryRow(ctx, createPerformanceStat, arg.PerformanceID, arg.StatTypeID, arg.Value)
	var i PerformanceStat
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.StatTypeID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

type CreatePerformanceStatsParams struct {
	PerformanceID pgtype.UUID    `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric `db:"value" json:"value"`
}

const deletePerformanceStat = `-- name: DeletePerformanceStat :exec
DELETE FROM performance_stats
WHERE performance_id = $1 AND stat_type_id = $2
`

type DeletePerformanceStatParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
}

func (q *Queries) DeletePerformanceStat(ctx context.Context, arg DeletePerformanceStatParams) error {
	_, err := q.db.Exec(ctx, deletePerformanceStat, arg.PerformanceID, arg.StatTypeID)
	return err
}

const deletePerformanceStats = `-- name: DeletePerformanceStats :exec
DELETE FROM performance_stats
WHERE performance_id = $1
`

func (q *Queries) DeletePerformanceStats(ctx context.Context, performanceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerformanceStats, performanceID)
	return err
}

const getPerformanceStat = `-- name: GetPerformanceStat :one
SELECT 
    ps.id, ps.performance_id, ps.stat_type_id, ps.value,
    st.name AS stat_name, st.short_name AS stat_short_name, st.unit AS stat_unit, st.category AS stat_category
FROM performance_stats ps
JOIN stat_types st ON ps.stat_type_id = st.id
WHERE ps.performance_id = $1 AND ps.stat_type_id = $2 LIMIT 1
`

type GetPerformanceStatParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
}

type GetPerformanceStatRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	PerformanceID pgtype.UUID    `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric `db:"value" json:"value"`
	StatName      string         `db:"stat_name" json:"stat_name"`
	StatShortName string         `db:"stat_short_name" json:"stat_short_name"`
	StatUnit      pgtype.Text    `db:"stat_unit" json:"stat_unit"`
	StatCategory  string         `db:"stat_category" json:"stat_category"`
}

func (q *Queries) GetPerformanceStat(ctx context.Context, arg GetPerformanceStatParams) (GetPerformanceStatRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceStat, arg.PerformanceID, arg.StatTypeID)
	var i GetPerformanceStatRow
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.StatTypeID,
		&i.Value,
		&i.StatName,
		&i.StatShortName,
		&i.StatUnit,
		&i.StatCategory,
	)
	return i, err
}

const getPerformanceStats = `-- name: GetPerformanceStats :many
SELECT 
    ps.id, ps.performance_id, ps.stat_type_id, ps.value,
    st.name AS stat_name, st.short_name AS stat_short_name, st.unit AS stat_unit, st.category AS stat_category, st.display_order AS stat_display_order
FROM performance_stats ps
JOIN stat_types st ON ps.stat_type_id = st.id
WHERE ps.performance_id = $1
ORDER BY st.category, st.display_order
`

type GetPerformanceStatsRow struct {
	ID               pgtype.UUID    `db:"id" json:"id"`
	PerformanceID    pgtype.UUID    `db:"performance_id" json:"performance_id"`
	StatTypeID       pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value            pgtype.Numeric `db:"value" json:"value"`
	StatName         string         `db:"stat_name" json:"stat_name"`
	StatShortName    string         `db:"stat_short_name" json:"stat_short_name"`
	StatUnit         pgtype.Text    `db:"stat_unit" json:"stat_unit"`
	StatCategory     string         `db:"stat_category" json:"stat_category"`
	StatDisplayOrder int32          `db:"stat_display_order" json:"stat_display_order"`
}

func (q *Queries) GetPerformanceStats(ctx context.Context, performanceID pgtype.UUID) ([]GetPerformanceStatsRow, error) {
	rows, err := q.db.Query(ctx, getPerformanceStats, performanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPerformanceStatsRow
	for rows.Next() {
		var i GetPerformanceStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformanceID,
			&i.StatTypeID,
			&i.Value,
			&i.StatName,
			&i.StatShortName,
			&i.StatUnit,
			&i.StatCategory,
			&i.StatDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPerformancesByStat = `-- name: GetTopPerformancesByStat :many
SELECT 
    ps.performance_id, ps.value,
    p.title AS performance_title, p.average_rating,
    pl.name AS player_name, pl.slug AS player_slug, pl.photo_url AS player_photo_url,
    m.title AS match_title, m.slug AS match_slug, m.utc_datetime AS match_utc_datetime
FROM performance_stats ps
JOIN performances p ON ps.performance_id = p.id
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
WHERE ps.stat_type_id = $1
ORDER BY ps.value DESC, p.average_rating DESC
LIMIT $2 OFFSET $3
`

type GetTopPerformancesByStatParams struct {
	StatTypeID pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetTopPerformancesByStatRow struct {
	PerformanceID    pgtype.UUID        `db:"performance_id" json:"performance_id"`
	Value            pgtype.Numeric     `db:"value" json:"value"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
	AverageRating    pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	PlayerName       string             `db:"player_name" json:"player_name"`
	PlayerSlug       string             `db:"player_slug" json:"player_slug"`
	PlayerPhotoUrl   pgtype.Text        `db:"player_photo_url" json:"player_photo_url"`
	MatchTitle       string             `db:"match_title" json:"match_title"`
	MatchSlug        string             `db:"match_slug" json:"match_slug"`
	MatchUtcDatetime pgtype.Timestamptz `db:"match_utc_datetime" json:"match_utc_datetime"`
}

func (q *Queries) GetTopPerformancesByStat(ctx context.Context, arg GetTopPerformancesByStatParams) ([]GetTopPerformancesByStatRow, error) {
	rows, err := q.db.Query(ctx, getTopPerformancesByStat, arg.StatTypeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPerformancesByStatRow
	for rows.Next() {
		var i GetTopPerformancesByStatRow
		if err := rows.Scan(
			&i.PerformanceID,
			&i.Value,
			&i.PerformanceTitle,
			&i.AverageRating,
			&i.PlayerName,
			&i.PlayerSlug,
			&i.PlayerPhotoUrl,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.MatchUtcDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerformanceStat = `-- name: UpdatePerformanceStat :one
UPDATE performance_stats
SET value = $3
WHERE performance_id = $1 AND stat_type_id = $2
RETURNING id, performance_id, stat_type_id, value, created_at
`

type UpdatePerformanceStatParams struct {
	PerformanceID pgtype.UUID    `db:"performance_id" json:"performance_id"`
	StatTypeID    pgtype.UUID    `db:"stat_type_id" json:"stat_type_id"`
	Value         pgtype.Numeric `db:"value" json:"value"`
}

func (q *Queries) UpdatePerformanceStat(ctx context.Context, arg UpdatePerformanceStatParams) (PerformanceStat, error) {
	row := q.db.QueryRow(ctx, updatePerformanceStat, arg.PerformanceID, arg.StatTypeID, arg.Value)
	var i PerformanceStat
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.StatTypeID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
