// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performance_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerformanceReview = `-- name: CreatePerformanceReview :one
INSERT INTO performance_reviews (
    performance_id,
    user_id,
    title,
    content
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, performance_id, user_id, title, content, created_at, updated_at
`

type CreatePerformanceReviewParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	Title         pgtype.Text `db:"title" json:"title"`
	Content       string      `db:"content" json:"content"`
}

func (q *Queries) CreatePerformanceReview(ctx context.Context, arg CreatePerformanceReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, createPerformanceReview,
		arg.PerformanceID,
		arg.UserID,
		arg.Title,
		arg.Content,
	)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePerformanceReview = `-- name: DeletePerformanceReview :exec
DELETE FROM performance_reviews
WHERE id = $1
`

func (q *Queries) DeletePerformanceReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerformanceReview, id)
	return err
}

const getPerformanceReviewAverageRating = `-- name: GetPerformanceReviewAverageRating :one
SELECT COALESCE(AVG(r.rating), 0.0)::numeric(2,1) AS average_rating
FROM performance_reviews pr
JOIN performance_ratings r ON pr.performance_id = r.performance_id AND pr.user_id = r.user_id
WHERE pr.performance_id = $1
`

func (q *Queries) GetPerformanceReviewAverageRating(ctx context.Context, performanceID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewAverageRating, performanceID)
	var average_rating pgtype.Numeric
	err := row.Scan(&average_rating)
	return average_rating, err
}

const getPerformanceReviewByID = `-- name: GetPerformanceReviewByID :one
SELECT 
    pr.id, pr.performance_id, pr.user_id, pr.title, pr.content, pr.created_at, pr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    p.title AS performance_title, pl.name AS player_name, m.title AS match_title,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count
FROM performance_reviews pr
JOIN users u ON pr.user_id = u.id
JOIN performances p ON pr.performance_id = p.id
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM performance_review_likes
    GROUP BY review_id
) likes ON pr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM performance_review_comments
    GROUP BY review_id
) comments ON pr.id = comments.review_id
WHERE pr.id = $1 LIMIT 1
`

type GetPerformanceReviewByIDRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PerformanceID     pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	PerformanceTitle  string             `db:"performance_title" json:"performance_title"`
	PlayerName        string             `db:"player_name" json:"player_name"`
	MatchTitle        string             `db:"match_title" json:"match_title"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) GetPerformanceReviewByID(ctx context.Context, id pgtype.UUID) (GetPerformanceReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewByID, id)
	var i GetPerformanceReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
		&i.PerformanceTitle,
		&i.PlayerName,
		&i.MatchTitle,
		&i.LikesCount,
		&i.CommentCount,
	)
	return i, err
}

const getPerformanceReviewCount = `-- name: GetPerformanceReviewCount :one
SELECT COUNT(*)::bigint AS review_count
FROM performance_reviews
WHERE performance_id = $1
`

func (q *Queries) GetPerformanceReviewCount(ctx context.Context, performanceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewCount, performanceID)
	var review_count int64
	err := row.Scan(&review_count)
	return review_count, err
}

const getPerformanceReviews = `-- name: GetPerformanceReviews :many
SELECT 
    pr.id, pr.performance_id, pr.user_id, pr.title, pr.content, pr.created_at, pr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count,
    CASE WHEN $4::uuid IS NOT NULL THEN 
        EXISTS(SELECT 1 FROM performance_review_likes WHERE review_id = pr.id AND user_id = $4)
    ELSE false END AS liked_by_me
FROM performance_reviews pr
JOIN users u ON pr.user_id = u.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM performance_review_likes
    GROUP BY review_id
) likes ON pr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM performance_review_comments
    GROUP BY review_id
) comments ON pr.id = comments.review_id
WHERE pr.performance_id = $1
ORDER BY pr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPerformanceReviewsParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	Limit         int32       `db:"limit" json:"limit"`
	Offset        int32       `db:"offset" json:"offset"`
	Column4       pgtype.UUID `db:"column_4" json:"column_4"`
}

type GetPerformanceReviewsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PerformanceID     pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
	LikedByMe         bool               `db:"liked_by_me" json:"liked_by_me"`
}

func (q *Queries) GetPerformanceReviews(ctx context.Context, arg GetPerformanceReviewsParams) ([]GetPerformanceReviewsRow, error) {
	rows, err := q.db.Query(ctx, getPerformanceReviews,
		arg.PerformanceID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPerformanceReviewsRow
	for rows.Next() {
		var i GetPerformanceReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformanceID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.LikesCount,
			&i.CommentCount,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularPerformanceReviews = `-- name: GetPopularPerformanceReviews :many
SELECT 
    pr.id, pr.performance_id, pr.user_id, pr.title, pr.content, pr.created_at, pr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    p.title AS performance_title, pl.name AS player_name,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count
FROM performance_reviews pr
JOIN users u ON pr.user_id = u.id
JOIN performances p ON pr.performance_id = p.id
JOIN players pl ON p.player_id = pl.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM performance_review_likes
    GROUP BY review_id
) likes ON pr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM performance_review_comments
    GROUP BY review_id
) comments ON pr.id = comments.review_id
ORDER BY likes_count DESC, pr.created_at DESC
LIMIT $1 OFFSET $2
`

type GetPopularPerformanceReviewsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetPopularPerformanceReviewsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PerformanceID     pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	PerformanceTitle  string             `db:"performance_title" json:"performance_title"`
	PlayerName        string             `db:"player_name" json:"player_name"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) GetPopularPerformanceReviews(ctx context.Context, arg GetPopularPerformanceReviewsParams) ([]GetPopularPerformanceReviewsRow, error) {
	rows, err := q.db.Query(ctx, getPopularPerformanceReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularPerformanceReviewsRow
	for rows.Next() {
		var i GetPopularPerformanceReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformanceID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.PerformanceTitle,
			&i.PlayerName,
			&i.LikesCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPerformanceReviews = `-- name: GetRecentPerformanceReviews :many
SELECT 
    pr.id, pr.performance_id, pr.user_id, pr.title, pr.content, pr.created_at, pr.updated_at,
    u.username AS author_username, u.display_name AS author_display_name, u.avatar_url AS author_avatar_url,
    p.title AS performance_title, pl.name AS player_name,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count,
    COALESCE(comments.comment_count, 0)::bigint AS comment_count
FROM performance_reviews pr
JOIN users u ON pr.user_id = u.id
JOIN performances p ON pr.performance_id = p.id
JOIN players pl ON p.player_id = pl.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM performance_review_likes
    GROUP BY review_id
) likes ON pr.id = likes.review_id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS comment_count
    FROM performance_review_comments
    GROUP BY review_id
) comments ON pr.id = comments.review_id
ORDER BY pr.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentPerformanceReviewsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentPerformanceReviewsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PerformanceID     pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Title             pgtype.Text        `db:"title" json:"title"`
	Content           string             `db:"content" json:"content"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `db:"author_avatar_url" json:"author_avatar_url"`
	PerformanceTitle  string             `db:"performance_title" json:"performance_title"`
	PlayerName        string             `db:"player_name" json:"player_name"`
	LikesCount        int64              `db:"likes_count" json:"likes_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) GetRecentPerformanceReviews(ctx context.Context, arg GetRecentPerformanceReviewsParams) ([]GetRecentPerformanceReviewsRow, error) {
	rows, err := q.db.Query(ctx, getRecentPerformanceReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPerformanceReviewsRow
	for rows.Next() {
		var i GetRecentPerformanceReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformanceID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.PerformanceTitle,
			&i.PlayerName,
			&i.LikesCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPerformanceReviews = `-- name: GetUserPerformanceReviews :many
SELECT 
    pr.id, pr.performance_id, pr.user_id, pr.title, pr.content, pr.created_at, pr.updated_at,
    p.title AS performance_title, pl.name AS player_name,
    COALESCE(likes.likes_count, 0)::bigint AS likes_count
FROM performance_reviews pr
JOIN performances p ON pr.performance_id = p.id
JOIN players pl ON p.player_id = pl.id
LEFT JOIN (
    SELECT review_id, COUNT(*) AS likes_count
    FROM performance_review_likes
    GROUP BY review_id
) likes ON pr.id = likes.review_id
WHERE pr.user_id = $1
ORDER BY pr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserPerformanceReviewsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserPerformanceReviewsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PerformanceID    pgtype.UUID        `db:"performance_id" json:"performance_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Title            pgtype.Text        `db:"title" json:"title"`
	Content          string             `db:"content" json:"content"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
	PlayerName       string             `db:"player_name" json:"player_name"`
	LikesCount       int64              `db:"likes_count" json:"likes_count"`
}

func (q *Queries) GetUserPerformanceReviews(ctx context.Context, arg GetUserPerformanceReviewsParams) ([]GetUserPerformanceReviewsRow, error) {
	rows, err := q.db.Query(ctx, getUserPerformanceReviews, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPerformanceReviewsRow
	for rows.Next() {
		var i GetUserPerformanceReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformanceID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PerformanceTitle,
			&i.PlayerName,
			&i.LikesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserReviewedPerformance = `-- name: HasUserReviewedPerformance :one
SELECT EXISTS (
    SELECT 1 FROM performance_reviews
    WHERE performance_id = $1 AND user_id = $2
)::boolean AS has_reviewed
`

type HasUserReviewedPerformanceParams struct {
	PerformanceID pgtype.UUID `db:"performance_id" json:"performance_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserReviewedPerformance(ctx context.Context, arg HasUserReviewedPerformanceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserReviewedPerformance, arg.PerformanceID, arg.UserID)
	var has_reviewed bool
	err := row.Scan(&has_reviewed)
	return has_reviewed, err
}

const updatePerformanceReview = `-- name: UpdatePerformanceReview :one
UPDATE performance_reviews
SET 
    title = COALESCE($2, title),
    content = COALESCE($3, content),
    updated_at = now()
WHERE id = $1
RETURNING id, performance_id, user_id, title, content, created_at, updated_at
`

type UpdatePerformanceReviewParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Title   pgtype.Text `db:"title" json:"title"`
	Content string      `db:"content" json:"content"`
}

func (q *Queries) UpdatePerformanceReview(ctx context.Context, arg UpdatePerformanceReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, updatePerformanceReview, arg.ID, arg.Title, arg.Content)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.PerformanceID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
