// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerformance = `-- name: CreatePerformance :one
INSERT INTO performances (
    match_id,
    player_id,
    player_team_id,
    title,
    description,
    cover_image_url,
    jersey_number,
    is_starter,
    captain,
    minutes_played,
    average_rating,
    slug,
    tagline
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, match_id, player_id, player_team_id, title, description, cover_image_url, jersey_number, is_starter, captain, minutes_played, average_rating, total_votes, slug, tagline, created_at, updated_at
`

type CreatePerformanceParams struct {
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID    `db:"player_id" json:"player_id"`
	PlayerTeamID  pgtype.UUID    `db:"player_team_id" json:"player_team_id"`
	Title         string         `db:"title" json:"title"`
	Description   pgtype.Text    `db:"description" json:"description"`
	CoverImageUrl pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber  pgtype.Int4    `db:"jersey_number" json:"jersey_number"`
	IsStarter     bool           `db:"is_starter" json:"is_starter"`
	Captain       bool           `db:"captain" json:"captain"`
	MinutesPlayed int32          `db:"minutes_played" json:"minutes_played"`
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	Slug          pgtype.Text    `db:"slug" json:"slug"`
	Tagline       pgtype.Text    `db:"tagline" json:"tagline"`
}

type CreatePerformanceRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	MatchID       pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID  pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	CoverImageUrl pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber  pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	IsStarter     bool               `db:"is_starter" json:"is_starter"`
	Captain       bool               `db:"captain" json:"captain"`
	MinutesPlayed int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	TotalVotes    pgtype.Int4        `db:"total_votes" json:"total_votes"`
	Slug          pgtype.Text        `db:"slug" json:"slug"`
	Tagline       pgtype.Text        `db:"tagline" json:"tagline"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePerformance(ctx context.Context, arg CreatePerformanceParams) (CreatePerformanceRow, error) {
	row := q.db.QueryRow(ctx, createPerformance,
		arg.MatchID,
		arg.PlayerID,
		arg.PlayerTeamID,
		arg.Title,
		arg.Description,
		arg.CoverImageUrl,
		arg.JerseyNumber,
		arg.IsStarter,
		arg.Captain,
		arg.MinutesPlayed,
		arg.AverageRating,
		arg.Slug,
		arg.Tagline,
	)
	var i CreatePerformanceRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerTeamID,
		&i.Title,
		&i.Description,
		&i.CoverImageUrl,
		&i.JerseyNumber,
		&i.IsStarter,
		&i.Captain,
		&i.MinutesPlayed,
		&i.AverageRating,
		&i.TotalVotes,
		&i.Slug,
		&i.Tagline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePerformance = `-- name: DeletePerformance :exec
DELETE FROM performances
WHERE id = $1
`

func (q *Queries) DeletePerformance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerformance, id)
	return err
}

const getPerformanceByID = `-- name: GetPerformanceByID :one
SELECT 
    p.id, p.match_id, p.player_id, p.player_team_id, p.title, p.description, p.cover_image_url, p.jersey_number, p.is_starter, p.captain, p.minutes_played, p.average_rating, p.slug, p.tagline, p.created_at, p.updated_at,
    pl.name AS player_name, pl.slug AS player_slug, pl.photo_url AS player_photo_url, pl.known_as AS player_known_as,
    t.name AS team_name, t.short_name AS team_short_name, t.logo_url AS team_logo_url,
    p.total_votes
FROM performances p
JOIN players pl ON p.player_id = pl.id
JOIN player_teams pt ON p.player_team_id = pt.id
JOIN teams t ON pt.team_id = t.id
WHERE p.id = $1 LIMIT 1
`

type GetPerformanceByIDRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	MatchID        pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID       pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID   pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	CoverImageUrl  pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber   pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	IsStarter      bool               `db:"is_starter" json:"is_starter"`
	Captain        bool               `db:"captain" json:"captain"`
	MinutesPlayed  int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating  pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	Slug           pgtype.Text        `db:"slug" json:"slug"`
	Tagline        pgtype.Text        `db:"tagline" json:"tagline"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PlayerName     string             `db:"player_name" json:"player_name"`
	PlayerSlug     string             `db:"player_slug" json:"player_slug"`
	PlayerPhotoUrl pgtype.Text        `db:"player_photo_url" json:"player_photo_url"`
	PlayerKnownAs  pgtype.Text        `db:"player_known_as" json:"player_known_as"`
	TeamName       string             `db:"team_name" json:"team_name"`
	TeamShortName  string             `db:"team_short_name" json:"team_short_name"`
	TeamLogoUrl    pgtype.Text        `db:"team_logo_url" json:"team_logo_url"`
	TotalVotes     pgtype.Int4        `db:"total_votes" json:"total_votes"`
}

func (q *Queries) GetPerformanceByID(ctx context.Context, id pgtype.UUID) (GetPerformanceByIDRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceByID, id)
	var i GetPerformanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerTeamID,
		&i.Title,
		&i.Description,
		&i.CoverImageUrl,
		&i.JerseyNumber,
		&i.IsStarter,
		&i.Captain,
		&i.MinutesPlayed,
		&i.AverageRating,
		&i.Slug,
		&i.Tagline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerName,
		&i.PlayerSlug,
		&i.PlayerPhotoUrl,
		&i.PlayerKnownAs,
		&i.TeamName,
		&i.TeamShortName,
		&i.TeamLogoUrl,
		&i.TotalVotes,
	)
	return i, err
}

const getPerformanceByMatch = `-- name: GetPerformanceByMatch :many
SELECT 
    p.id, p.match_id, p.player_id, p.player_team_id, p.title, p.cover_image_url, p.jersey_number, p.is_starter, p.minutes_played, p.average_rating, p.slug, p.tagline,
    pl.name AS player_name, pl.photo_url AS player_photo_url,
    'N/A' AS position, t.name AS team_name, t.flag_emoji,
    COALESCE((SELECT sv.value FROM performance_stats sv JOIN stat_types stt ON stt.id = sv.stat_type_id WHERE sv.performance_id = p.id AND stt.name = 'goals' LIMIT 1), 0)::int AS goals,
    COALESCE((SELECT sv.value FROM performance_stats sv JOIN stat_types stt ON stt.id = sv.stat_type_id WHERE sv.performance_id = p.id AND stt.name = 'assists' LIMIT 1), 0)::int AS assists,
    0::int AS dribbles,
    0::numeric(5,2) AS passes_accuracy
FROM performances p
JOIN players pl ON p.player_id = pl.id
LEFT JOIN player_teams pt ON p.player_team_id = pt.id
LEFT JOIN teams t ON pt.team_id = t.id
WHERE p.match_id = $1
ORDER BY p.is_starter DESC, p.minutes_played DESC
`

type GetPerformanceByMatchRow struct {
	ID             pgtype.UUID    `db:"id" json:"id"`
	MatchID        pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID       pgtype.UUID    `db:"player_id" json:"player_id"`
	PlayerTeamID   pgtype.UUID    `db:"player_team_id" json:"player_team_id"`
	Title          string         `db:"title" json:"title"`
	CoverImageUrl  pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber   pgtype.Int4    `db:"jersey_number" json:"jersey_number"`
	IsStarter      bool           `db:"is_starter" json:"is_starter"`
	MinutesPlayed  int32          `db:"minutes_played" json:"minutes_played"`
	AverageRating  pgtype.Numeric `db:"average_rating" json:"average_rating"`
	Slug           pgtype.Text    `db:"slug" json:"slug"`
	Tagline        pgtype.Text    `db:"tagline" json:"tagline"`
	PlayerName     string         `db:"player_name" json:"player_name"`
	PlayerPhotoUrl pgtype.Text    `db:"player_photo_url" json:"player_photo_url"`
	Position       string         `db:"position" json:"position"`
	TeamName       pgtype.Text    `db:"team_name" json:"team_name"`
	FlagEmoji      pgtype.Text    `db:"flag_emoji" json:"flag_emoji"`
	Goals          int32          `db:"goals" json:"goals"`
	Assists        int32          `db:"assists" json:"assists"`
	Dribbles       int32          `db:"dribbles" json:"dribbles"`
	PassesAccuracy pgtype.Numeric `db:"passes_accuracy" json:"passes_accuracy"`
}

func (q *Queries) GetPerformanceByMatch(ctx context.Context, matchID pgtype.UUID) ([]GetPerformanceByMatchRow, error) {
	rows, err := q.db.Query(ctx, getPerformanceByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPerformanceByMatchRow
	for rows.Next() {
		var i GetPerformanceByMatchRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.PlayerTeamID,
			&i.Title,
			&i.CoverImageUrl,
			&i.JerseyNumber,
			&i.IsStarter,
			&i.MinutesPlayed,
			&i.AverageRating,
			&i.Slug,
			&i.Tagline,
			&i.PlayerName,
			&i.PlayerPhotoUrl,
			&i.Position,
			&i.TeamName,
			&i.FlagEmoji,
			&i.Goals,
			&i.Assists,
			&i.Dribbles,
			&i.PassesAccuracy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerformanceByPlayer = `-- name: GetPerformanceByPlayer :many
SELECT 
    p.id, p.match_id, p.player_id, p.player_team_id, p.title, p.cover_image_url, p.jersey_number, p.minutes_played, p.average_rating, p.created_at,
    m.title AS match_title, m.slug AS match_slug, m.utc_datetime AS match_utc_datetime
FROM performances p
JOIN matches m ON p.match_id = m.id
WHERE p.player_id = $1
ORDER BY m.utc_datetime DESC
`

type GetPerformanceByPlayerRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	MatchID          pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID         pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID     pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title            string             `db:"title" json:"title"`
	CoverImageUrl    pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber     pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	MinutesPlayed    int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating    pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MatchTitle       string             `db:"match_title" json:"match_title"`
	MatchSlug        string             `db:"match_slug" json:"match_slug"`
	MatchUtcDatetime pgtype.Timestamptz `db:"match_utc_datetime" json:"match_utc_datetime"`
}

func (q *Queries) GetPerformanceByPlayer(ctx context.Context, playerID pgtype.UUID) ([]GetPerformanceByPlayerRow, error) {
	rows, err := q.db.Query(ctx, getPerformanceByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPerformanceByPlayerRow
	for rows.Next() {
		var i GetPerformanceByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.PlayerTeamID,
			&i.Title,
			&i.CoverImageUrl,
			&i.JerseyNumber,
			&i.MinutesPlayed,
			&i.AverageRating,
			&i.CreatedAt,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.MatchUtcDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerformanceByPlayerAndMatch = `-- name: GetPerformanceByPlayerAndMatch :one
SELECT 
    p.id, p.match_id, p.player_id, p.player_team_id, p.title, p.description, p.cover_image_url, p.jersey_number, p.is_starter, p.captain, p.minutes_played, p.average_rating, p.slug, p.tagline, p.created_at, p.updated_at
FROM performances p
WHERE p.player_id = $1 AND p.match_id = $2 LIMIT 1
`

type GetPerformanceByPlayerAndMatchParams struct {
	PlayerID pgtype.UUID `db:"player_id" json:"player_id"`
	MatchID  pgtype.UUID `db:"match_id" json:"match_id"`
}

type GetPerformanceByPlayerAndMatchRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	MatchID       pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID  pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	CoverImageUrl pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber  pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	IsStarter     bool               `db:"is_starter" json:"is_starter"`
	Captain       bool               `db:"captain" json:"captain"`
	MinutesPlayed int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	Slug          pgtype.Text        `db:"slug" json:"slug"`
	Tagline       pgtype.Text        `db:"tagline" json:"tagline"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPerformanceByPlayerAndMatch(ctx context.Context, arg GetPerformanceByPlayerAndMatchParams) (GetPerformanceByPlayerAndMatchRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceByPlayerAndMatch, arg.PlayerID, arg.MatchID)
	var i GetPerformanceByPlayerAndMatchRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerTeamID,
		&i.Title,
		&i.Description,
		&i.CoverImageUrl,
		&i.JerseyNumber,
		&i.IsStarter,
		&i.Captain,
		&i.MinutesPlayed,
		&i.AverageRating,
		&i.Slug,
		&i.Tagline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerformanceBySlug = `-- name: GetPerformanceBySlug :one
SELECT 
    p.id, p.match_id, p.player_id, p.player_team_id, p.title, p.description, p.cover_image_url, p.jersey_number, p.is_starter, p.captain, p.minutes_played, p.average_rating, p.slug, p.tagline, p.created_at, p.updated_at,
    pl.name AS player_name, pl.slug AS player_slug, pl.photo_url AS player_photo_url, pl.known_as AS player_known_as,
    t.name AS team_name, t.short_name AS team_short_name, t.logo_url AS team_logo_url,
    p.total_votes
FROM performances p
JOIN players pl ON p.player_id = pl.id
JOIN player_teams pt ON p.player_team_id = pt.id
JOIN teams t ON pt.team_id = t.id
WHERE p.slug = $1 LIMIT 1
`

type GetPerformanceBySlugRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	MatchID        pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID       pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID   pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	CoverImageUrl  pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber   pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	IsStarter      bool               `db:"is_starter" json:"is_starter"`
	Captain        bool               `db:"captain" json:"captain"`
	MinutesPlayed  int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating  pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	Slug           pgtype.Text        `db:"slug" json:"slug"`
	Tagline        pgtype.Text        `db:"tagline" json:"tagline"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PlayerName     string             `db:"player_name" json:"player_name"`
	PlayerSlug     string             `db:"player_slug" json:"player_slug"`
	PlayerPhotoUrl pgtype.Text        `db:"player_photo_url" json:"player_photo_url"`
	PlayerKnownAs  pgtype.Text        `db:"player_known_as" json:"player_known_as"`
	TeamName       string             `db:"team_name" json:"team_name"`
	TeamShortName  string             `db:"team_short_name" json:"team_short_name"`
	TeamLogoUrl    pgtype.Text        `db:"team_logo_url" json:"team_logo_url"`
	TotalVotes     pgtype.Int4        `db:"total_votes" json:"total_votes"`
}

func (q *Queries) GetPerformanceBySlug(ctx context.Context, slug pgtype.Text) (GetPerformanceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceBySlug, slug)
	var i GetPerformanceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerTeamID,
		&i.Title,
		&i.Description,
		&i.CoverImageUrl,
		&i.JerseyNumber,
		&i.IsStarter,
		&i.Captain,
		&i.MinutesPlayed,
		&i.AverageRating,
		&i.Slug,
		&i.Tagline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerName,
		&i.PlayerSlug,
		&i.PlayerPhotoUrl,
		&i.PlayerKnownAs,
		&i.TeamName,
		&i.TeamShortName,
		&i.TeamLogoUrl,
		&i.TotalVotes,
	)
	return i, err
}

const getRecentPerformances = `-- name: GetRecentPerformances :many
SELECT 
    p.id, p.match_id, p.player_id, p.title, p.cover_image_url, p.average_rating, p.created_at,
    pl.name AS player_name, m.title AS match_title
FROM performances p
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentPerformancesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentPerformancesRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	MatchID       pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID        `db:"player_id" json:"player_id"`
	Title         string             `db:"title" json:"title"`
	CoverImageUrl pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	AverageRating pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PlayerName    string             `db:"player_name" json:"player_name"`
	MatchTitle    string             `db:"match_title" json:"match_title"`
}

func (q *Queries) GetRecentPerformances(ctx context.Context, arg GetRecentPerformancesParams) ([]GetRecentPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getRecentPerformances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPerformancesRow
	for rows.Next() {
		var i GetRecentPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.Title,
			&i.CoverImageUrl,
			&i.AverageRating,
			&i.CreatedAt,
			&i.PlayerName,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelatedPerformances = `-- name: GetRelatedPerformances :many
SELECT 
    p.id, p.match_id, p.player_id, p.title, p.cover_image_url, p.average_rating,
    pl.name AS player_name
FROM performances p
JOIN players pl ON p.player_id = pl.id
WHERE p.match_id = (SELECT sub_p.match_id FROM performances sub_p WHERE sub_p.id = $1) AND p.id <> $1
ORDER BY p.average_rating DESC
LIMIT $2
`

type GetRelatedPerformancesParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Limit int32       `db:"limit" json:"limit"`
}

type GetRelatedPerformancesRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID    `db:"player_id" json:"player_id"`
	Title         string         `db:"title" json:"title"`
	CoverImageUrl pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	PlayerName    string         `db:"player_name" json:"player_name"`
}

func (q *Queries) GetRelatedPerformances(ctx context.Context, arg GetRelatedPerformancesParams) ([]GetRelatedPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getRelatedPerformances, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelatedPerformancesRow
	for rows.Next() {
		var i GetRelatedPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.Title,
			&i.CoverImageUrl,
			&i.AverageRating,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRatedPerformances = `-- name: GetTopRatedPerformances :many
SELECT 
    p.id, p.match_id, p.player_id, p.title, p.cover_image_url, p.average_rating, p.total_votes,
    pl.name AS player_name, m.title AS match_title
FROM performances p
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
ORDER BY p.average_rating DESC, m.utc_datetime DESC
LIMIT $1 OFFSET $2
`

type GetTopRatedPerformancesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetTopRatedPerformancesRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID    `db:"player_id" json:"player_id"`
	Title         string         `db:"title" json:"title"`
	CoverImageUrl pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	TotalVotes    pgtype.Int4    `db:"total_votes" json:"total_votes"`
	PlayerName    string         `db:"player_name" json:"player_name"`
	MatchTitle    string         `db:"match_title" json:"match_title"`
}

func (q *Queries) GetTopRatedPerformances(ctx context.Context, arg GetTopRatedPerformancesParams) ([]GetTopRatedPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getTopRatedPerformances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopRatedPerformancesRow
	for rows.Next() {
		var i GetTopRatedPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.Title,
			&i.CoverImageUrl,
			&i.AverageRating,
			&i.TotalVotes,
			&i.PlayerName,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformances = `-- name: ListPerformances :many
SELECT 
    p.id, p.match_id, p.player_id, p.player_team_id, p.title, p.cover_image_url, p.average_rating, p.created_at, p.updated_at, p.minutes_played, p.slug, p.tagline,
    pl.name AS player_name, m.title AS match_title, m.round AS match_round,
    'N/A' AS position, t.name AS team_name, t.flag_emoji,
    COALESCE((SELECT sv.value FROM performance_stats sv JOIN stat_types stt ON stt.id = sv.stat_type_id WHERE sv.performance_id = p.id AND stt.name = 'goals' LIMIT 1), 0)::int AS goals,
    COALESCE((SELECT sv.value FROM performance_stats sv JOIN stat_types stt ON stt.id = sv.stat_type_id WHERE sv.performance_id = p.id AND stt.name = 'assists' LIMIT 1), 0)::int AS assists,
    0::int AS dribbles,
    0::numeric(5,2) AS passes_accuracy,
    p.total_votes
FROM performances p
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
LEFT JOIN player_teams pt ON p.player_team_id = pt.id
LEFT JOIN teams t ON pt.team_id = t.id
ORDER BY m.utc_datetime DESC
LIMIT $1 OFFSET $2
`

type ListPerformancesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListPerformancesRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	MatchID        pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID       pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID   pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title          string             `db:"title" json:"title"`
	CoverImageUrl  pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	AverageRating  pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MinutesPlayed  int32              `db:"minutes_played" json:"minutes_played"`
	Slug           pgtype.Text        `db:"slug" json:"slug"`
	Tagline        pgtype.Text        `db:"tagline" json:"tagline"`
	PlayerName     string             `db:"player_name" json:"player_name"`
	MatchTitle     string             `db:"match_title" json:"match_title"`
	MatchRound     pgtype.Text        `db:"match_round" json:"match_round"`
	Position       string             `db:"position" json:"position"`
	TeamName       pgtype.Text        `db:"team_name" json:"team_name"`
	FlagEmoji      pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
	Goals          int32              `db:"goals" json:"goals"`
	Assists        int32              `db:"assists" json:"assists"`
	Dribbles       int32              `db:"dribbles" json:"dribbles"`
	PassesAccuracy pgtype.Numeric     `db:"passes_accuracy" json:"passes_accuracy"`
	TotalVotes     pgtype.Int4        `db:"total_votes" json:"total_votes"`
}

func (q *Queries) ListPerformances(ctx context.Context, arg ListPerformancesParams) ([]ListPerformancesRow, error) {
	rows, err := q.db.Query(ctx, listPerformances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerformancesRow
	for rows.Next() {
		var i ListPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.PlayerTeamID,
			&i.Title,
			&i.CoverImageUrl,
			&i.AverageRating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinutesPlayed,
			&i.Slug,
			&i.Tagline,
			&i.PlayerName,
			&i.MatchTitle,
			&i.MatchRound,
			&i.Position,
			&i.TeamName,
			&i.FlagEmoji,
			&i.Goals,
			&i.Assists,
			&i.Dribbles,
			&i.PassesAccuracy,
			&i.TotalVotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPerformances = `-- name: SearchPerformances :many
SELECT 
    p.id, p.match_id, p.player_id, p.title, p.cover_image_url, p.average_rating,
    pl.name AS player_name, m.title AS match_title
FROM performances p
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
WHERE p.title ILIKE $1 OR pl.name ILIKE $1 OR m.title ILIKE $1
ORDER BY m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type SearchPerformancesParams struct {
	Title  string `db:"title" json:"title"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type SearchPerformancesRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID    `db:"player_id" json:"player_id"`
	Title         string         `db:"title" json:"title"`
	CoverImageUrl pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	PlayerName    string         `db:"player_name" json:"player_name"`
	MatchTitle    string         `db:"match_title" json:"match_title"`
}

func (q *Queries) SearchPerformances(ctx context.Context, arg SearchPerformancesParams) ([]SearchPerformancesRow, error) {
	rows, err := q.db.Query(ctx, searchPerformances, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPerformancesRow
	for rows.Next() {
		var i SearchPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.Title,
			&i.CoverImageUrl,
			&i.AverageRating,
			&i.PlayerName,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerformance = `-- name: UpdatePerformance :one
UPDATE performances
SET
    match_id = COALESCE($2, match_id),
    player_id = COALESCE($3, player_id),
    player_team_id = COALESCE($4, player_team_id),
    title = COALESCE($5, title),
    description = COALESCE($6, description),
    cover_image_url = COALESCE($7, cover_image_url),
    jersey_number = COALESCE($8, jersey_number),
    is_starter = COALESCE($9, is_starter),
    captain = COALESCE($10, captain),
    minutes_played = COALESCE($11, minutes_played),
    average_rating = COALESCE($12, average_rating),
    slug = COALESCE($13, slug),
    tagline = COALESCE($14, tagline),
    updated_at = now()
WHERE id = $1
RETURNING id, match_id, player_id, player_team_id, title, description, cover_image_url, jersey_number, is_starter, captain, minutes_played, average_rating, slug, tagline, created_at, updated_at
`

type UpdatePerformanceParams struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MatchID       pgtype.UUID    `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID    `db:"player_id" json:"player_id"`
	PlayerTeamID  pgtype.UUID    `db:"player_team_id" json:"player_team_id"`
	Title         string         `db:"title" json:"title"`
	Description   pgtype.Text    `db:"description" json:"description"`
	CoverImageUrl pgtype.Text    `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber  pgtype.Int4    `db:"jersey_number" json:"jersey_number"`
	IsStarter     bool           `db:"is_starter" json:"is_starter"`
	Captain       bool           `db:"captain" json:"captain"`
	MinutesPlayed int32          `db:"minutes_played" json:"minutes_played"`
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	Slug          pgtype.Text    `db:"slug" json:"slug"`
	Tagline       pgtype.Text    `db:"tagline" json:"tagline"`
}

type UpdatePerformanceRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	MatchID       pgtype.UUID        `db:"match_id" json:"match_id"`
	PlayerID      pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerTeamID  pgtype.UUID        `db:"player_team_id" json:"player_team_id"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	CoverImageUrl pgtype.Text        `db:"cover_image_url" json:"cover_image_url"`
	JerseyNumber  pgtype.Int4        `db:"jersey_number" json:"jersey_number"`
	IsStarter     bool               `db:"is_starter" json:"is_starter"`
	Captain       bool               `db:"captain" json:"captain"`
	MinutesPlayed int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	Slug          pgtype.Text        `db:"slug" json:"slug"`
	Tagline       pgtype.Text        `db:"tagline" json:"tagline"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdatePerformance(ctx context.Context, arg UpdatePerformanceParams) (UpdatePerformanceRow, error) {
	row := q.db.QueryRow(ctx, updatePerformance,
		arg.ID,
		arg.MatchID,
		arg.PlayerID,
		arg.PlayerTeamID,
		arg.Title,
		arg.Description,
		arg.CoverImageUrl,
		arg.JerseyNumber,
		arg.IsStarter,
		arg.Captain,
		arg.MinutesPlayed,
		arg.AverageRating,
		arg.Slug,
		arg.Tagline,
	)
	var i UpdatePerformanceRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerTeamID,
		&i.Title,
		&i.Description,
		&i.CoverImageUrl,
		&i.JerseyNumber,
		&i.IsStarter,
		&i.Captain,
		&i.MinutesPlayed,
		&i.AverageRating,
		&i.Slug,
		&i.Tagline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
