// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentTeam = `-- name: GetCurrentTeam :many
SELECT 
    pt.id AS player_team_id, pt.jersey_number, pt.start_date, pt.is_active,
    t.id AS team_id, t.name AS team_name, t.short_name AS team_short_name, t.logo_url AS team_logo_url, t.type AS team_type
FROM player_teams pt
JOIN teams t ON pt.team_id = t.id
WHERE pt.player_id = $1 AND pt.is_active = TRUE
`

type GetCurrentTeamRow struct {
	PlayerTeamID  pgtype.UUID `db:"player_team_id" json:"player_team_id"`
	JerseyNumber  pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate     pgtype.Date `db:"start_date" json:"start_date"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	TeamID        pgtype.UUID `db:"team_id" json:"team_id"`
	TeamName      string      `db:"team_name" json:"team_name"`
	TeamShortName string      `db:"team_short_name" json:"team_short_name"`
	TeamLogoUrl   pgtype.Text `db:"team_logo_url" json:"team_logo_url"`
	TeamType      TeamType    `db:"team_type" json:"team_type"`
}

func (q *Queries) GetCurrentTeam(ctx context.Context, playerID pgtype.UUID) ([]GetCurrentTeamRow, error) {
	rows, err := q.db.Query(ctx, getCurrentTeam, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentTeamRow
	for rows.Next() {
		var i GetCurrentTeamRow
		if err := rows.Scan(
			&i.PlayerTeamID,
			&i.JerseyNumber,
			&i.StartDate,
			&i.IsActive,
			&i.TeamID,
			&i.TeamName,
			&i.TeamShortName,
			&i.TeamLogoUrl,
			&i.TeamType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerCareer = `-- name: GetPlayerCareer :many
SELECT 
    pt.id AS player_team_id, pt.jersey_number, pt.start_date, pt.end_date, pt.is_active,
    t.id AS team_id, t.name AS team_name, t.short_name AS team_short_name, t.logo_url AS team_logo_url, t.type AS team_type
FROM player_teams pt
JOIN teams t ON pt.team_id = t.id
WHERE pt.player_id = $1
ORDER BY pt.start_date DESC
`

type GetPlayerCareerRow struct {
	PlayerTeamID  pgtype.UUID `db:"player_team_id" json:"player_team_id"`
	JerseyNumber  pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate     pgtype.Date `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date `db:"end_date" json:"end_date"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	TeamID        pgtype.UUID `db:"team_id" json:"team_id"`
	TeamName      string      `db:"team_name" json:"team_name"`
	TeamShortName string      `db:"team_short_name" json:"team_short_name"`
	TeamLogoUrl   pgtype.Text `db:"team_logo_url" json:"team_logo_url"`
	TeamType      TeamType    `db:"team_type" json:"team_type"`
}

func (q *Queries) GetPlayerCareer(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerCareerRow, error) {
	rows, err := q.db.Query(ctx, getPlayerCareer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerCareerRow
	for rows.Next() {
		var i GetPlayerCareerRow
		if err := rows.Scan(
			&i.PlayerTeamID,
			&i.JerseyNumber,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.TeamID,
			&i.TeamName,
			&i.TeamShortName,
			&i.TeamLogoUrl,
			&i.TeamType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTeams = `-- name: GetPlayerTeams :many
SELECT 
    pt.id, pt.player_id, pt.team_id, pt.jersey_number, pt.start_date, pt.end_date, pt.is_active,
    t.name AS team_name, t.logo_url AS team_logo_url
FROM player_teams pt
JOIN teams t ON pt.team_id = t.id
WHERE pt.player_id = $1
ORDER BY pt.start_date DESC
`

type GetPlayerTeamsRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PlayerID     pgtype.UUID `db:"player_id" json:"player_id"`
	TeamID       pgtype.UUID `db:"team_id" json:"team_id"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate    pgtype.Date `db:"start_date" json:"start_date"`
	EndDate      pgtype.Date `db:"end_date" json:"end_date"`
	IsActive     bool        `db:"is_active" json:"is_active"`
	TeamName     string      `db:"team_name" json:"team_name"`
	TeamLogoUrl  pgtype.Text `db:"team_logo_url" json:"team_logo_url"`
}

func (q *Queries) GetPlayerTeams(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerTeamsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerTeams, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerTeamsRow
	for rows.Next() {
		var i GetPlayerTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.TeamID,
			&i.JerseyNumber,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.TeamName,
			&i.TeamLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamPlayers = `-- name: GetTeamPlayers :many
SELECT DISTINCT
    p.id, p.name, p.slug, p.known_as, p.photo_url, p.shirt_name,
    pt.jersey_number, pt.start_date, pt.end_date, pt.is_active
FROM player_teams pt
JOIN players p ON pt.player_id = p.id
WHERE pt.team_id = $1
ORDER BY pt.is_active DESC, p.name
`

type GetTeamPlayersRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	KnownAs      pgtype.Text `db:"known_as" json:"known_as"`
	PhotoUrl     pgtype.Text `db:"photo_url" json:"photo_url"`
	ShirtName    pgtype.Text `db:"shirt_name" json:"shirt_name"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate    pgtype.Date `db:"start_date" json:"start_date"`
	EndDate      pgtype.Date `db:"end_date" json:"end_date"`
	IsActive     bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) GetTeamPlayers(ctx context.Context, teamID pgtype.UUID) ([]GetTeamPlayersRow, error) {
	rows, err := q.db.Query(ctx, getTeamPlayers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamPlayersRow
	for rows.Next() {
		var i GetTeamPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.KnownAs,
			&i.PhotoUrl,
			&i.ShirtName,
			&i.JerseyNumber,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinPlayerToTeam = `-- name: JoinPlayerToTeam :one
INSERT INTO player_teams (
    player_id,
    team_id,
    jersey_number,
    start_date,
    end_date,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, player_id, team_id, jersey_number, start_date, end_date, is_active
`

type JoinPlayerToTeamParams struct {
	PlayerID     pgtype.UUID `db:"player_id" json:"player_id"`
	TeamID       pgtype.UUID `db:"team_id" json:"team_id"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate    pgtype.Date `db:"start_date" json:"start_date"`
	EndDate      pgtype.Date `db:"end_date" json:"end_date"`
	IsActive     bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) JoinPlayerToTeam(ctx context.Context, arg JoinPlayerToTeamParams) (PlayerTeam, error) {
	row := q.db.QueryRow(ctx, joinPlayerToTeam,
		arg.PlayerID,
		arg.TeamID,
		arg.JerseyNumber,
		arg.StartDate,
		arg.EndDate,
		arg.IsActive,
	)
	var i PlayerTeam
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}

const leavePlayerTeam = `-- name: LeavePlayerTeam :one
UPDATE player_teams
SET 
    end_date = $2,
    is_active = FALSE
WHERE id = $1
RETURNING id, player_id, team_id, jersey_number, start_date, end_date, is_active
`

type LeavePlayerTeamParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	EndDate pgtype.Date `db:"end_date" json:"end_date"`
}

func (q *Queries) LeavePlayerTeam(ctx context.Context, arg LeavePlayerTeamParams) (PlayerTeam, error) {
	row := q.db.QueryRow(ctx, leavePlayerTeam, arg.ID, arg.EndDate)
	var i PlayerTeam
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}

const updateJerseyNumber = `-- name: UpdateJerseyNumber :one
UPDATE player_teams
SET jersey_number = $2
WHERE id = $1
RETURNING id, player_id, team_id, jersey_number, start_date, end_date, is_active
`

type UpdateJerseyNumberParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
}

func (q *Queries) UpdateJerseyNumber(ctx context.Context, arg UpdateJerseyNumberParams) (PlayerTeam, error) {
	row := q.db.QueryRow(ctx, updateJerseyNumber, arg.ID, arg.JerseyNumber)
	var i PlayerTeam
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}

const updatePlayerTeam = `-- name: UpdatePlayerTeam :one
UPDATE player_teams
SET 
    jersey_number = COALESCE($2, jersey_number),
    start_date = COALESCE($3, start_date),
    end_date = COALESCE($4, end_date),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, player_id, team_id, jersey_number, start_date, end_date, is_active
`

type UpdatePlayerTeamParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate    pgtype.Date `db:"start_date" json:"start_date"`
	EndDate      pgtype.Date `db:"end_date" json:"end_date"`
	IsActive     bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdatePlayerTeam(ctx context.Context, arg UpdatePlayerTeamParams) (PlayerTeam, error) {
	row := q.db.QueryRow(ctx, updatePlayerTeam,
		arg.ID,
		arg.JerseyNumber,
		arg.StartDate,
		arg.EndDate,
		arg.IsActive,
	)
	var i PlayerTeam
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}

const updateSquadNumber = `-- name: UpdateSquadNumber :one
UPDATE player_teams
SET jersey_number = $2
WHERE id = $1
RETURNING id, player_id, team_id, jersey_number, start_date, end_date, is_active
`

type UpdateSquadNumberParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
}

func (q *Queries) UpdateSquadNumber(ctx context.Context, arg UpdateSquadNumberParams) (PlayerTeam, error) {
	row := q.db.QueryRow(ctx, updateSquadNumber, arg.ID, arg.JerseyNumber)
	var i PlayerTeam
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}
