// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (
    name,
    slug,
    full_name,
    known_as,
    date_of_birth,
    place_of_birth,
    country_id,
    photo_url,
    height_cm,
    weight_kg,
    shirt_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, name, slug, full_name, known_as, date_of_birth, place_of_birth, country_id, photo_url, height_cm, weight_kg, shirt_name, created_at, updated_at
`

type CreatePlayerParams struct {
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	FullName     pgtype.Text `db:"full_name" json:"full_name"`
	KnownAs      pgtype.Text `db:"known_as" json:"known_as"`
	DateOfBirth  pgtype.Date `db:"date_of_birth" json:"date_of_birth"`
	PlaceOfBirth pgtype.Text `db:"place_of_birth" json:"place_of_birth"`
	CountryID    pgtype.UUID `db:"country_id" json:"country_id"`
	PhotoUrl     pgtype.Text `db:"photo_url" json:"photo_url"`
	HeightCm     pgtype.Int4 `db:"height_cm" json:"height_cm"`
	WeightKg     pgtype.Int4 `db:"weight_kg" json:"weight_kg"`
	ShirtName    pgtype.Text `db:"shirt_name" json:"shirt_name"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.Name,
		arg.Slug,
		arg.FullName,
		arg.KnownAs,
		arg.DateOfBirth,
		arg.PlaceOfBirth,
		arg.CountryID,
		arg.PhotoUrl,
		arg.HeightCm,
		arg.WeightKg,
		arg.ShirtName,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FullName,
		&i.KnownAs,
		&i.DateOfBirth,
		&i.PlaceOfBirth,
		&i.CountryID,
		&i.PhotoUrl,
		&i.HeightCm,
		&i.WeightKg,
		&i.ShirtName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getPlayerAggregatedStats = `-- name: GetPlayerAggregatedStats :many
SELECT 
    st.id AS stat_type_id,
    st.name AS stat_name,
    st.short_name AS stat_short_name,
    st.unit AS stat_unit,
    st.category AS stat_category,
    SUM(ps.value)::double precision AS total_value,
    AVG(ps.value)::double precision AS average_value
FROM performance_stats ps
JOIN stat_types st ON ps.stat_type_id = st.id
JOIN performances p ON ps.performance_id = p.id
WHERE p.player_id = $1
GROUP BY st.id, st.name, st.short_name, st.unit, st.category, st.display_order
ORDER BY st.category, st.display_order
`

type GetPlayerAggregatedStatsRow struct {
	StatTypeID    pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
	StatName      string      `db:"stat_name" json:"stat_name"`
	StatShortName string      `db:"stat_short_name" json:"stat_short_name"`
	StatUnit      pgtype.Text `db:"stat_unit" json:"stat_unit"`
	StatCategory  string      `db:"stat_category" json:"stat_category"`
	TotalValue    float64     `db:"total_value" json:"total_value"`
	AverageValue  float64     `db:"average_value" json:"average_value"`
}

func (q *Queries) GetPlayerAggregatedStats(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerAggregatedStatsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerAggregatedStats, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerAggregatedStatsRow
	for rows.Next() {
		var i GetPlayerAggregatedStatsRow
		if err := rows.Scan(
			&i.StatTypeID,
			&i.StatName,
			&i.StatShortName,
			&i.StatUnit,
			&i.StatCategory,
			&i.TotalValue,
			&i.AverageValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerAverageRating = `-- name: GetPlayerAverageRating :one
SELECT 
    COALESCE(AVG(pr.rating), 0.0)::numeric(2,1) AS average_rating,
    COUNT(pr.id)::bigint AS total_votes
FROM performances p
JOIN performance_ratings pr ON p.id = pr.performance_id
WHERE p.player_id = $1
`

type GetPlayerAverageRatingRow struct {
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	TotalVotes    int64          `db:"total_votes" json:"total_votes"`
}

func (q *Queries) GetPlayerAverageRating(ctx context.Context, playerID pgtype.UUID) (GetPlayerAverageRatingRow, error) {
	row := q.db.QueryRow(ctx, getPlayerAverageRating, playerID)
	var i GetPlayerAverageRatingRow
	err := row.Scan(&i.AverageRating, &i.TotalVotes)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT 
    p.id, p.name, p.slug, p.full_name, p.known_as, p.date_of_birth, p.place_of_birth, p.country_id, p.photo_url, p.height_cm, p.weight_kg, p.shirt_name, p.created_at, p.updated_at,
    c.name AS country_name, c.iso2 AS country_iso2, c.iso3 AS country_iso3
FROM players p
LEFT JOIN countries c ON p.country_id = c.id
WHERE p.id = $1 LIMIT 1
`

type GetPlayerByIDRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Slug         string             `db:"slug" json:"slug"`
	FullName     pgtype.Text        `db:"full_name" json:"full_name"`
	KnownAs      pgtype.Text        `db:"known_as" json:"known_as"`
	DateOfBirth  pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	PlaceOfBirth pgtype.Text        `db:"place_of_birth" json:"place_of_birth"`
	CountryID    pgtype.UUID        `db:"country_id" json:"country_id"`
	PhotoUrl     pgtype.Text        `db:"photo_url" json:"photo_url"`
	HeightCm     pgtype.Int4        `db:"height_cm" json:"height_cm"`
	WeightKg     pgtype.Int4        `db:"weight_kg" json:"weight_kg"`
	ShirtName    pgtype.Text        `db:"shirt_name" json:"shirt_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CountryName  pgtype.Text        `db:"country_name" json:"country_name"`
	CountryIso2  pgtype.Text        `db:"country_iso2" json:"country_iso2"`
	CountryIso3  pgtype.Text        `db:"country_iso3" json:"country_iso3"`
}

func (q *Queries) GetPlayerByID(ctx context.Context, id pgtype.UUID) (GetPlayerByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i GetPlayerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FullName,
		&i.KnownAs,
		&i.DateOfBirth,
		&i.PlaceOfBirth,
		&i.CountryID,
		&i.PhotoUrl,
		&i.HeightCm,
		&i.WeightKg,
		&i.ShirtName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryName,
		&i.CountryIso2,
		&i.CountryIso3,
	)
	return i, err
}

const getPlayerBySlug = `-- name: GetPlayerBySlug :one
SELECT 
    p.id, p.name, p.slug, p.full_name, p.known_as, p.date_of_birth, p.place_of_birth, p.country_id, p.photo_url, p.height_cm, p.weight_kg, p.shirt_name, p.created_at, p.updated_at,
    c.name AS country_name, c.iso2 AS country_iso2, c.iso3 AS country_iso3
FROM players p
LEFT JOIN countries c ON p.country_id = c.id
WHERE p.slug = $1 LIMIT 1
`

type GetPlayerBySlugRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Slug         string             `db:"slug" json:"slug"`
	FullName     pgtype.Text        `db:"full_name" json:"full_name"`
	KnownAs      pgtype.Text        `db:"known_as" json:"known_as"`
	DateOfBirth  pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	PlaceOfBirth pgtype.Text        `db:"place_of_birth" json:"place_of_birth"`
	CountryID    pgtype.UUID        `db:"country_id" json:"country_id"`
	PhotoUrl     pgtype.Text        `db:"photo_url" json:"photo_url"`
	HeightCm     pgtype.Int4        `db:"height_cm" json:"height_cm"`
	WeightKg     pgtype.Int4        `db:"weight_kg" json:"weight_kg"`
	ShirtName    pgtype.Text        `db:"shirt_name" json:"shirt_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CountryName  pgtype.Text        `db:"country_name" json:"country_name"`
	CountryIso2  pgtype.Text        `db:"country_iso2" json:"country_iso2"`
	CountryIso3  pgtype.Text        `db:"country_iso3" json:"country_iso3"`
}

func (q *Queries) GetPlayerBySlug(ctx context.Context, slug string) (GetPlayerBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPlayerBySlug, slug)
	var i GetPlayerBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FullName,
		&i.KnownAs,
		&i.DateOfBirth,
		&i.PlaceOfBirth,
		&i.CountryID,
		&i.PhotoUrl,
		&i.HeightCm,
		&i.WeightKg,
		&i.ShirtName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryName,
		&i.CountryIso2,
		&i.CountryIso3,
	)
	return i, err
}

const getPlayerMatches = `-- name: GetPlayerMatches :many
SELECT 
    m.id, m.title, m.slug, m.utc_datetime, m.home_score, m.away_score,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url
FROM performances p
JOIN matches m ON p.match_id = m.id
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
WHERE p.player_id = $1
ORDER BY m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type GetPlayerMatchesParams struct {
	PlayerID pgtype.UUID `db:"player_id" json:"player_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetPlayerMatchesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Title           string             `db:"title" json:"title"`
	Slug            string             `db:"slug" json:"slug"`
	UtcDatetime     pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	HomeScore       int32              `db:"home_score" json:"home_score"`
	AwayScore       int32              `db:"away_score" json:"away_score"`
	HomeTeamName    string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	AwayTeamName    string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
}

func (q *Queries) GetPlayerMatches(ctx context.Context, arg GetPlayerMatchesParams) ([]GetPlayerMatchesRow, error) {
	rows, err := q.db.Query(ctx, getPlayerMatches, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerMatchesRow
	for rows.Next() {
		var i GetPlayerMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.UtcDatetime,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerPerformances = `-- name: GetPlayerPerformances :many
SELECT 
    p.id AS performance_id, p.title AS performance_title, p.cover_image_url AS performance_cover_image, p.minutes_played, p.average_rating, p.created_at,
    m.id AS match_id, m.title AS match_title, m.slug AS match_slug, m.utc_datetime AS match_utc_datetime, m.home_score, m.away_score,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url
FROM performances p
JOIN matches m ON p.match_id = m.id
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
WHERE p.player_id = $1
ORDER BY m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type GetPlayerPerformancesParams struct {
	PlayerID pgtype.UUID `db:"player_id" json:"player_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetPlayerPerformancesRow struct {
	PerformanceID         pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle      string             `db:"performance_title" json:"performance_title"`
	PerformanceCoverImage pgtype.Text        `db:"performance_cover_image" json:"performance_cover_image"`
	MinutesPlayed         int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating         pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MatchID               pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle            string             `db:"match_title" json:"match_title"`
	MatchSlug             string             `db:"match_slug" json:"match_slug"`
	MatchUtcDatetime      pgtype.Timestamptz `db:"match_utc_datetime" json:"match_utc_datetime"`
	HomeScore             int32              `db:"home_score" json:"home_score"`
	AwayScore             int32              `db:"away_score" json:"away_score"`
	HomeTeamName          string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl       pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	AwayTeamName          string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl       pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
}

func (q *Queries) GetPlayerPerformances(ctx context.Context, arg GetPlayerPerformancesParams) ([]GetPlayerPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getPlayerPerformances, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerPerformancesRow
	for rows.Next() {
		var i GetPlayerPerformancesRow
		if err := rows.Scan(
			&i.PerformanceID,
			&i.PerformanceTitle,
			&i.PerformanceCoverImage,
			&i.MinutesPlayed,
			&i.AverageRating,
			&i.CreatedAt,
			&i.MatchID,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.MatchUtcDatetime,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRatings = `-- name: GetPlayerRatings :many
SELECT 
    pr.id AS rating_id, pr.rating, pr.created_at AS rated_at,
    u.id AS user_id, u.username, u.display_name, u.avatar_url,
    p.id AS performance_id, p.title AS performance_title,
    m.id AS match_id, m.title AS match_title
FROM performance_ratings pr
JOIN performances p ON pr.performance_id = p.id
JOIN matches m ON p.match_id = m.id
JOIN users u ON r.user_id = u.id
WHERE p.player_id = $1
ORDER BY pr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPlayerRatingsParams struct {
	PlayerID pgtype.UUID `db:"player_id" json:"player_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetPlayerRatingsRow struct {
	RatingID         pgtype.UUID        `db:"rating_id" json:"rating_id"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	RatedAt          pgtype.Timestamptz `db:"rated_at" json:"rated_at"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Username         string             `db:"username" json:"username"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PerformanceID    pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
	MatchID          pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle       string             `db:"match_title" json:"match_title"`
}

func (q *Queries) GetPlayerRatings(ctx context.Context, arg GetPlayerRatingsParams) ([]GetPlayerRatingsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerRatings, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerRatingsRow
	for rows.Next() {
		var i GetPlayerRatingsRow
		if err := rows.Scan(
			&i.RatingID,
			&i.Rating,
			&i.RatedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.PerformanceID,
			&i.PerformanceTitle,
			&i.MatchID,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerReviewCount = `-- name: GetPlayerReviewCount :one
SELECT COUNT(r.id)::bigint AS review_count
FROM performance_reviews r
JOIN performances p ON r.performance_id = p.id
WHERE p.player_id = $1
`

func (q *Queries) GetPlayerReviewCount(ctx context.Context, playerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPlayerReviewCount, playerID)
	var review_count int64
	err := row.Scan(&review_count)
	return review_count, err
}

const getPlayerReviews = `-- name: GetPlayerReviews :many
SELECT 
    r.id AS review_id, r.title AS review_title, r.content AS review_content, r.created_at AS review_created_at,
    u.id AS user_id, u.username, u.display_name, u.avatar_url,
    p.id AS performance_id, p.title AS performance_title,
    m.id AS match_id, m.title AS match_title
FROM performance_reviews r
JOIN performances p ON r.performance_id = p.id
JOIN matches m ON p.match_id = m.id
JOIN users u ON r.user_id = u.id
WHERE p.player_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPlayerReviewsParams struct {
	PlayerID pgtype.UUID `db:"player_id" json:"player_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetPlayerReviewsRow struct {
	ReviewID         pgtype.UUID        `db:"review_id" json:"review_id"`
	ReviewTitle      pgtype.Text        `db:"review_title" json:"review_title"`
	ReviewContent    string             `db:"review_content" json:"review_content"`
	ReviewCreatedAt  pgtype.Timestamptz `db:"review_created_at" json:"review_created_at"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Username         string             `db:"username" json:"username"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PerformanceID    pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
	MatchID          pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle       string             `db:"match_title" json:"match_title"`
}

func (q *Queries) GetPlayerReviews(ctx context.Context, arg GetPlayerReviewsParams) ([]GetPlayerReviewsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerReviews, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerReviewsRow
	for rows.Next() {
		var i GetPlayerReviewsRow
		if err := rows.Scan(
			&i.ReviewID,
			&i.ReviewTitle,
			&i.ReviewContent,
			&i.ReviewCreatedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.PerformanceID,
			&i.PerformanceTitle,
			&i.MatchID,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTopRatedPerformances = `-- name: GetPlayerTopRatedPerformances :many
SELECT 
    p.id AS performance_id, p.title AS performance_title, p.cover_image_url AS performance_cover_image, p.minutes_played, p.average_rating,
    m.id AS match_id, m.title AS match_title, m.slug AS match_slug, m.utc_datetime AS match_utc_datetime
FROM performances p
JOIN matches m ON p.match_id = m.id
WHERE p.player_id = $1
ORDER BY p.average_rating DESC, m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type GetPlayerTopRatedPerformancesParams struct {
	PlayerID pgtype.UUID `db:"player_id" json:"player_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetPlayerTopRatedPerformancesRow struct {
	PerformanceID         pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle      string             `db:"performance_title" json:"performance_title"`
	PerformanceCoverImage pgtype.Text        `db:"performance_cover_image" json:"performance_cover_image"`
	MinutesPlayed         int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating         pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	MatchID               pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle            string             `db:"match_title" json:"match_title"`
	MatchSlug             string             `db:"match_slug" json:"match_slug"`
	MatchUtcDatetime      pgtype.Timestamptz `db:"match_utc_datetime" json:"match_utc_datetime"`
}

func (q *Queries) GetPlayerTopRatedPerformances(ctx context.Context, arg GetPlayerTopRatedPerformancesParams) ([]GetPlayerTopRatedPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getPlayerTopRatedPerformances, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerTopRatedPerformancesRow
	for rows.Next() {
		var i GetPlayerTopRatedPerformancesRow
		if err := rows.Scan(
			&i.PerformanceID,
			&i.PerformanceTitle,
			&i.PerformanceCoverImage,
			&i.MinutesPlayed,
			&i.AverageRating,
			&i.MatchID,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.MatchUtcDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByCountry = `-- name: GetPlayersByCountry :many
SELECT 
    p.id, p.name, p.slug, p.known_as, p.photo_url, p.shirt_name
FROM players p
WHERE p.country_id = $1
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type GetPlayersByCountryParams struct {
	CountryID pgtype.UUID `db:"country_id" json:"country_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

type GetPlayersByCountryRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	Slug      string      `db:"slug" json:"slug"`
	KnownAs   pgtype.Text `db:"known_as" json:"known_as"`
	PhotoUrl  pgtype.Text `db:"photo_url" json:"photo_url"`
	ShirtName pgtype.Text `db:"shirt_name" json:"shirt_name"`
}

func (q *Queries) GetPlayersByCountry(ctx context.Context, arg GetPlayersByCountryParams) ([]GetPlayersByCountryRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByCountry, arg.CountryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersByCountryRow
	for rows.Next() {
		var i GetPlayersByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.KnownAs,
			&i.PhotoUrl,
			&i.ShirtName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByTeam = `-- name: GetPlayersByTeam :many
SELECT 
    p.id, p.name, p.slug, p.known_as, p.photo_url, p.shirt_name,
    pt.jersey_number, pt.start_date, pt.is_active
FROM player_teams pt
JOIN players p ON pt.player_id = p.id
WHERE pt.team_id = $1 AND pt.is_active = TRUE
ORDER BY p.name
`

type GetPlayersByTeamRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	KnownAs      pgtype.Text `db:"known_as" json:"known_as"`
	PhotoUrl     pgtype.Text `db:"photo_url" json:"photo_url"`
	ShirtName    pgtype.Text `db:"shirt_name" json:"shirt_name"`
	JerseyNumber pgtype.Int4 `db:"jersey_number" json:"jersey_number"`
	StartDate    pgtype.Date `db:"start_date" json:"start_date"`
	IsActive     bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) GetPlayersByTeam(ctx context.Context, teamID pgtype.UUID) ([]GetPlayersByTeamRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersByTeamRow
	for rows.Next() {
		var i GetPlayersByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.KnownAs,
			&i.PhotoUrl,
			&i.ShirtName,
			&i.JerseyNumber,
			&i.StartDate,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelatedPlayers = `-- name: GetRelatedPlayers :many
SELECT DISTINCT 
    p.id, p.name, p.slug, p.known_as, p.photo_url, p.shirt_name
FROM players p
LEFT JOIN player_teams pt ON p.id = pt.player_id
WHERE p.id <> $1 AND (
    p.country_id = (SELECT country_id FROM players WHERE id = $1)
    OR pt.team_id IN (SELECT team_id FROM player_teams WHERE player_id = $1 AND is_active = TRUE)
)
LIMIT $2
`

type GetRelatedPlayersParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Limit int32       `db:"limit" json:"limit"`
}

type GetRelatedPlayersRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	Slug      string      `db:"slug" json:"slug"`
	KnownAs   pgtype.Text `db:"known_as" json:"known_as"`
	PhotoUrl  pgtype.Text `db:"photo_url" json:"photo_url"`
	ShirtName pgtype.Text `db:"shirt_name" json:"shirt_name"`
}

func (q *Queries) GetRelatedPlayers(ctx context.Context, arg GetRelatedPlayersParams) ([]GetRelatedPlayersRow, error) {
	rows, err := q.db.Query(ctx, getRelatedPlayers, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelatedPlayersRow
	for rows.Next() {
		var i GetRelatedPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.KnownAs,
			&i.PhotoUrl,
			&i.ShirtName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT 
    p.id, p.name, p.slug, p.full_name, p.known_as, p.date_of_birth, p.country_id, p.photo_url, p.height_cm, p.weight_kg, p.shirt_name, p.created_at, p.updated_at,
    c.name AS country_name
FROM players p
LEFT JOIN countries c ON p.country_id = c.id
ORDER BY p.name
LIMIT $1 OFFSET $2
`

type ListPlayersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListPlayersRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Slug        string             `db:"slug" json:"slug"`
	FullName    pgtype.Text        `db:"full_name" json:"full_name"`
	KnownAs     pgtype.Text        `db:"known_as" json:"known_as"`
	DateOfBirth pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	PhotoUrl    pgtype.Text        `db:"photo_url" json:"photo_url"`
	HeightCm    pgtype.Int4        `db:"height_cm" json:"height_cm"`
	WeightKg    pgtype.Int4        `db:"weight_kg" json:"weight_kg"`
	ShirtName   pgtype.Text        `db:"shirt_name" json:"shirt_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CountryName pgtype.Text        `db:"country_name" json:"country_name"`
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FullName,
			&i.KnownAs,
			&i.DateOfBirth,
			&i.CountryID,
			&i.PhotoUrl,
			&i.HeightCm,
			&i.WeightKg,
			&i.ShirtName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CountryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT 
    p.id, p.name, p.slug, p.known_as, p.photo_url, p.shirt_name,
    c.name AS country_name
FROM players p
LEFT JOIN countries c ON p.country_id = c.id
WHERE p.name ILIKE $1 OR p.known_as ILIKE $1 OR p.full_name ILIKE $1
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type SearchPlayersParams struct {
	Name   string `db:"name" json:"name"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type SearchPlayersRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Slug        string      `db:"slug" json:"slug"`
	KnownAs     pgtype.Text `db:"known_as" json:"known_as"`
	PhotoUrl    pgtype.Text `db:"photo_url" json:"photo_url"`
	ShirtName   pgtype.Text `db:"shirt_name" json:"shirt_name"`
	CountryName pgtype.Text `db:"country_name" json:"country_name"`
}

func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPlayersRow
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.KnownAs,
			&i.PhotoUrl,
			&i.ShirtName,
			&i.CountryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    full_name = COALESCE($4, full_name),
    known_as = COALESCE($5, known_as),
    date_of_birth = COALESCE($6, date_of_birth),
    place_of_birth = COALESCE($7, place_of_birth),
    country_id = COALESCE($8, country_id),
    photo_url = COALESCE($9, photo_url),
    height_cm = COALESCE($10, height_cm),
    weight_kg = COALESCE($11, weight_kg),
    shirt_name = COALESCE($12, shirt_name),
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, full_name, known_as, date_of_birth, place_of_birth, country_id, photo_url, height_cm, weight_kg, shirt_name, created_at, updated_at
`

type UpdatePlayerParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	FullName     pgtype.Text `db:"full_name" json:"full_name"`
	KnownAs      pgtype.Text `db:"known_as" json:"known_as"`
	DateOfBirth  pgtype.Date `db:"date_of_birth" json:"date_of_birth"`
	PlaceOfBirth pgtype.Text `db:"place_of_birth" json:"place_of_birth"`
	CountryID    pgtype.UUID `db:"country_id" json:"country_id"`
	PhotoUrl     pgtype.Text `db:"photo_url" json:"photo_url"`
	HeightCm     pgtype.Int4 `db:"height_cm" json:"height_cm"`
	WeightKg     pgtype.Int4 `db:"weight_kg" json:"weight_kg"`
	ShirtName    pgtype.Text `db:"shirt_name" json:"shirt_name"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.FullName,
		arg.KnownAs,
		arg.DateOfBirth,
		arg.PlaceOfBirth,
		arg.CountryID,
		arg.PhotoUrl,
		arg.HeightCm,
		arg.WeightKg,
		arg.ShirtName,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FullName,
		&i.KnownAs,
		&i.DateOfBirth,
		&i.PlaceOfBirth,
		&i.CountryID,
		&i.PhotoUrl,
		&i.HeightCm,
		&i.WeightKg,
		&i.ShirtName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
