// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanExpiredOTPs(ctx context.Context) error
	CleanExpiredRefreshTokens(ctx context.Context) error
	CountTrendingScores(ctx context.Context, arg CountTrendingScoresParams) (int64, error)
	CreateCountry(ctx context.Context, arg CreateCountryParams) (CreateCountryRow, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (CreateMatchRow, error)
	CreateMatchReview(ctx context.Context, arg CreateMatchReviewParams) (MatchReview, error)
	// ============================================================================
	// Match Review Comments
	// ============================================================================
	CreateMatchReviewComment(ctx context.Context, arg CreateMatchReviewCommentParams) (MatchReviewComment, error)
	CreateMatchStat(ctx context.Context, arg CreateMatchStatParams) (MatchStat, error)
	CreateMatchStats(ctx context.Context, arg []CreateMatchStatsParams) (int64, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) error
	CreatePerformance(ctx context.Context, arg CreatePerformanceParams) (CreatePerformanceRow, error)
	CreatePerformanceReview(ctx context.Context, arg CreatePerformanceReviewParams) (PerformanceReview, error)
	// ============================================================================
	// Performance Review Comments
	// ============================================================================
	CreatePerformanceReviewComment(ctx context.Context, arg CreatePerformanceReviewCommentParams) (PerformanceReviewComment, error)
	CreatePerformanceStat(ctx context.Context, arg CreatePerformanceStatParams) (PerformanceStat, error)
	CreatePerformanceStats(ctx context.Context, arg []CreatePerformanceStatsParams) (int64, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateStatType(ctx context.Context, arg CreateStatTypeParams) (StatType, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCountry(ctx context.Context, id pgtype.UUID) error
	DeleteMatch(ctx context.Context, id pgtype.UUID) error
	DeleteMatchRating(ctx context.Context, arg DeleteMatchRatingParams) error
	DeleteMatchReview(ctx context.Context, id pgtype.UUID) error
	DeleteMatchReviewComment(ctx context.Context, id pgtype.UUID) error
	DeleteMatchStat(ctx context.Context, arg DeleteMatchStatParams) error
	DeleteMatchStats(ctx context.Context, matchID pgtype.UUID) error
	DeleteOTP(ctx context.Context, id pgtype.UUID) error
	DeletePerformance(ctx context.Context, id pgtype.UUID) error
	DeletePerformanceRating(ctx context.Context, arg DeletePerformanceRatingParams) error
	DeletePerformanceReview(ctx context.Context, id pgtype.UUID) error
	DeletePerformanceReviewComment(ctx context.Context, id pgtype.UUID) error
	DeletePerformanceStat(ctx context.Context, arg DeletePerformanceStatParams) error
	DeletePerformanceStats(ctx context.Context, performanceID pgtype.UUID) error
	DeletePlayer(ctx context.Context, id pgtype.UUID) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteStatType(ctx context.Context, id pgtype.UUID) error
	DeleteTeam(ctx context.Context, id pgtype.UUID) error
	DeleteTrendingScoresByTypeAndWindow(ctx context.Context, arg DeleteTrendingScoresByTypeAndWindowParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	GetCompletedMatches(ctx context.Context, arg GetCompletedMatchesParams) ([]GetCompletedMatchesRow, error)
	GetCountryByCode(ctx context.Context, upper interface{}) (GetCountryByCodeRow, error)
	GetCountryByID(ctx context.Context, id pgtype.UUID) (GetCountryByIDRow, error)
	GetCurrentTeam(ctx context.Context, playerID pgtype.UUID) ([]GetCurrentTeamRow, error)
	GetMatchAverageRating(ctx context.Context, matchID pgtype.UUID) (GetMatchAverageRatingRow, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (GetMatchByIDRow, error)
	GetMatchBySlug(ctx context.Context, slug string) (GetMatchBySlugRow, error)
	GetMatchPerformances(ctx context.Context, matchID pgtype.UUID) ([]GetMatchPerformancesRow, error)
	GetMatchRating(ctx context.Context, id pgtype.UUID) (MatchRating, error)
	GetMatchRatings(ctx context.Context, arg GetMatchRatingsParams) ([]GetMatchRatingsRow, error)
	GetMatchRatingsCount(ctx context.Context, matchID pgtype.UUID) (int64, error)
	GetMatchReviewAverageRating(ctx context.Context, matchID pgtype.UUID) (pgtype.Numeric, error)
	GetMatchReviewByID(ctx context.Context, id pgtype.UUID) (GetMatchReviewByIDRow, error)
	GetMatchReviewCommentByID(ctx context.Context, id pgtype.UUID) (GetMatchReviewCommentByIDRow, error)
	GetMatchReviewCommentCount(ctx context.Context, reviewID pgtype.UUID) (int64, error)
	GetMatchReviewCommentLikesCount(ctx context.Context, commentID pgtype.UUID) (int64, error)
	GetMatchReviewComments(ctx context.Context, arg GetMatchReviewCommentsParams) ([]GetMatchReviewCommentsRow, error)
	GetMatchReviewCount(ctx context.Context, matchID pgtype.UUID) (int64, error)
	GetMatchReviewLikesCount(ctx context.Context, reviewID pgtype.UUID) (int64, error)
	GetMatchReviews(ctx context.Context, arg GetMatchReviewsParams) ([]GetMatchReviewsRow, error)
	GetMatchStats(ctx context.Context, matchID pgtype.UUID) ([]GetMatchStatsRow, error)
	GetMatchesByDate(ctx context.Context, dollar_1 pgtype.Date) ([]GetMatchesByDateRow, error)
	GetMatchesByTeam(ctx context.Context, arg GetMatchesByTeamParams) ([]GetMatchesByTeamRow, error)
	GetOverviewStats(ctx context.Context) (GetOverviewStatsRow, error)
	// Folds the provider seed rating in as the first vote so the live detail-page
	// value matches the stored average_rating column.
	GetPerformanceAverageRating(ctx context.Context, id pgtype.UUID) (GetPerformanceAverageRatingRow, error)
	GetPerformanceByID(ctx context.Context, id pgtype.UUID) (GetPerformanceByIDRow, error)
	GetPerformanceByMatch(ctx context.Context, matchID pgtype.UUID) ([]GetPerformanceByMatchRow, error)
	GetPerformanceByPlayer(ctx context.Context, playerID pgtype.UUID) ([]GetPerformanceByPlayerRow, error)
	GetPerformanceByPlayerAndMatch(ctx context.Context, arg GetPerformanceByPlayerAndMatchParams) (GetPerformanceByPlayerAndMatchRow, error)
	GetPerformanceBySlug(ctx context.Context, slug pgtype.Text) (GetPerformanceBySlugRow, error)
	GetPerformanceRating(ctx context.Context, id pgtype.UUID) (PerformanceRating, error)
	GetPerformanceRatings(ctx context.Context, arg GetPerformanceRatingsParams) ([]GetPerformanceRatingsRow, error)
	GetPerformanceRatingsCount(ctx context.Context, performanceID pgtype.UUID) (int64, error)
	GetPerformanceReviewAverageRating(ctx context.Context, performanceID pgtype.UUID) (pgtype.Numeric, error)
	GetPerformanceReviewByID(ctx context.Context, id pgtype.UUID) (GetPerformanceReviewByIDRow, error)
	GetPerformanceReviewCommentByID(ctx context.Context, id pgtype.UUID) (GetPerformanceReviewCommentByIDRow, error)
	GetPerformanceReviewCommentCount(ctx context.Context, reviewID pgtype.UUID) (int64, error)
	GetPerformanceReviewCommentLikesCount(ctx context.Context, commentID pgtype.UUID) (int64, error)
	GetPerformanceReviewComments(ctx context.Context, arg GetPerformanceReviewCommentsParams) ([]GetPerformanceReviewCommentsRow, error)
	GetPerformanceReviewCount(ctx context.Context, performanceID pgtype.UUID) (int64, error)
	GetPerformanceReviewLikesCount(ctx context.Context, reviewID pgtype.UUID) (int64, error)
	GetPerformanceReviews(ctx context.Context, arg GetPerformanceReviewsParams) ([]GetPerformanceReviewsRow, error)
	GetPerformanceStat(ctx context.Context, arg GetPerformanceStatParams) (GetPerformanceStatRow, error)
	GetPerformanceStats(ctx context.Context, performanceID pgtype.UUID) ([]GetPerformanceStatsRow, error)
	GetPlayerAggregatedStats(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerAggregatedStatsRow, error)
	GetPlayerAverageRating(ctx context.Context, playerID pgtype.UUID) (GetPlayerAverageRatingRow, error)
	GetPlayerByID(ctx context.Context, id pgtype.UUID) (GetPlayerByIDRow, error)
	GetPlayerBySlug(ctx context.Context, slug string) (GetPlayerBySlugRow, error)
	GetPlayerCareer(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerCareerRow, error)
	GetPlayerMatches(ctx context.Context, arg GetPlayerMatchesParams) ([]GetPlayerMatchesRow, error)
	GetPlayerPerformances(ctx context.Context, arg GetPlayerPerformancesParams) ([]GetPlayerPerformancesRow, error)
	GetPlayerRatings(ctx context.Context, arg GetPlayerRatingsParams) ([]GetPlayerRatingsRow, error)
	GetPlayerReviewCount(ctx context.Context, playerID pgtype.UUID) (int64, error)
	GetPlayerReviews(ctx context.Context, arg GetPlayerReviewsParams) ([]GetPlayerReviewsRow, error)
	GetPlayerTeams(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerTeamsRow, error)
	GetPlayerTopRatedPerformances(ctx context.Context, arg GetPlayerTopRatedPerformancesParams) ([]GetPlayerTopRatedPerformancesRow, error)
	GetPlayersByCountry(ctx context.Context, arg GetPlayersByCountryParams) ([]GetPlayersByCountryRow, error)
	GetPlayersByTeam(ctx context.Context, teamID pgtype.UUID) ([]GetPlayersByTeamRow, error)
	GetPopularMatchReviews(ctx context.Context, arg GetPopularMatchReviewsParams) ([]GetPopularMatchReviewsRow, error)
	GetPopularPerformanceReviews(ctx context.Context, arg GetPopularPerformanceReviewsParams) ([]GetPopularPerformanceReviewsRow, error)
	GetPublicProfile(ctx context.Context, id pgtype.UUID) (GetPublicProfileRow, error)
	GetRecentMatchReviewComments(ctx context.Context, arg GetRecentMatchReviewCommentsParams) ([]GetRecentMatchReviewCommentsRow, error)
	GetRecentMatchReviews(ctx context.Context, arg GetRecentMatchReviewsParams) ([]GetRecentMatchReviewsRow, error)
	GetRecentPerformanceReviewComments(ctx context.Context, arg GetRecentPerformanceReviewCommentsParams) ([]GetRecentPerformanceReviewCommentsRow, error)
	GetRecentPerformanceReviews(ctx context.Context, arg GetRecentPerformanceReviewsParams) ([]GetRecentPerformanceReviewsRow, error)
	GetRecentPerformances(ctx context.Context, arg GetRecentPerformancesParams) ([]GetRecentPerformancesRow, error)
	GetRecentlyRatedMatches(ctx context.Context, arg GetRecentlyRatedMatchesParams) ([]GetRecentlyRatedMatchesRow, error)
	GetRecentlyRatedPerformances(ctx context.Context, arg GetRecentlyRatedPerformancesParams) ([]GetRecentlyRatedPerformancesRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRelatedMatches(ctx context.Context, arg GetRelatedMatchesParams) ([]GetRelatedMatchesRow, error)
	GetRelatedPerformances(ctx context.Context, arg GetRelatedPerformancesParams) ([]GetRelatedPerformancesRow, error)
	GetRelatedPlayers(ctx context.Context, arg GetRelatedPlayersParams) ([]GetRelatedPlayersRow, error)
	GetRelatedTeams(ctx context.Context, arg GetRelatedTeamsParams) ([]GetRelatedTeamsRow, error)
	GetStatTypeByID(ctx context.Context, id pgtype.UUID) (StatType, error)
	GetStatTypesByCategory(ctx context.Context, category string) ([]StatType, error)
	GetTeamAggregatedStats(ctx context.Context, teamID pgtype.UUID) ([]GetTeamAggregatedStatsRow, error)
	GetTeamAverageRating(ctx context.Context, teamID pgtype.UUID) (GetTeamAverageRatingRow, error)
	GetTeamByID(ctx context.Context, id pgtype.UUID) (GetTeamByIDRow, error)
	GetTeamBySlug(ctx context.Context, slug string) (GetTeamBySlugRow, error)
	GetTeamCompletedMatches(ctx context.Context, arg GetTeamCompletedMatchesParams) ([]GetTeamCompletedMatchesRow, error)
	GetTeamMatchStats(ctx context.Context, arg GetTeamMatchStatsParams) ([]GetTeamMatchStatsRow, error)
	GetTeamMatches(ctx context.Context, arg GetTeamMatchesParams) ([]GetTeamMatchesRow, error)
	GetTeamPerformances(ctx context.Context, arg GetTeamPerformancesParams) ([]GetTeamPerformancesRow, error)
	GetTeamPlayers(ctx context.Context, teamID pgtype.UUID) ([]GetTeamPlayersRow, error)
	GetTeamRatings(ctx context.Context, arg GetTeamRatingsParams) ([]GetTeamRatingsRow, error)
	GetTeamReviews(ctx context.Context, arg GetTeamReviewsParams) ([]GetTeamReviewsRow, error)
	GetTeamUpcomingMatches(ctx context.Context, arg GetTeamUpcomingMatchesParams) ([]GetTeamUpcomingMatchesRow, error)
	GetTeamsByCountry(ctx context.Context, countryID pgtype.UUID) ([]GetTeamsByCountryRow, error)
	GetTopMatchesByStat(ctx context.Context, arg GetTopMatchesByStatParams) ([]GetTopMatchesByStatRow, error)
	GetTopPerformancesByStat(ctx context.Context, arg GetTopPerformancesByStatParams) ([]GetTopPerformancesByStatRow, error)
	GetTopRatedMatches(ctx context.Context, arg GetTopRatedMatchesParams) ([]GetTopRatedMatchesRow, error)
	GetTopRatedPerformances(ctx context.Context, arg GetTopRatedPerformancesParams) ([]GetTopRatedPerformancesRow, error)
	GetTrendingScores(ctx context.Context, arg GetTrendingScoresParams) ([]TrendingScore, error)
	GetUpcomingMatches(ctx context.Context, arg GetUpcomingMatchesParams) ([]GetUpcomingMatchesRow, error)
	GetUserActivity(ctx context.Context, arg GetUserActivityParams) ([]GetUserActivityRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserLikesReceived(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUserMatchRating(ctx context.Context, arg GetUserMatchRatingParams) (MatchRating, error)
	GetUserMatchReviewComments(ctx context.Context, arg GetUserMatchReviewCommentsParams) ([]GetUserMatchReviewCommentsRow, error)
	GetUserMatchReviews(ctx context.Context, arg GetUserMatchReviewsParams) ([]GetUserMatchReviewsRow, error)
	GetUserPerformanceRating(ctx context.Context, arg GetUserPerformanceRatingParams) (PerformanceRating, error)
	GetUserPerformanceReviewComments(ctx context.Context, arg GetUserPerformanceReviewCommentsParams) ([]GetUserPerformanceReviewCommentsRow, error)
	GetUserPerformanceReviews(ctx context.Context, arg GetUserPerformanceReviewsParams) ([]GetUserPerformanceReviewsRow, error)
	GetUserRatingCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUserRecentComments(ctx context.Context, arg GetUserRecentCommentsParams) ([]GetUserRecentCommentsRow, error)
	GetUserRecentRatings(ctx context.Context, arg GetUserRecentRatingsParams) ([]GetUserRecentRatingsRow, error)
	GetUserRecentReviews(ctx context.Context, arg GetUserRecentReviewsParams) ([]GetUserRecentReviewsRow, error)
	GetUserReviewCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUsersWhoLikedMatchReview(ctx context.Context, reviewID pgtype.UUID) ([]GetUsersWhoLikedMatchReviewRow, error)
	GetUsersWhoLikedMatchReviewComment(ctx context.Context, commentID pgtype.UUID) ([]GetUsersWhoLikedMatchReviewCommentRow, error)
	GetUsersWhoLikedPerformanceReview(ctx context.Context, reviewID pgtype.UUID) ([]GetUsersWhoLikedPerformanceReviewRow, error)
	GetUsersWhoLikedPerformanceReviewComment(ctx context.Context, commentID pgtype.UUID) ([]GetUsersWhoLikedPerformanceReviewCommentRow, error)
	GetValidOTP(ctx context.Context, arg GetValidOTPParams) (UserOtp, error)
	HasUserLikedMatchReview(ctx context.Context, arg HasUserLikedMatchReviewParams) (bool, error)
	HasUserLikedMatchReviewComment(ctx context.Context, arg HasUserLikedMatchReviewCommentParams) (bool, error)
	HasUserLikedPerformanceReview(ctx context.Context, arg HasUserLikedPerformanceReviewParams) (bool, error)
	HasUserLikedPerformanceReviewComment(ctx context.Context, arg HasUserLikedPerformanceReviewCommentParams) (bool, error)
	HasUserReviewedMatch(ctx context.Context, arg HasUserReviewedMatchParams) (bool, error)
	HasUserReviewedPerformance(ctx context.Context, arg HasUserReviewedPerformanceParams) (bool, error)
	JoinPlayerToTeam(ctx context.Context, arg JoinPlayerToTeamParams) (PlayerTeam, error)
	LeavePlayerTeam(ctx context.Context, arg LeavePlayerTeamParams) (PlayerTeam, error)
	// ============================================================================
	// Match Review Likes
	// ============================================================================
	LikeMatchReview(ctx context.Context, arg LikeMatchReviewParams) (MatchReviewLike, error)
	// ============================================================================
	// Match Review Comment Likes
	// ============================================================================
	LikeMatchReviewComment(ctx context.Context, arg LikeMatchReviewCommentParams) (MatchReviewCommentLike, error)
	// ============================================================================
	// Performance Review Likes
	// ============================================================================
	LikePerformanceReview(ctx context.Context, arg LikePerformanceReviewParams) (PerformanceReviewLike, error)
	// ============================================================================
	// Performance Review Comment Likes
	// ============================================================================
	LikePerformanceReviewComment(ctx context.Context, arg LikePerformanceReviewCommentParams) (PerformanceReviewCommentLike, error)
	ListCountries(ctx context.Context) ([]ListCountriesRow, error)
	ListMatches(ctx context.Context, arg ListMatchesParams) ([]ListMatchesRow, error)
	ListPerformances(ctx context.Context, arg ListPerformancesParams) ([]ListPerformancesRow, error)
	ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error)
	ListStatTypes(ctx context.Context) ([]StatType, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error)
	RateMatch(ctx context.Context, arg RateMatchParams) (MatchRating, error)
	RatePerformance(ctx context.Context, arg RatePerformanceParams) (PerformanceRating, error)
	// Recomputes and persists the stored average_rating/total_votes for a match.
	// Call after any rating mutation. Matches have no provider seed.
	RefreshMatchRating(ctx context.Context, matchID pgtype.UUID) error
	// Recomputes and persists the stored average_rating/total_votes for a
	// performance (seed vote + community votes). Call after any rating mutation.
	RefreshPerformanceRating(ctx context.Context, id pgtype.UUID) error
	SearchCountries(ctx context.Context, name string) ([]SearchCountriesRow, error)
	SearchMatches(ctx context.Context, arg SearchMatchesParams) ([]SearchMatchesRow, error)
	SearchPerformances(ctx context.Context, arg SearchPerformancesParams) ([]SearchPerformancesRow, error)
	SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error)
	SearchTeams(ctx context.Context, arg SearchTeamsParams) ([]SearchTeamsRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	UnlikeMatchReview(ctx context.Context, arg UnlikeMatchReviewParams) error
	UnlikeMatchReviewComment(ctx context.Context, arg UnlikeMatchReviewCommentParams) error
	UnlikePerformanceReview(ctx context.Context, arg UnlikePerformanceReviewParams) error
	UnlikePerformanceReviewComment(ctx context.Context, arg UnlikePerformanceReviewCommentParams) error
	UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (UpdateAvatarRow, error)
	UpdateBio(ctx context.Context, arg UpdateBioParams) (UpdateBioRow, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (UpdateCountryRow, error)
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (UpdateDisplayNameRow, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (UpdateEmailRow, error)
	UpdateJerseyNumber(ctx context.Context, arg UpdateJerseyNumberParams) (PlayerTeam, error)
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (UpdateMatchRow, error)
	UpdateMatchRating(ctx context.Context, arg UpdateMatchRatingParams) (MatchRating, error)
	UpdateMatchReview(ctx context.Context, arg UpdateMatchReviewParams) (MatchReview, error)
	UpdateMatchReviewComment(ctx context.Context, arg UpdateMatchReviewCommentParams) (MatchReviewComment, error)
	UpdateMatchStat(ctx context.Context, arg UpdateMatchStatParams) (MatchStat, error)
	UpdatePerformance(ctx context.Context, arg UpdatePerformanceParams) (UpdatePerformanceRow, error)
	UpdatePerformanceRating(ctx context.Context, arg UpdatePerformanceRatingParams) (PerformanceRating, error)
	UpdatePerformanceReview(ctx context.Context, arg UpdatePerformanceReviewParams) (PerformanceReview, error)
	UpdatePerformanceReviewComment(ctx context.Context, arg UpdatePerformanceReviewCommentParams) (PerformanceReviewComment, error)
	UpdatePerformanceStat(ctx context.Context, arg UpdatePerformanceStatParams) (PerformanceStat, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdatePlayerTeam(ctx context.Context, arg UpdatePlayerTeamParams) (PlayerTeam, error)
	UpdateSquadNumber(ctx context.Context, arg UpdateSquadNumberParams) (PlayerTeam, error)
	UpdateStatType(ctx context.Context, arg UpdateStatTypeParams) (StatType, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (UpdateTeamRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UpdateUsernameRow, error)
	UpsertTrendingScore(ctx context.Context, arg UpsertTrendingScoreParams) error
	VerifyUserEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
