// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_likes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatchReviewCommentLikesCount = `-- name: GetMatchReviewCommentLikesCount :one
SELECT COUNT(*)::bigint AS likes_count
FROM match_review_comment_likes
WHERE comment_id = $1
`

func (q *Queries) GetMatchReviewCommentLikesCount(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMatchReviewCommentLikesCount, commentID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}

const getMatchReviewLikesCount = `-- name: GetMatchReviewLikesCount :one
SELECT COUNT(*)::bigint AS likes_count
FROM match_review_likes
WHERE review_id = $1
`

func (q *Queries) GetMatchReviewLikesCount(ctx context.Context, reviewID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMatchReviewLikesCount, reviewID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}

const getPerformanceReviewCommentLikesCount = `-- name: GetPerformanceReviewCommentLikesCount :one
SELECT COUNT(*)::bigint AS likes_count
FROM performance_review_comment_likes
WHERE comment_id = $1
`

func (q *Queries) GetPerformanceReviewCommentLikesCount(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewCommentLikesCount, commentID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}

const getPerformanceReviewLikesCount = `-- name: GetPerformanceReviewLikesCount :one
SELECT COUNT(*)::bigint AS likes_count
FROM performance_review_likes
WHERE review_id = $1
`

func (q *Queries) GetPerformanceReviewLikesCount(ctx context.Context, reviewID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewLikesCount, reviewID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}

const getUsersWhoLikedMatchReview = `-- name: GetUsersWhoLikedMatchReview :many
SELECT 
    u.id, u.username, u.display_name, u.avatar_url, mrl.created_at AS liked_at
FROM match_review_likes mrl
JOIN users u ON mrl.user_id = u.id
WHERE mrl.review_id = $1
ORDER BY mrl.created_at DESC
`

type GetUsersWhoLikedMatchReviewRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	LikedAt     pgtype.Timestamptz `db:"liked_at" json:"liked_at"`
}

func (q *Queries) GetUsersWhoLikedMatchReview(ctx context.Context, reviewID pgtype.UUID) ([]GetUsersWhoLikedMatchReviewRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoLikedMatchReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWhoLikedMatchReviewRow
	for rows.Next() {
		var i GetUsersWhoLikedMatchReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoLikedMatchReviewComment = `-- name: GetUsersWhoLikedMatchReviewComment :many
SELECT 
    u.id, u.username, u.display_name, u.avatar_url, mrcl.created_at AS liked_at
FROM match_review_comment_likes mrcl
JOIN users u ON mrcl.user_id = u.id
WHERE mrcl.comment_id = $1
ORDER BY mrcl.created_at DESC
`

type GetUsersWhoLikedMatchReviewCommentRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	LikedAt     pgtype.Timestamptz `db:"liked_at" json:"liked_at"`
}

func (q *Queries) GetUsersWhoLikedMatchReviewComment(ctx context.Context, commentID pgtype.UUID) ([]GetUsersWhoLikedMatchReviewCommentRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoLikedMatchReviewComment, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWhoLikedMatchReviewCommentRow
	for rows.Next() {
		var i GetUsersWhoLikedMatchReviewCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoLikedPerformanceReview = `-- name: GetUsersWhoLikedPerformanceReview :many
SELECT 
    u.id, u.username, u.display_name, u.avatar_url, prl.created_at AS liked_at
FROM performance_review_likes prl
JOIN users u ON prl.user_id = u.id
WHERE prl.review_id = $1
ORDER BY prl.created_at DESC
`

type GetUsersWhoLikedPerformanceReviewRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	LikedAt     pgtype.Timestamptz `db:"liked_at" json:"liked_at"`
}

func (q *Queries) GetUsersWhoLikedPerformanceReview(ctx context.Context, reviewID pgtype.UUID) ([]GetUsersWhoLikedPerformanceReviewRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoLikedPerformanceReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWhoLikedPerformanceReviewRow
	for rows.Next() {
		var i GetUsersWhoLikedPerformanceReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoLikedPerformanceReviewComment = `-- name: GetUsersWhoLikedPerformanceReviewComment :many
SELECT 
    u.id, u.username, u.display_name, u.avatar_url, prcl.created_at AS liked_at
FROM performance_review_comment_likes prcl
JOIN users u ON prcl.user_id = u.id
WHERE prcl.comment_id = $1
ORDER BY prcl.created_at DESC
`

type GetUsersWhoLikedPerformanceReviewCommentRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	LikedAt     pgtype.Timestamptz `db:"liked_at" json:"liked_at"`
}

func (q *Queries) GetUsersWhoLikedPerformanceReviewComment(ctx context.Context, commentID pgtype.UUID) ([]GetUsersWhoLikedPerformanceReviewCommentRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoLikedPerformanceReviewComment, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWhoLikedPerformanceReviewCommentRow
	for rows.Next() {
		var i GetUsersWhoLikedPerformanceReviewCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserLikedMatchReview = `-- name: HasUserLikedMatchReview :one
SELECT EXISTS (
    SELECT 1 FROM match_review_likes
    WHERE review_id = $1 AND user_id = $2
)::boolean AS has_liked
`

type HasUserLikedMatchReviewParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserLikedMatchReview(ctx context.Context, arg HasUserLikedMatchReviewParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedMatchReview, arg.ReviewID, arg.UserID)
	var has_liked bool
	err := row.Scan(&has_liked)
	return has_liked, err
}

const hasUserLikedMatchReviewComment = `-- name: HasUserLikedMatchReviewComment :one
SELECT EXISTS (
    SELECT 1 FROM match_review_comment_likes
    WHERE comment_id = $1 AND user_id = $2
)::boolean AS has_liked
`

type HasUserLikedMatchReviewCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserLikedMatchReviewComment(ctx context.Context, arg HasUserLikedMatchReviewCommentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedMatchReviewComment, arg.CommentID, arg.UserID)
	var has_liked bool
	err := row.Scan(&has_liked)
	return has_liked, err
}

const hasUserLikedPerformanceReview = `-- name: HasUserLikedPerformanceReview :one
SELECT EXISTS (
    SELECT 1 FROM performance_review_likes
    WHERE review_id = $1 AND user_id = $2
)::boolean AS has_liked
`

type HasUserLikedPerformanceReviewParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserLikedPerformanceReview(ctx context.Context, arg HasUserLikedPerformanceReviewParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedPerformanceReview, arg.ReviewID, arg.UserID)
	var has_liked bool
	err := row.Scan(&has_liked)
	return has_liked, err
}

const hasUserLikedPerformanceReviewComment = `-- name: HasUserLikedPerformanceReviewComment :one
SELECT EXISTS (
    SELECT 1 FROM performance_review_comment_likes
    WHERE comment_id = $1 AND user_id = $2
)::boolean AS has_liked
`

type HasUserLikedPerformanceReviewCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserLikedPerformanceReviewComment(ctx context.Context, arg HasUserLikedPerformanceReviewCommentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedPerformanceReviewComment, arg.CommentID, arg.UserID)
	var has_liked bool
	err := row.Scan(&has_liked)
	return has_liked, err
}

const likeMatchReview = `-- name: LikeMatchReview :one

INSERT INTO match_review_likes (
    review_id,
    user_id
) VALUES (
    $1, $2
)
RETURNING review_id, user_id, created_at
`

type LikeMatchReviewParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

// ============================================================================
// Match Review Likes
// ============================================================================
func (q *Queries) LikeMatchReview(ctx context.Context, arg LikeMatchReviewParams) (MatchReviewLike, error) {
	row := q.db.QueryRow(ctx, likeMatchReview, arg.ReviewID, arg.UserID)
	var i MatchReviewLike
	err := row.Scan(&i.ReviewID, &i.UserID, &i.CreatedAt)
	return i, err
}

const likeMatchReviewComment = `-- name: LikeMatchReviewComment :one

INSERT INTO match_review_comment_likes (
    comment_id,
    user_id
) VALUES (
    $1, $2
)
RETURNING comment_id, user_id, created_at
`

type LikeMatchReviewCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

// ============================================================================
// Match Review Comment Likes
// ============================================================================
func (q *Queries) LikeMatchReviewComment(ctx context.Context, arg LikeMatchReviewCommentParams) (MatchReviewCommentLike, error) {
	row := q.db.QueryRow(ctx, likeMatchReviewComment, arg.CommentID, arg.UserID)
	var i MatchReviewCommentLike
	err := row.Scan(&i.CommentID, &i.UserID, &i.CreatedAt)
	return i, err
}

const likePerformanceReview = `-- name: LikePerformanceReview :one

INSERT INTO performance_review_likes (
    review_id,
    user_id
) VALUES (
    $1, $2
)
RETURNING review_id, user_id, created_at
`

type LikePerformanceReviewParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

// ============================================================================
// Performance Review Likes
// ============================================================================
func (q *Queries) LikePerformanceReview(ctx context.Context, arg LikePerformanceReviewParams) (PerformanceReviewLike, error) {
	row := q.db.QueryRow(ctx, likePerformanceReview, arg.ReviewID, arg.UserID)
	var i PerformanceReviewLike
	err := row.Scan(&i.ReviewID, &i.UserID, &i.CreatedAt)
	return i, err
}

const likePerformanceReviewComment = `-- name: LikePerformanceReviewComment :one

INSERT INTO performance_review_comment_likes (
    comment_id,
    user_id
) VALUES (
    $1, $2
)
RETURNING comment_id, user_id, created_at
`

type LikePerformanceReviewCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

// ============================================================================
// Performance Review Comment Likes
// ============================================================================
func (q *Queries) LikePerformanceReviewComment(ctx context.Context, arg LikePerformanceReviewCommentParams) (PerformanceReviewCommentLike, error) {
	row := q.db.QueryRow(ctx, likePerformanceReviewComment, arg.CommentID, arg.UserID)
	var i PerformanceReviewCommentLike
	err := row.Scan(&i.CommentID, &i.UserID, &i.CreatedAt)
	return i, err
}

const unlikeMatchReview = `-- name: UnlikeMatchReview :exec
DELETE FROM match_review_likes
WHERE review_id = $1 AND user_id = $2
`

type UnlikeMatchReviewParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikeMatchReview(ctx context.Context, arg UnlikeMatchReviewParams) error {
	_, err := q.db.Exec(ctx, unlikeMatchReview, arg.ReviewID, arg.UserID)
	return err
}

const unlikeMatchReviewComment = `-- name: UnlikeMatchReviewComment :exec
DELETE FROM match_review_comment_likes
WHERE comment_id = $1 AND user_id = $2
`

type UnlikeMatchReviewCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikeMatchReviewComment(ctx context.Context, arg UnlikeMatchReviewCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeMatchReviewComment, arg.CommentID, arg.UserID)
	return err
}

const unlikePerformanceReview = `-- name: UnlikePerformanceReview :exec
DELETE FROM performance_review_likes
WHERE review_id = $1 AND user_id = $2
`

type UnlikePerformanceReviewParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikePerformanceReview(ctx context.Context, arg UnlikePerformanceReviewParams) error {
	_, err := q.db.Exec(ctx, unlikePerformanceReview, arg.ReviewID, arg.UserID)
	return err
}

const unlikePerformanceReviewComment = `-- name: UnlikePerformanceReviewComment :exec
DELETE FROM performance_review_comment_likes
WHERE comment_id = $1 AND user_id = $2
`

type UnlikePerformanceReviewCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikePerformanceReviewComment(ctx context.Context, arg UnlikePerformanceReviewCommentParams) error {
	_, err := q.db.Exec(ctx, unlikePerformanceReviewComment, arg.CommentID, arg.UserID)
	return err
}
