// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchReviewComment = `-- name: CreateMatchReviewComment :one

INSERT INTO match_review_comments (
    review_id,
    user_id,
    body
) VALUES (
    $1, $2, $3
)
RETURNING id, review_id, user_id, body, created_at, updated_at
`

type CreateMatchReviewCommentParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Body     string      `db:"body" json:"body"`
}

// ============================================================================
// Match Review Comments
// ============================================================================
func (q *Queries) CreateMatchReviewComment(ctx context.Context, arg CreateMatchReviewCommentParams) (MatchReviewComment, error) {
	row := q.db.QueryRow(ctx, createMatchReviewComment, arg.ReviewID, arg.UserID, arg.Body)
	var i MatchReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPerformanceReviewComment = `-- name: CreatePerformanceReviewComment :one

INSERT INTO performance_review_comments (
    review_id,
    user_id,
    body
) VALUES (
    $1, $2, $3
)
RETURNING id, review_id, user_id, body, created_at, updated_at
`

type CreatePerformanceReviewCommentParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Body     string      `db:"body" json:"body"`
}

// ============================================================================
// Performance Review Comments
// ============================================================================
func (q *Queries) CreatePerformanceReviewComment(ctx context.Context, arg CreatePerformanceReviewCommentParams) (PerformanceReviewComment, error) {
	row := q.db.QueryRow(ctx, createPerformanceReviewComment, arg.ReviewID, arg.UserID, arg.Body)
	var i PerformanceReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatchReviewComment = `-- name: DeleteMatchReviewComment :exec
DELETE FROM match_review_comments
WHERE id = $1
`

func (q *Queries) DeleteMatchReviewComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatchReviewComment, id)
	return err
}

const deletePerformanceReviewComment = `-- name: DeletePerformanceReviewComment :exec
DELETE FROM performance_review_comments
WHERE id = $1
`

func (q *Queries) DeletePerformanceReviewComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerformanceReviewComment, id)
	return err
}

const getMatchReviewCommentByID = `-- name: GetMatchReviewCommentByID :one
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username, u.display_name, u.avatar_url
FROM match_review_comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = $1 LIMIT 1
`

type GetMatchReviewCommentByIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ReviewID    pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetMatchReviewCommentByID(ctx context.Context, id pgtype.UUID) (GetMatchReviewCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchReviewCommentByID, id)
	var i GetMatchReviewCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getMatchReviewCommentCount = `-- name: GetMatchReviewCommentCount :one
SELECT COUNT(*)::bigint AS comment_count
FROM match_review_comments
WHERE review_id = $1
`

func (q *Queries) GetMatchReviewCommentCount(ctx context.Context, reviewID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMatchReviewCommentCount, reviewID)
	var comment_count int64
	err := row.Scan(&comment_count)
	return comment_count, err
}

const getMatchReviewComments = `-- name: GetMatchReviewComments :many
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username, u.display_name, u.avatar_url
FROM match_review_comments c
JOIN users u ON c.user_id = u.id
WHERE c.review_id = $1
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type GetMatchReviewCommentsParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetMatchReviewCommentsRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ReviewID    pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetMatchReviewComments(ctx context.Context, arg GetMatchReviewCommentsParams) ([]GetMatchReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getMatchReviewComments, arg.ReviewID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchReviewCommentsRow
	for rows.Next() {
		var i GetMatchReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerformanceReviewCommentByID = `-- name: GetPerformanceReviewCommentByID :one
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username, u.display_name, u.avatar_url
FROM performance_review_comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = $1 LIMIT 1
`

type GetPerformanceReviewCommentByIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ReviewID    pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetPerformanceReviewCommentByID(ctx context.Context, id pgtype.UUID) (GetPerformanceReviewCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewCommentByID, id)
	var i GetPerformanceReviewCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getPerformanceReviewCommentCount = `-- name: GetPerformanceReviewCommentCount :one
SELECT COUNT(*)::bigint AS comment_count
FROM performance_review_comments
WHERE review_id = $1
`

func (q *Queries) GetPerformanceReviewCommentCount(ctx context.Context, reviewID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPerformanceReviewCommentCount, reviewID)
	var comment_count int64
	err := row.Scan(&comment_count)
	return comment_count, err
}

const getPerformanceReviewComments = `-- name: GetPerformanceReviewComments :many
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username, u.display_name, u.avatar_url
FROM performance_review_comments c
JOIN users u ON c.user_id = u.id
WHERE c.review_id = $1
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type GetPerformanceReviewCommentsParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type GetPerformanceReviewCommentsRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ReviewID    pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetPerformanceReviewComments(ctx context.Context, arg GetPerformanceReviewCommentsParams) ([]GetPerformanceReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getPerformanceReviewComments, arg.ReviewID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPerformanceReviewCommentsRow
	for rows.Next() {
		var i GetPerformanceReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMatchReviewComments = `-- name: GetRecentMatchReviewComments :many
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username, u.display_name, u.avatar_url,
    m.title AS match_title
FROM match_review_comments c
JOIN users u ON c.user_id = u.id
JOIN match_reviews r ON c.review_id = r.id
JOIN matches m ON r.match_id = m.id
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentMatchReviewCommentsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentMatchReviewCommentsRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ReviewID    pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	MatchTitle  string             `db:"match_title" json:"match_title"`
}

func (q *Queries) GetRecentMatchReviewComments(ctx context.Context, arg GetRecentMatchReviewCommentsParams) ([]GetRecentMatchReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getRecentMatchReviewComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMatchReviewCommentsRow
	for rows.Next() {
		var i GetRecentMatchReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPerformanceReviewComments = `-- name: GetRecentPerformanceReviewComments :many
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username, u.display_name, u.avatar_url,
    p.title AS performance_title
FROM performance_review_comments c
JOIN users u ON c.user_id = u.id
JOIN performance_reviews r ON c.review_id = r.id
JOIN performances p ON r.performance_id = p.id
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentPerformanceReviewCommentsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetRecentPerformanceReviewCommentsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ReviewID         pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Body             string             `db:"body" json:"body"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username         string             `db:"username" json:"username"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
}

func (q *Queries) GetRecentPerformanceReviewComments(ctx context.Context, arg GetRecentPerformanceReviewCommentsParams) ([]GetRecentPerformanceReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getRecentPerformanceReviewComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPerformanceReviewCommentsRow
	for rows.Next() {
		var i GetRecentPerformanceReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.PerformanceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMatchReviewComments = `-- name: GetUserMatchReviewComments :many
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    r.match_id, m.title AS match_title
FROM match_review_comments c
JOIN match_reviews r ON c.review_id = r.id
JOIN matches m ON r.match_id = m.id
WHERE c.user_id = $1
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserMatchReviewCommentsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserMatchReviewCommentsRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ReviewID   pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Body       string             `db:"body" json:"body"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MatchID    pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle string             `db:"match_title" json:"match_title"`
}

func (q *Queries) GetUserMatchReviewComments(ctx context.Context, arg GetUserMatchReviewCommentsParams) ([]GetUserMatchReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getUserMatchReviewComments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMatchReviewCommentsRow
	for rows.Next() {
		var i GetUserMatchReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchID,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPerformanceReviewComments = `-- name: GetUserPerformanceReviewComments :many
SELECT 
    c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at,
    r.performance_id, p.title AS performance_title
FROM performance_review_comments c
JOIN performance_reviews r ON c.review_id = r.id
JOIN performances p ON r.performance_id = p.id
WHERE c.user_id = $1
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserPerformanceReviewCommentsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserPerformanceReviewCommentsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ReviewID         pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Body             string             `db:"body" json:"body"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PerformanceID    pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
}

func (q *Queries) GetUserPerformanceReviewComments(ctx context.Context, arg GetUserPerformanceReviewCommentsParams) ([]GetUserPerformanceReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getUserPerformanceReviewComments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPerformanceReviewCommentsRow
	for rows.Next() {
		var i GetUserPerformanceReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PerformanceID,
			&i.PerformanceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchReviewComment = `-- name: UpdateMatchReviewComment :one
UPDATE match_review_comments
SET 
    body = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, review_id, user_id, body, created_at, updated_at
`

type UpdateMatchReviewCommentParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Body string      `db:"body" json:"body"`
}

func (q *Queries) UpdateMatchReviewComment(ctx context.Context, arg UpdateMatchReviewCommentParams) (MatchReviewComment, error) {
	row := q.db.QueryRow(ctx, updateMatchReviewComment, arg.ID, arg.Body)
	var i MatchReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePerformanceReviewComment = `-- name: UpdatePerformanceReviewComment :one
UPDATE performance_review_comments
SET 
    body = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, review_id, user_id, body, created_at, updated_at
`

type UpdatePerformanceReviewCommentParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Body string      `db:"body" json:"body"`
}

func (q *Queries) UpdatePerformanceReviewComment(ctx context.Context, arg UpdatePerformanceReviewCommentParams) (PerformanceReviewComment, error) {
	row := q.db.QueryRow(ctx, updatePerformanceReviewComment, arg.ID, arg.Body)
	var i PerformanceReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
