// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stat_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStatType = `-- name: CreateStatType :one
INSERT INTO stat_types (
    name,
    short_name,
    unit,
    category,
    display_order
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, short_name, unit, category, display_order
`

type CreateStatTypeParams struct {
	Name         string      `db:"name" json:"name"`
	ShortName    string      `db:"short_name" json:"short_name"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	Category     string      `db:"category" json:"category"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
}

func (q *Queries) CreateStatType(ctx context.Context, arg CreateStatTypeParams) (StatType, error) {
	row := q.db.QueryRow(ctx, createStatType,
		arg.Name,
		arg.ShortName,
		arg.Unit,
		arg.Category,
		arg.DisplayOrder,
	)
	var i StatType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Unit,
		&i.Category,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteStatType = `-- name: DeleteStatType :exec
DELETE FROM stat_types
WHERE id = $1
`

func (q *Queries) DeleteStatType(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStatType, id)
	return err
}

const getStatTypeByID = `-- name: GetStatTypeByID :one
SELECT id, name, short_name, unit, category, display_order
FROM stat_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStatTypeByID(ctx context.Context, id pgtype.UUID) (StatType, error) {
	row := q.db.QueryRow(ctx, getStatTypeByID, id)
	var i StatType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Unit,
		&i.Category,
		&i.DisplayOrder,
	)
	return i, err
}

const getStatTypesByCategory = `-- name: GetStatTypesByCategory :many
SELECT id, name, short_name, unit, category, display_order
FROM stat_types
WHERE category = $1
ORDER BY display_order
`

func (q *Queries) GetStatTypesByCategory(ctx context.Context, category string) ([]StatType, error) {
	rows, err := q.db.Query(ctx, getStatTypesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatType
	for rows.Next() {
		var i StatType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Unit,
			&i.Category,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatTypes = `-- name: ListStatTypes :many
SELECT id, name, short_name, unit, category, display_order
FROM stat_types
ORDER BY category, display_order
`

func (q *Queries) ListStatTypes(ctx context.Context) ([]StatType, error) {
	rows, err := q.db.Query(ctx, listStatTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatType
	for rows.Next() {
		var i StatType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Unit,
			&i.Category,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatType = `-- name: UpdateStatType :one
UPDATE stat_types
SET 
    name = COALESCE($2, name),
    short_name = COALESCE($3, short_name),
    unit = COALESCE($4, unit),
    category = COALESCE($5, category),
    display_order = COALESCE($6, display_order)
WHERE id = $1
RETURNING id, name, short_name, unit, category, display_order
`

type UpdateStatTypeParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	ShortName    string      `db:"short_name" json:"short_name"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	Category     string      `db:"category" json:"category"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
}

func (q *Queries) UpdateStatType(ctx context.Context, arg UpdateStatTypeParams) (StatType, error) {
	row := q.db.QueryRow(ctx, updateStatType,
		arg.ID,
		arg.Name,
		arg.ShortName,
		arg.Unit,
		arg.Category,
		arg.DisplayOrder,
	)
	var i StatType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Unit,
		&i.Category,
		&i.DisplayOrder,
	)
	return i, err
}
