// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    country_id,
    name,
    short_name,
    slug,
    type,
    logo_url,
    flag_emoji,
    founded_year
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, country_id, name, short_name, slug, type, logo_url, flag_emoji, founded_year, created_at, updated_at
`

type CreateTeamParams struct {
	CountryID   pgtype.UUID `db:"country_id" json:"country_id"`
	Name        string      `db:"name" json:"name"`
	ShortName   string      `db:"short_name" json:"short_name"`
	Slug        string      `db:"slug" json:"slug"`
	Type        TeamType    `db:"type" json:"type"`
	LogoUrl     pgtype.Text `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4 `db:"founded_year" json:"founded_year"`
}

type CreateTeamRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	Name        string             `db:"name" json:"name"`
	ShortName   string             `db:"short_name" json:"short_name"`
	Slug        string             `db:"slug" json:"slug"`
	Type        TeamType           `db:"type" json:"type"`
	LogoUrl     pgtype.Text        `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4        `db:"founded_year" json:"founded_year"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.CountryID,
		arg.Name,
		arg.ShortName,
		arg.Slug,
		arg.Type,
		arg.LogoUrl,
		arg.FlagEmoji,
		arg.FoundedYear,
	)
	var i CreateTeamRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Name,
		&i.ShortName,
		&i.Slug,
		&i.Type,
		&i.LogoUrl,
		&i.FlagEmoji,
		&i.FoundedYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getRelatedTeams = `-- name: GetRelatedTeams :many
SELECT 
    t.id, t.name, t.short_name, t.slug, t.logo_url, t.flag_emoji
FROM teams t
WHERE t.id <> $1 AND t.country_id = (SELECT country_id FROM teams WHERE id = $1) AND t.type = (SELECT type FROM teams WHERE id = $1)
ORDER BY t.name
LIMIT $2
`

type GetRelatedTeamsParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Limit int32       `db:"limit" json:"limit"`
}

type GetRelatedTeamsRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	ShortName string      `db:"short_name" json:"short_name"`
	Slug      string      `db:"slug" json:"slug"`
	LogoUrl   pgtype.Text `db:"logo_url" json:"logo_url"`
	FlagEmoji pgtype.Text `db:"flag_emoji" json:"flag_emoji"`
}

func (q *Queries) GetRelatedTeams(ctx context.Context, arg GetRelatedTeamsParams) ([]GetRelatedTeamsRow, error) {
	rows, err := q.db.Query(ctx, getRelatedTeams, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelatedTeamsRow
	for rows.Next() {
		var i GetRelatedTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Slug,
			&i.LogoUrl,
			&i.FlagEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamAggregatedStats = `-- name: GetTeamAggregatedStats :many
SELECT 
    st.id AS stat_type_id,
    st.name AS stat_name,
    st.short_name AS stat_short_name,
    st.unit AS stat_unit,
    st.category AS stat_category,
    SUM(ms.value)::double precision AS total_value,
    AVG(ms.value)::double precision AS average_value
FROM match_stats ms
JOIN stat_types st ON ms.stat_type_id = st.id
WHERE ms.team_id = $1
GROUP BY st.id, st.name, st.short_name, st.unit, st.category, st.display_order
ORDER BY st.category, st.display_order
`

type GetTeamAggregatedStatsRow struct {
	StatTypeID    pgtype.UUID `db:"stat_type_id" json:"stat_type_id"`
	StatName      string      `db:"stat_name" json:"stat_name"`
	StatShortName string      `db:"stat_short_name" json:"stat_short_name"`
	StatUnit      pgtype.Text `db:"stat_unit" json:"stat_unit"`
	StatCategory  string      `db:"stat_category" json:"stat_category"`
	TotalValue    float64     `db:"total_value" json:"total_value"`
	AverageValue  float64     `db:"average_value" json:"average_value"`
}

func (q *Queries) GetTeamAggregatedStats(ctx context.Context, teamID pgtype.UUID) ([]GetTeamAggregatedStatsRow, error) {
	rows, err := q.db.Query(ctx, getTeamAggregatedStats, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamAggregatedStatsRow
	for rows.Next() {
		var i GetTeamAggregatedStatsRow
		if err := rows.Scan(
			&i.StatTypeID,
			&i.StatName,
			&i.StatShortName,
			&i.StatUnit,
			&i.StatCategory,
			&i.TotalValue,
			&i.AverageValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamAverageRating = `-- name: GetTeamAverageRating :one
SELECT 
    COALESCE(AVG(pr.rating), 0.0)::numeric(2,1) AS average_rating,
    COUNT(pr.id)::bigint AS total_votes
FROM performances p
JOIN player_teams pt ON p.player_team_id = pt.id
JOIN performance_ratings pr ON p.id = pr.performance_id
WHERE pt.team_id = $1
`

type GetTeamAverageRatingRow struct {
	AverageRating pgtype.Numeric `db:"average_rating" json:"average_rating"`
	TotalVotes    int64          `db:"total_votes" json:"total_votes"`
}

func (q *Queries) GetTeamAverageRating(ctx context.Context, teamID pgtype.UUID) (GetTeamAverageRatingRow, error) {
	row := q.db.QueryRow(ctx, getTeamAverageRating, teamID)
	var i GetTeamAverageRatingRow
	err := row.Scan(&i.AverageRating, &i.TotalVotes)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT 
    t.id, t.country_id, t.name, t.short_name, t.slug, t.type, t.logo_url, t.flag_emoji, t.founded_year, t.created_at, t.updated_at,
    c.name AS country_name
FROM teams t
LEFT JOIN countries c ON t.country_id = c.id
WHERE t.id = $1 LIMIT 1
`

type GetTeamByIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	Name        string             `db:"name" json:"name"`
	ShortName   string             `db:"short_name" json:"short_name"`
	Slug        string             `db:"slug" json:"slug"`
	Type        TeamType           `db:"type" json:"type"`
	LogoUrl     pgtype.Text        `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4        `db:"founded_year" json:"founded_year"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CountryName pgtype.Text        `db:"country_name" json:"country_name"`
}

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (GetTeamByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i GetTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Name,
		&i.ShortName,
		&i.Slug,
		&i.Type,
		&i.LogoUrl,
		&i.FlagEmoji,
		&i.FoundedYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryName,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT 
    t.id, t.country_id, t.name, t.short_name, t.slug, t.type, t.logo_url, t.flag_emoji, t.founded_year, t.created_at, t.updated_at,
    c.name AS country_name
FROM teams t
LEFT JOIN countries c ON t.country_id = c.id
WHERE t.slug = $1 LIMIT 1
`

type GetTeamBySlugRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	Name        string             `db:"name" json:"name"`
	ShortName   string             `db:"short_name" json:"short_name"`
	Slug        string             `db:"slug" json:"slug"`
	Type        TeamType           `db:"type" json:"type"`
	LogoUrl     pgtype.Text        `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4        `db:"founded_year" json:"founded_year"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CountryName pgtype.Text        `db:"country_name" json:"country_name"`
}

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (GetTeamBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, slug)
	var i GetTeamBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Name,
		&i.ShortName,
		&i.Slug,
		&i.Type,
		&i.LogoUrl,
		&i.FlagEmoji,
		&i.FoundedYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryName,
	)
	return i, err
}

const getTeamCompletedMatches = `-- name: GetTeamCompletedMatches :many
SELECT 
    m.id, m.home_team_id, m.away_team_id, m.title, m.slug, m.utc_datetime, m.venue, m.home_score, m.away_score,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url, ht.flag_emoji AS home_team_flag_emoji,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url, at.flag_emoji AS away_team_flag_emoji
FROM matches m
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
WHERE (m.home_team_id = $1 OR m.away_team_id = $1) AND m.utc_datetime <= now()
ORDER BY m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type GetTeamCompletedMatchesParams struct {
	HomeTeamID pgtype.UUID `db:"home_team_id" json:"home_team_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetTeamCompletedMatchesRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	HomeTeamID        pgtype.UUID        `db:"home_team_id" json:"home_team_id"`
	AwayTeamID        pgtype.UUID        `db:"away_team_id" json:"away_team_id"`
	Title             string             `db:"title" json:"title"`
	Slug              string             `db:"slug" json:"slug"`
	UtcDatetime       pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	Venue             pgtype.Text        `db:"venue" json:"venue"`
	HomeScore         int32              `db:"home_score" json:"home_score"`
	AwayScore         int32              `db:"away_score" json:"away_score"`
	HomeTeamName      string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl   pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	HomeTeamFlagEmoji pgtype.Text        `db:"home_team_flag_emoji" json:"home_team_flag_emoji"`
	AwayTeamName      string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl   pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
	AwayTeamFlagEmoji pgtype.Text        `db:"away_team_flag_emoji" json:"away_team_flag_emoji"`
}

func (q *Queries) GetTeamCompletedMatches(ctx context.Context, arg GetTeamCompletedMatchesParams) ([]GetTeamCompletedMatchesRow, error) {
	rows, err := q.db.Query(ctx, getTeamCompletedMatches, arg.HomeTeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCompletedMatchesRow
	for rows.Next() {
		var i GetTeamCompletedMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Title,
			&i.Slug,
			&i.UtcDatetime,
			&i.Venue,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.HomeTeamFlagEmoji,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
			&i.AwayTeamFlagEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMatches = `-- name: GetTeamMatches :many
SELECT 
    m.id, m.home_team_id, m.away_team_id, m.title, m.slug, m.utc_datetime, m.venue, m.home_score, m.away_score,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url, ht.flag_emoji AS home_team_flag_emoji,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url, at.flag_emoji AS away_team_flag_emoji
FROM matches m
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
WHERE m.home_team_id = $1 OR m.away_team_id = $1
ORDER BY m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type GetTeamMatchesParams struct {
	HomeTeamID pgtype.UUID `db:"home_team_id" json:"home_team_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetTeamMatchesRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	HomeTeamID        pgtype.UUID        `db:"home_team_id" json:"home_team_id"`
	AwayTeamID        pgtype.UUID        `db:"away_team_id" json:"away_team_id"`
	Title             string             `db:"title" json:"title"`
	Slug              string             `db:"slug" json:"slug"`
	UtcDatetime       pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	Venue             pgtype.Text        `db:"venue" json:"venue"`
	HomeScore         int32              `db:"home_score" json:"home_score"`
	AwayScore         int32              `db:"away_score" json:"away_score"`
	HomeTeamName      string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl   pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	HomeTeamFlagEmoji pgtype.Text        `db:"home_team_flag_emoji" json:"home_team_flag_emoji"`
	AwayTeamName      string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl   pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
	AwayTeamFlagEmoji pgtype.Text        `db:"away_team_flag_emoji" json:"away_team_flag_emoji"`
}

func (q *Queries) GetTeamMatches(ctx context.Context, arg GetTeamMatchesParams) ([]GetTeamMatchesRow, error) {
	rows, err := q.db.Query(ctx, getTeamMatches, arg.HomeTeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMatchesRow
	for rows.Next() {
		var i GetTeamMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Title,
			&i.Slug,
			&i.UtcDatetime,
			&i.Venue,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.HomeTeamFlagEmoji,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
			&i.AwayTeamFlagEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamPerformances = `-- name: GetTeamPerformances :many
SELECT 
    p.id AS performance_id, p.title AS performance_title, p.cover_image_url AS performance_cover_image, p.minutes_played, p.average_rating,
    pl.id AS player_id, pl.name AS player_name, pl.slug AS player_slug, pl.photo_url AS player_photo_url,
    m.id AS match_id, m.title AS match_title, m.slug AS match_slug, m.utc_datetime AS match_utc_datetime
FROM performances p
JOIN player_teams pt ON p.player_team_id = pt.id
JOIN players pl ON p.player_id = pl.id
JOIN matches m ON p.match_id = m.id
WHERE pt.team_id = $1
ORDER BY m.utc_datetime DESC
LIMIT $2 OFFSET $3
`

type GetTeamPerformancesParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetTeamPerformancesRow struct {
	PerformanceID         pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle      string             `db:"performance_title" json:"performance_title"`
	PerformanceCoverImage pgtype.Text        `db:"performance_cover_image" json:"performance_cover_image"`
	MinutesPlayed         int32              `db:"minutes_played" json:"minutes_played"`
	AverageRating         pgtype.Numeric     `db:"average_rating" json:"average_rating"`
	PlayerID              pgtype.UUID        `db:"player_id" json:"player_id"`
	PlayerName            string             `db:"player_name" json:"player_name"`
	PlayerSlug            string             `db:"player_slug" json:"player_slug"`
	PlayerPhotoUrl        pgtype.Text        `db:"player_photo_url" json:"player_photo_url"`
	MatchID               pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle            string             `db:"match_title" json:"match_title"`
	MatchSlug             string             `db:"match_slug" json:"match_slug"`
	MatchUtcDatetime      pgtype.Timestamptz `db:"match_utc_datetime" json:"match_utc_datetime"`
}

func (q *Queries) GetTeamPerformances(ctx context.Context, arg GetTeamPerformancesParams) ([]GetTeamPerformancesRow, error) {
	rows, err := q.db.Query(ctx, getTeamPerformances, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamPerformancesRow
	for rows.Next() {
		var i GetTeamPerformancesRow
		if err := rows.Scan(
			&i.PerformanceID,
			&i.PerformanceTitle,
			&i.PerformanceCoverImage,
			&i.MinutesPlayed,
			&i.AverageRating,
			&i.PlayerID,
			&i.PlayerName,
			&i.PlayerSlug,
			&i.PlayerPhotoUrl,
			&i.MatchID,
			&i.MatchTitle,
			&i.MatchSlug,
			&i.MatchUtcDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamRatings = `-- name: GetTeamRatings :many
SELECT 
    mr.id AS rating_id, mr.rating, mr.created_at AS rated_at,
    u.id AS user_id, u.username, u.display_name, u.avatar_url,
    m.id AS match_id, m.title AS match_title, m.slug AS match_slug
FROM match_ratings mr
JOIN matches m ON mr.match_id = m.id
JOIN users u ON mr.user_id = u.id
WHERE m.home_team_id = $1 OR m.away_team_id = $1
ORDER BY mr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetTeamRatingsParams struct {
	HomeTeamID pgtype.UUID `db:"home_team_id" json:"home_team_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetTeamRatingsRow struct {
	RatingID    pgtype.UUID        `db:"rating_id" json:"rating_id"`
	Rating      pgtype.Numeric     `db:"rating" json:"rating"`
	RatedAt     pgtype.Timestamptz `db:"rated_at" json:"rated_at"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	MatchID     pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle  string             `db:"match_title" json:"match_title"`
	MatchSlug   string             `db:"match_slug" json:"match_slug"`
}

func (q *Queries) GetTeamRatings(ctx context.Context, arg GetTeamRatingsParams) ([]GetTeamRatingsRow, error) {
	rows, err := q.db.Query(ctx, getTeamRatings, arg.HomeTeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamRatingsRow
	for rows.Next() {
		var i GetTeamRatingsRow
		if err := rows.Scan(
			&i.RatingID,
			&i.Rating,
			&i.RatedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.MatchID,
			&i.MatchTitle,
			&i.MatchSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamReviews = `-- name: GetTeamReviews :many
SELECT 
    r.id AS review_id, r.title AS review_title, r.content AS review_content, r.created_at AS review_created_at,
    u.id AS user_id, u.username, u.display_name, u.avatar_url,
    p.id AS performance_id, p.title AS performance_title,
    m.id AS match_id, m.title AS match_title
FROM performance_reviews r
JOIN performances p ON r.performance_id = p.id
JOIN player_teams pt ON p.player_team_id = pt.id
JOIN matches m ON p.match_id = m.id
JOIN users u ON r.user_id = u.id
WHERE pt.team_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type GetTeamReviewsParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetTeamReviewsRow struct {
	ReviewID         pgtype.UUID        `db:"review_id" json:"review_id"`
	ReviewTitle      pgtype.Text        `db:"review_title" json:"review_title"`
	ReviewContent    string             `db:"review_content" json:"review_content"`
	ReviewCreatedAt  pgtype.Timestamptz `db:"review_created_at" json:"review_created_at"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Username         string             `db:"username" json:"username"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PerformanceID    pgtype.UUID        `db:"performance_id" json:"performance_id"`
	PerformanceTitle string             `db:"performance_title" json:"performance_title"`
	MatchID          pgtype.UUID        `db:"match_id" json:"match_id"`
	MatchTitle       string             `db:"match_title" json:"match_title"`
}

func (q *Queries) GetTeamReviews(ctx context.Context, arg GetTeamReviewsParams) ([]GetTeamReviewsRow, error) {
	rows, err := q.db.Query(ctx, getTeamReviews, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamReviewsRow
	for rows.Next() {
		var i GetTeamReviewsRow
		if err := rows.Scan(
			&i.ReviewID,
			&i.ReviewTitle,
			&i.ReviewContent,
			&i.ReviewCreatedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.PerformanceID,
			&i.PerformanceTitle,
			&i.MatchID,
			&i.MatchTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamUpcomingMatches = `-- name: GetTeamUpcomingMatches :many
SELECT 
    m.id, m.home_team_id, m.away_team_id, m.title, m.slug, m.utc_datetime, m.venue,
    ht.name AS home_team_name, ht.logo_url AS home_team_logo_url, ht.flag_emoji AS home_team_flag_emoji,
    at.name AS away_team_name, at.logo_url AS away_team_logo_url, at.flag_emoji AS away_team_flag_emoji
FROM matches m
JOIN teams ht ON m.home_team_id = ht.id
JOIN teams at ON m.away_team_id = at.id
WHERE (m.home_team_id = $1 OR m.away_team_id = $1) AND m.utc_datetime > now()
ORDER BY m.utc_datetime ASC
LIMIT $2 OFFSET $3
`

type GetTeamUpcomingMatchesParams struct {
	HomeTeamID pgtype.UUID `db:"home_team_id" json:"home_team_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetTeamUpcomingMatchesRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	HomeTeamID        pgtype.UUID        `db:"home_team_id" json:"home_team_id"`
	AwayTeamID        pgtype.UUID        `db:"away_team_id" json:"away_team_id"`
	Title             string             `db:"title" json:"title"`
	Slug              string             `db:"slug" json:"slug"`
	UtcDatetime       pgtype.Timestamptz `db:"utc_datetime" json:"utc_datetime"`
	Venue             pgtype.Text        `db:"venue" json:"venue"`
	HomeTeamName      string             `db:"home_team_name" json:"home_team_name"`
	HomeTeamLogoUrl   pgtype.Text        `db:"home_team_logo_url" json:"home_team_logo_url"`
	HomeTeamFlagEmoji pgtype.Text        `db:"home_team_flag_emoji" json:"home_team_flag_emoji"`
	AwayTeamName      string             `db:"away_team_name" json:"away_team_name"`
	AwayTeamLogoUrl   pgtype.Text        `db:"away_team_logo_url" json:"away_team_logo_url"`
	AwayTeamFlagEmoji pgtype.Text        `db:"away_team_flag_emoji" json:"away_team_flag_emoji"`
}

func (q *Queries) GetTeamUpcomingMatches(ctx context.Context, arg GetTeamUpcomingMatchesParams) ([]GetTeamUpcomingMatchesRow, error) {
	rows, err := q.db.Query(ctx, getTeamUpcomingMatches, arg.HomeTeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamUpcomingMatchesRow
	for rows.Next() {
		var i GetTeamUpcomingMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Title,
			&i.Slug,
			&i.UtcDatetime,
			&i.Venue,
			&i.HomeTeamName,
			&i.HomeTeamLogoUrl,
			&i.HomeTeamFlagEmoji,
			&i.AwayTeamName,
			&i.AwayTeamLogoUrl,
			&i.AwayTeamFlagEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsByCountry = `-- name: GetTeamsByCountry :many
SELECT 
    t.id, t.country_id, t.name, t.short_name, t.slug, t.type, t.logo_url, t.flag_emoji
FROM teams t
WHERE t.country_id = $1
ORDER BY t.name
`

type GetTeamsByCountryRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	CountryID pgtype.UUID `db:"country_id" json:"country_id"`
	Name      string      `db:"name" json:"name"`
	ShortName string      `db:"short_name" json:"short_name"`
	Slug      string      `db:"slug" json:"slug"`
	Type      TeamType    `db:"type" json:"type"`
	LogoUrl   pgtype.Text `db:"logo_url" json:"logo_url"`
	FlagEmoji pgtype.Text `db:"flag_emoji" json:"flag_emoji"`
}

func (q *Queries) GetTeamsByCountry(ctx context.Context, countryID pgtype.UUID) ([]GetTeamsByCountryRow, error) {
	rows, err := q.db.Query(ctx, getTeamsByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamsByCountryRow
	for rows.Next() {
		var i GetTeamsByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.Name,
			&i.ShortName,
			&i.Slug,
			&i.Type,
			&i.LogoUrl,
			&i.FlagEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT 
    t.id, t.country_id, t.name, t.short_name, t.slug, t.type, t.logo_url, t.flag_emoji, t.founded_year, t.created_at, t.updated_at
FROM teams t
ORDER BY t.name
LIMIT $1 OFFSET $2
`

type ListTeamsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListTeamsRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	Name        string             `db:"name" json:"name"`
	ShortName   string             `db:"short_name" json:"short_name"`
	Slug        string             `db:"slug" json:"slug"`
	Type        TeamType           `db:"type" json:"type"`
	LogoUrl     pgtype.Text        `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4        `db:"founded_year" json:"founded_year"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.Name,
			&i.ShortName,
			&i.Slug,
			&i.Type,
			&i.LogoUrl,
			&i.FlagEmoji,
			&i.FoundedYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeams = `-- name: SearchTeams :many
SELECT 
    t.id, t.country_id, t.name, t.short_name, t.slug, t.type, t.logo_url, t.flag_emoji
FROM teams t
WHERE t.name ILIKE $1 OR t.short_name ILIKE $1
ORDER BY t.name
LIMIT $2 OFFSET $3
`

type SearchTeamsParams struct {
	Name   string `db:"name" json:"name"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type SearchTeamsRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	CountryID pgtype.UUID `db:"country_id" json:"country_id"`
	Name      string      `db:"name" json:"name"`
	ShortName string      `db:"short_name" json:"short_name"`
	Slug      string      `db:"slug" json:"slug"`
	Type      TeamType    `db:"type" json:"type"`
	LogoUrl   pgtype.Text `db:"logo_url" json:"logo_url"`
	FlagEmoji pgtype.Text `db:"flag_emoji" json:"flag_emoji"`
}

func (q *Queries) SearchTeams(ctx context.Context, arg SearchTeamsParams) ([]SearchTeamsRow, error) {
	rows, err := q.db.Query(ctx, searchTeams, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTeamsRow
	for rows.Next() {
		var i SearchTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.Name,
			&i.ShortName,
			&i.Slug,
			&i.Type,
			&i.LogoUrl,
			&i.FlagEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET
    country_id = COALESCE($2, country_id),
    name = COALESCE($3, name),
    short_name = COALESCE($4, short_name),
    slug = COALESCE($5, slug),
    type = COALESCE($6, type),
    logo_url = COALESCE($7, logo_url),
    flag_emoji = COALESCE($8, flag_emoji),
    founded_year = COALESCE($9, founded_year),
    updated_at = now()
WHERE id = $1
RETURNING id, country_id, name, short_name, slug, type, logo_url, flag_emoji, founded_year, created_at, updated_at
`

type UpdateTeamParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	CountryID   pgtype.UUID `db:"country_id" json:"country_id"`
	Name        string      `db:"name" json:"name"`
	ShortName   string      `db:"short_name" json:"short_name"`
	Slug        string      `db:"slug" json:"slug"`
	Type        TeamType    `db:"type" json:"type"`
	LogoUrl     pgtype.Text `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4 `db:"founded_year" json:"founded_year"`
}

type UpdateTeamRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CountryID   pgtype.UUID        `db:"country_id" json:"country_id"`
	Name        string             `db:"name" json:"name"`
	ShortName   string             `db:"short_name" json:"short_name"`
	Slug        string             `db:"slug" json:"slug"`
	Type        TeamType           `db:"type" json:"type"`
	LogoUrl     pgtype.Text        `db:"logo_url" json:"logo_url"`
	FlagEmoji   pgtype.Text        `db:"flag_emoji" json:"flag_emoji"`
	FoundedYear pgtype.Int4        `db:"founded_year" json:"founded_year"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (UpdateTeamRow, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.CountryID,
		arg.Name,
		arg.ShortName,
		arg.Slug,
		arg.Type,
		arg.LogoUrl,
		arg.FlagEmoji,
		arg.FoundedYear,
	)
	var i UpdateTeamRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Name,
		&i.ShortName,
		&i.Slug,
		&i.Type,
		&i.LogoUrl,
		&i.FlagEmoji,
		&i.FoundedYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
