// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trending.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTrendingScores = `-- name: CountTrendingScores :one
SELECT COUNT(*) FROM trending_scores
WHERE entity_type = $1
  AND time_window = $2
`

type CountTrendingScoresParams struct {
	EntityType string `db:"entity_type" json:"entity_type"`
	TimeWindow string `db:"time_window" json:"time_window"`
}

func (q *Queries) CountTrendingScores(ctx context.Context, arg CountTrendingScoresParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTrendingScores, arg.EntityType, arg.TimeWindow)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTrendingScoresByTypeAndWindow = `-- name: DeleteTrendingScoresByTypeAndWindow :exec
DELETE FROM trending_scores
WHERE entity_type = $1
  AND time_window = $2
`

type DeleteTrendingScoresByTypeAndWindowParams struct {
	EntityType string `db:"entity_type" json:"entity_type"`
	TimeWindow string `db:"time_window" json:"time_window"`
}

func (q *Queries) DeleteTrendingScoresByTypeAndWindow(ctx context.Context, arg DeleteTrendingScoresByTypeAndWindowParams) error {
	_, err := q.db.Exec(ctx, deleteTrendingScoresByTypeAndWindow, arg.EntityType, arg.TimeWindow)
	return err
}

const getTrendingScores = `-- name: GetTrendingScores :many
SELECT
    ts.id,
    ts.entity_type,
    ts.entity_id,
    ts.time_window,
    ts.score,
    ts.rank,
    ts.calculated_at
FROM trending_scores ts
WHERE ts.entity_type = $1
  AND ts.time_window = $2
ORDER BY ts.rank ASC
LIMIT $3
`

type GetTrendingScoresParams struct {
	EntityType string `db:"entity_type" json:"entity_type"`
	TimeWindow string `db:"time_window" json:"time_window"`
	Limit      int32  `db:"limit" json:"limit"`
}

func (q *Queries) GetTrendingScores(ctx context.Context, arg GetTrendingScoresParams) ([]TrendingScore, error) {
	rows, err := q.db.Query(ctx, getTrendingScores, arg.EntityType, arg.TimeWindow, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendingScore
	for rows.Next() {
		var i TrendingScore
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.TimeWindow,
			&i.Score,
			&i.Rank,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrendingScore = `-- name: UpsertTrendingScore :exec
INSERT INTO trending_scores (entity_type, entity_id, time_window, score, rank, calculated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (entity_type, entity_id, time_window)
DO UPDATE SET
    score = EXCLUDED.score,
    rank = EXCLUDED.rank,
    calculated_at = now()
`

type UpsertTrendingScoreParams struct {
	EntityType string         `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID    `db:"entity_id" json:"entity_id"`
	TimeWindow string         `db:"time_window" json:"time_window"`
	Score      pgtype.Numeric `db:"score" json:"score"`
	Rank       int32          `db:"rank" json:"rank"`
}

func (q *Queries) UpsertTrendingScore(ctx context.Context, arg UpsertTrendingScoreParams) error {
	_, err := q.db.Exec(ctx, upsertTrendingScore,
		arg.EntityType,
		arg.EntityID,
		arg.TimeWindow,
		arg.Score,
		arg.Rank,
	)
	return err
}
