// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    display_name,
    email,
    bio,
    avatar_url,
    password_hash,
    email_verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, display_name, email, bio, avatar_url, email_verified, role, created_at, updated_at
`

type CreateUserParams struct {
	Username      string      `db:"username" json:"username"`
	DisplayName   string      `db:"display_name" json:"display_name"`
	Email         string      `db:"email" json:"email"`
	Bio           pgtype.Text `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text `db:"avatar_url" json:"avatar_url"`
	PasswordHash  pgtype.Text `db:"password_hash" json:"password_hash"`
	EmailVerified bool        `db:"email_verified" json:"email_verified"`
}

type CreateUserRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Email         string             `db:"email" json:"email"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Role          UserRole           `db:"role" json:"role"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Bio,
		arg.AvatarUrl,
		arg.PasswordHash,
		arg.EmailVerified,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT id, username, display_name, bio, avatar_url, created_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetPublicProfileRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPublicProfile(ctx context.Context, id pgtype.UUID) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, id)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserActivity = `-- name: GetUserActivity :many
SELECT 'match_review' AS activity_type, id, created_at, title AS description
FROM match_reviews
WHERE match_reviews.user_id = $1
UNION ALL
SELECT 'performance_review' AS activity_type, id, created_at, title AS description
FROM performance_reviews
WHERE performance_reviews.user_id = $1
UNION ALL
SELECT 'match_rating' AS activity_type, id, created_at, 'Rated a match' AS description
FROM match_ratings
WHERE match_ratings.user_id = $1
UNION ALL
SELECT 'performance_rating' AS activity_type, id, created_at, 'Rated a player performance' AS description
FROM performance_ratings
WHERE performance_ratings.user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserActivityParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserActivityRow struct {
	ActivityType string             `db:"activity_type" json:"activity_type"`
	ID           pgtype.UUID        `db:"id" json:"id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Description  pgtype.Text        `db:"description" json:"description"`
}

func (q *Queries) GetUserActivity(ctx context.Context, arg GetUserActivityParams) ([]GetUserActivityRow, error) {
	rows, err := q.db.Query(ctx, getUserActivity, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActivityRow
	for rows.Next() {
		var i GetUserActivityRow
		if err := rows.Scan(
			&i.ActivityType,
			&i.ID,
			&i.CreatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, display_name, email, bio, avatar_url, password_hash, email_verified, role, created_at, updated_at
FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Email         string             `db:"email" json:"email"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"password_hash"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Role          UserRole           `db:"role" json:"role"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, email, bio, avatar_url, password_hash, email_verified, role, created_at, updated_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Email         string             `db:"email" json:"email"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"password_hash"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Role          UserRole           `db:"role" json:"role"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, email, bio, avatar_url, password_hash, email_verified, role, created_at, updated_at
FROM users
WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Email         string             `db:"email" json:"email"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"password_hash"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Role          UserRole           `db:"role" json:"role"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLikesReceived = `-- name: GetUserLikesReceived :one
SELECT (
    (SELECT COUNT(*) FROM match_review_likes mrl JOIN match_reviews mr ON mrl.review_id = mr.id WHERE mr.user_id = $1) +
    (SELECT COUNT(*) FROM performance_review_likes prl JOIN performance_reviews pr ON prl.review_id = pr.id WHERE pr.user_id = $1) +
    (SELECT COUNT(*) FROM match_review_comment_likes mrcl JOIN match_review_comments mrc ON mrcl.comment_id = mrc.id WHERE mrc.user_id = $1)
)::bigint AS likes_count
`

func (q *Queries) GetUserLikesReceived(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserLikesReceived, userID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}

const getUserRatingCount = `-- name: GetUserRatingCount :one
SELECT (
    (SELECT COUNT(*) FROM match_ratings mr WHERE mr.user_id = $1) +
    (SELECT COUNT(*) FROM performance_ratings pr WHERE pr.user_id = $1)
)::bigint AS rating_count
`

func (q *Queries) GetUserRatingCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserRatingCount, userID)
	var rating_count int64
	err := row.Scan(&rating_count)
	return rating_count, err
}

const getUserRecentComments = `-- name: GetUserRecentComments :many
SELECT 'match_review' AS comment_type, mrc.id, mrc.review_id, mrc.body, mrc.created_at, mrc.updated_at
FROM match_review_comments mrc
WHERE mrc.user_id = $1
UNION ALL
SELECT 'performance_review' AS comment_type, prc.id, prc.review_id, prc.body, prc.created_at, prc.updated_at
FROM performance_review_comments prc
WHERE prc.user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserRecentCommentsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserRecentCommentsRow struct {
	CommentType string             `db:"comment_type" json:"comment_type"`
	ID          pgtype.UUID        `db:"id" json:"id"`
	ReviewID    pgtype.UUID        `db:"review_id" json:"review_id"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserRecentComments(ctx context.Context, arg GetUserRecentCommentsParams) ([]GetUserRecentCommentsRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentComments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentCommentsRow
	for rows.Next() {
		var i GetUserRecentCommentsRow
		if err := rows.Scan(
			&i.CommentType,
			&i.ID,
			&i.ReviewID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentRatings = `-- name: GetUserRecentRatings :many
SELECT 'match' AS rating_type, mr.id, mr.match_id AS entity_id, mr.rating, mr.created_at, mr.updated_at, COALESCE(m.slug, '')::text AS match_slug
FROM match_ratings mr
JOIN matches m ON mr.match_id = m.id
WHERE mr.user_id = $1
UNION ALL
SELECT 'performance' AS rating_type, pr.id, pr.performance_id AS entity_id, pr.rating, pr.created_at, pr.updated_at, ''::text AS match_slug
FROM performance_ratings pr
WHERE pr.user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserRecentRatingsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserRecentRatingsRow struct {
	RatingType string             `db:"rating_type" json:"rating_type"`
	ID         pgtype.UUID        `db:"id" json:"id"`
	EntityID   pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Rating     pgtype.Numeric     `db:"rating" json:"rating"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MatchSlug  string             `db:"match_slug" json:"match_slug"`
}

func (q *Queries) GetUserRecentRatings(ctx context.Context, arg GetUserRecentRatingsParams) ([]GetUserRecentRatingsRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentRatings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentRatingsRow
	for rows.Next() {
		var i GetUserRecentRatingsRow
		if err := rows.Scan(
			&i.RatingType,
			&i.ID,
			&i.EntityID,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentReviews = `-- name: GetUserRecentReviews :many
SELECT 'match' AS review_type, mr.id, mr.match_id AS entity_id, mr.title, mr.content, mr.created_at, mr.updated_at, COALESCE(m.slug, '')::text AS match_slug
FROM match_reviews mr
JOIN matches m ON mr.match_id = m.id
WHERE mr.user_id = $1
UNION ALL
SELECT 'performance' AS review_type, pr.id, pr.performance_id AS entity_id, pr.title, pr.content, pr.created_at, pr.updated_at, ''::text AS match_slug
FROM performance_reviews pr
WHERE pr.user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserRecentReviewsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetUserRecentReviewsRow struct {
	ReviewType string             `db:"review_type" json:"review_type"`
	ID         pgtype.UUID        `db:"id" json:"id"`
	EntityID   pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Title      pgtype.Text        `db:"title" json:"title"`
	Content    string             `db:"content" json:"content"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MatchSlug  string             `db:"match_slug" json:"match_slug"`
}

func (q *Queries) GetUserRecentReviews(ctx context.Context, arg GetUserRecentReviewsParams) ([]GetUserRecentReviewsRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentReviews, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentReviewsRow
	for rows.Next() {
		var i GetUserRecentReviewsRow
		if err := rows.Scan(
			&i.ReviewType,
			&i.ID,
			&i.EntityID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReviewCount = `-- name: GetUserReviewCount :one
SELECT (
    (SELECT COUNT(*) FROM match_reviews mr WHERE mr.user_id = $1) +
    (SELECT COUNT(*) FROM performance_reviews pr WHERE pr.user_id = $1)
)::bigint AS review_count
`

func (q *Queries) GetUserReviewCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserReviewCount, userID)
	var review_count int64
	err := row.Scan(&review_count)
	return review_count, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, display_name, email, bio, avatar_url, created_at, updated_at
FROM users
WHERE username ILIKE $1 OR display_name ILIKE $1
ORDER BY username
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Username string `db:"username" json:"username"`
	Limit    int32  `db:"limit" json:"limit"`
	Offset   int32  `db:"offset" json:"offset"`
}

type SearchUsersRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Bio,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvatar = `-- name: UpdateAvatar :one
UPDATE users
SET avatar_url = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, bio, avatar_url, created_at, updated_at
`

type UpdateAvatarParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

type UpdateAvatarRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (UpdateAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateAvatar, arg.ID, arg.AvatarUrl)
	var i UpdateAvatarRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBio = `-- name: UpdateBio :one
UPDATE users
SET bio = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, bio, avatar_url, created_at, updated_at
`

type UpdateBioParams struct {
	ID  pgtype.UUID `db:"id" json:"id"`
	Bio pgtype.Text `db:"bio" json:"bio"`
}

type UpdateBioRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateBio(ctx context.Context, arg UpdateBioParams) (UpdateBioRow, error) {
	row := q.db.QueryRow(ctx, updateBio, arg.ID, arg.Bio)
	var i UpdateBioRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users
SET display_name = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, bio, avatar_url, created_at, updated_at
`

type UpdateDisplayNameParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

type UpdateDisplayNameRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (UpdateDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i UpdateDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE users
SET email = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, bio, avatar_url, created_at, updated_at
`

type UpdateEmailParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Email string      `db:"email" json:"email"`
}

type UpdateEmailRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (UpdateEmailRow, error) {
	row := q.db.QueryRow(ctx, updateEmail, arg.ID, arg.Email)
	var i UpdateEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, role, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Role UserRole    `db:"role" json:"role"`
}

type UpdateUserRoleRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Role        UserRole           `db:"role" json:"role"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users
SET username = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, bio, avatar_url, created_at, updated_at
`

type UpdateUsernameParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Username string      `db:"username" json:"username"`
}

type UpdateUsernameRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UpdateUsernameRow, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i UpdateUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
