// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_follows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followUser = `-- name: FollowUser :one
INSERT INTO user_follows (
    follower_id,
    following_id
) VALUES (
    $1, $2
)
RETURNING follower_id, following_id, created_at
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (UserFollow, error) {
	row := q.db.QueryRow(ctx, followUser, arg.FollowerID, arg.FollowingID)
	var i UserFollow
	err := row.Scan(&i.FollowerID, &i.FollowingID, &i.CreatedAt)
	return i, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT 
    u.id, u.username, u.display_name, u.email, u.bio, u.avatar_url, uf.created_at AS followed_at
FROM user_follows uf
JOIN users u ON uf.follower_id = u.id
WHERE uf.following_id = $1
ORDER BY uf.created_at DESC
`

type GetFollowersRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	FollowedAt  pgtype.Timestamptz `db:"followed_at" json:"followed_at"`
}

func (q *Queries) GetFollowers(ctx context.Context, followingID pgtype.UUID) ([]GetFollowersRow, error) {
	rows, err := q.db.Query(ctx, getFollowers, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Bio,
			&i.AvatarUrl,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersCount = `-- name: GetFollowersCount :one
SELECT COUNT(*)::bigint AS followers_count
FROM user_follows
WHERE following_id = $1
`

func (q *Queries) GetFollowersCount(ctx context.Context, followingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowersCount, followingID)
	var followers_count int64
	err := row.Scan(&followers_count)
	return followers_count, err
}

const getFollowing = `-- name: GetFollowing :many
SELECT 
    u.id, u.username, u.display_name, u.email, u.bio, u.avatar_url, uf.created_at AS followed_at
FROM user_follows uf
JOIN users u ON uf.following_id = u.id
WHERE uf.follower_id = $1
ORDER BY uf.created_at DESC
`

type GetFollowingRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       string             `db:"email" json:"email"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	FollowedAt  pgtype.Timestamptz `db:"followed_at" json:"followed_at"`
}

func (q *Queries) GetFollowing(ctx context.Context, followerID pgtype.UUID) ([]GetFollowingRow, error) {
	rows, err := q.db.Query(ctx, getFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingRow
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Bio,
			&i.AvatarUrl,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*)::bigint AS following_count
FROM user_follows
WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, followerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, followerID)
	var following_count int64
	err := row.Scan(&following_count)
	return following_count, err
}

const getMutualFollowers = `-- name: GetMutualFollowers :many
SELECT 
    u.id, u.username, u.display_name, u.avatar_url
FROM users u
WHERE u.id IN (
    SELECT uf1.follower_id FROM user_follows uf1 WHERE uf1.following_id = $1
    INTERSECT
    SELECT uf2.follower_id FROM user_follows uf2 WHERE uf2.following_id = $2
)
ORDER BY u.username
`

type GetMutualFollowersParams struct {
	FollowingID   pgtype.UUID `db:"following_id" json:"following_id"`
	FollowingID_2 pgtype.UUID `db:"following_id_2" json:"following_id_2"`
}

type GetMutualFollowersRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetMutualFollowers(ctx context.Context, arg GetMutualFollowersParams) ([]GetMutualFollowersRow, error) {
	rows, err := q.db.Query(ctx, getMutualFollowers, arg.FollowingID, arg.FollowingID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMutualFollowersRow
	for rows.Next() {
		var i GetMutualFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMutualFollowing = `-- name: GetMutualFollowing :many
SELECT 
    u.id, u.username, u.display_name, u.avatar_url
FROM users u
WHERE u.id IN (
    SELECT uf1.following_id FROM user_follows uf1 WHERE uf1.follower_id = $1
    INTERSECT
    SELECT uf2.following_id FROM user_follows uf2 WHERE uf2.follower_id = $2
)
ORDER BY u.username
`

type GetMutualFollowingParams struct {
	FollowerID   pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowerID_2 pgtype.UUID `db:"follower_id_2" json:"follower_id_2"`
}

type GetMutualFollowingRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetMutualFollowing(ctx context.Context, arg GetMutualFollowingParams) ([]GetMutualFollowingRow, error) {
	rows, err := q.db.Query(ctx, getMutualFollowing, arg.FollowerID, arg.FollowerID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMutualFollowingRow
	for rows.Next() {
		var i GetMutualFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM user_follows
    WHERE follower_id = $1 AND following_id = $2
)::boolean AS is_following
`

type IsFollowingParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM user_follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
