// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredOTPs = `-- name: CleanExpiredOTPs :exec
DELETE FROM user_otps
WHERE expires_at < now()
`

func (q *Queries) CleanExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredOTPs)
	return err
}

const cleanExpiredRefreshTokens = `-- name: CleanExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

func (q *Queries) CleanExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredRefreshTokens)
	return err
}

const createOTP = `-- name: CreateOTP :exec
INSERT INTO user_otps (email, otp_code, purpose, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateOTPParams struct {
	Email     string             `db:"email" json:"email"`
	OtpCode   string             `db:"otp_code" json:"otp_code"`
	Purpose   string             `db:"purpose" json:"purpose"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.Exec(ctx, createOTP,
		arg.Email,
		arg.OtpCode,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteOTP = `-- name: DeleteOTP :exec
DELETE FROM user_otps
WHERE id = $1
`

func (q *Queries) DeleteOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOTP, id)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, expires_at, created_at
FROM refresh_tokens
WHERE token = $1 AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, email, otp_code, purpose, expires_at, created_at
FROM user_otps
WHERE email = $1 AND otp_code = $2 AND purpose = $3 AND expires_at > now()
LIMIT 1
`

type GetValidOTPParams struct {
	Email   string `db:"email" json:"email"`
	OtpCode string `db:"otp_code" json:"otp_code"`
	Purpose string `db:"purpose" json:"purpose"`
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (UserOtp, error) {
	row := q.db.QueryRow(ctx, getValidOTP, arg.Email, arg.OtpCode, arg.Purpose)
	var i UserOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OtpCode,
		&i.Purpose,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE email = $1
`

type UpdateUserPasswordParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Email, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    bio = COALESCE($3, bio),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, email, bio, avatar_url, email_verified, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Bio         pgtype.Text `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

type UpdateUserProfileRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Email         string             `db:"email" json:"email"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Bio,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET email_verified = TRUE, updated_at = now()
WHERE email = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, email)
	return err
}
